### ISSUE TITLE
nss-myhostname/sd-netlink should use kernel route filtering for local_gateways()

### ISSUE THREAD

**Issue by grawity** [systemd/systemd#13199]
**systemd version the issue has been seen with**

242 and older, on Arch Linux

**Unexpected behaviour you saw**

Context:

 1. Some of my systems have ~70k routes from BGP installed into a non-default routing table.
 2. My nsswitch.conf is configured for `hosts: files dns myhostname`.
 3. The system also runs some software that wants to perform reverse-DNS lookups of client IP addresses (in this case Postfix, but it doesn't matter which).

Symptoms:

Whenever nss_myhostname receives an IP address query (gethostbyaddr, rDNS) it loads all routes from all tables into memory at once, and this results in the process permanently growing by ~120 MB. In the case of Postfix, that's a **10x** increase over its normal memory usage:

```
● postfix.service - Postfix Mail Transport Agent
   [...]
    Tasks: 7 (limit: 2373)
   Memory: 127.7M
   CGroup: /system.slice/postfix.service
```

As far as I could figure out, this is a problem with sd-netlink, and not with nss_myhostname itself. I see that the local_gateways() function gets a complete route dump, then skips all routes that aren't suitable for the gateway lookup. Although the dump is free'd later, it still causes the process to grow, and it's a problem when multiple "worker" processes do it.

**Expected behaviour you didn't see**

I think local_gateways() should use [kernel-side route filtering][1] to only dump routes in RT_TABLE_MAIN, which would _massively_ reduce the amount of routes it needs to receive.

The kernel-side filtering feature was added in Linux 4.20, after getting rejected [several years ago][2]. It seems that using it should be completely backwards-compatible, i.e. sd-netlink would still be given the full dump on older kernels.

Unfortunately the kernel doesn't seem to allow filtering by dst (e.g. requesting only routes for ::/0 and 0.0.0.0/0), but I think filtering by table would already improve things.

**Steps to reproduce the problem**

1. Have ~70k routes from BGP installed into a non-default routing table.
2. Have the "myhostname" module enabled in nsswitch.
3. Do a gethostbyname lookup for `_gateway`, or do a gethostbyaddr lookup for any random IP address that lacks rDNS.
4. Measure the memory usage of the process after the lookup is done.

[1]: https://git.kernel.org/linus/effe6792662495ad9c175bf0d9c53459a51fdbbd
[2]: https://patchwork.ozlabs.org/patch/133440/

**Comment by yuwata** [comment]
Not sure, but maybe already fixed by #13145?

**Comment by grawity** [comment]
> Not sure, but maybe already fixed by #13145?

Huh, I didn't realize that bit was added literally just this week.

It's a good change, but it probably won't help in this case, as it's still a client-side filter -- the whole raw dump still has to be received by sd-netlink first, and I assume that's where the memory usage comes from. (Besides, the existing code already skips all BGP routes due to nonzero dst_prefixlen anyway.)

**Comment by poettering** [comment]
Can we even do a kernel-side filter on this? (if we can we totally should, of course)

**Comment by poettering** [comment]
So, I played around with this, unless I am confused the kernel doesn't allow such "focussed" dumps. It has the NLM_F_MATCH for this purpose, but as http://man7.org/linux/man-pages/man7/netlink.7.html says: "Not implemented yet.")... And indeed, if I set the route table nr in the netlink request this changes nothing at all...

So, I take it we can't do much about this, there's now other option than downloading all routes and filtering in userspace...

This would require kernel work to get fixed properly. Let's close this bug until then though...

I don't think the status quo is too horrible, after all we only do this when the user explicitly resolves _gateway, which should not happen by accident... Hence it's a perfomance optimization to have a pinpointed dumping, but not more. But of course, if the kernel learns this one day, I am all for supporting this here.

Closing hence, hope that makes sense?

**Comment by grawity** [comment]
@poettering:

> So, I played around with this, unless I am confused the kernel doesn't allow such "focussed" dumps. It has the NLM_F_MATCH for this purpose, but as http://man7.org/linux/man-pages/man7/netlink.7.html says: "Not implemented yet.")... And indeed, if I set the route table nr in the netlink request this changes nothing at all...

According to [Linux commit logs](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=effe6792662495ad9c175bf0d9c53459a51fdbbd), this _did_ get implemented recently (in kernel 4.20).

(I guess you tested against 4.19? To be honest I haven't tested it against my system yet, so it's possible that the kernel's implementation is still broken, too.)

> I don't think the status quo is too horrible, after all we only do this when the user explicitly resolves _gateway, which should not happen by accident... Hence it's a perfomance optimization to have a pinpointed dumping, but not more. But of course, if the kernel learns this one day, I am all for supporting this here.

No, unfortunately it's much broader than that – it also affects all programs which resolve IP addresses to hostnames (using gethostbyaddr or similar), and any IP address that doesn't have real "reverse DNS" will cause nss_myhostname to do the same thing.

(This is what prompted the bug report in the first place...) For example:

    getent hosts 185.36.81.165
    getent -s myhostname hosts 185.36.81.165

It's not an urgent issue as I can simply disable nss_myhostname on affected systems, but given that the kernel already has a relevant patch in 4.20+, I'd like this to be reopened for future improvement.

**Comment by poettering** [comment]
I tested this with `Linux iota 5.1.18-300.fc30.x86_64 #1 SMP Mon Jul 15 15:42:34 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`...

Weird. Reopened for now. I wonder how the netlink request has to look like precisely for the filtering to take effect

**Comment by grawity** [comment]
Indeed, somehow it works for iproute2:

```
$ strace -e sendto,recvmsg ip -6 route show table 7
sendto(3, [{{len=36, type=RTM_GETROUTE, flags=NLM_F_REQUEST|NLM_F_DUMP, seq=1565673948, pid=0},
            {rtm_family=AF_INET6, rtm_dst_len=0, rtm_src_len=0, rtm_tos=0, rtm_table=RT_TABLE_UNSPEC,
             rtm_protocol=RTPROT_UNSPEC, rtm_scope=RT_SCOPE_UNIVERSE, rtm_type=RTN_UNSPEC,
             rtm_flags=0},
            {{nla_len=8, nla_type=RTA_TABLE}, 0x7}},
           {len=0, type=0 /* NLMSG_??? */, flags=0, seq=0, pid=0}],
          156, 0, NULL, 0) = 156
```

But not for my sd-netlink hack attempts, as much as I try to minimize the differences (flags, rtm_family, rtm_table, payload):

```
$ strace -e sendto,recvmsg ./test-local-addresses
sendto(3, {{len=36, type=RTM_GETROUTE, flags=NLM_F_REQUEST|NLM_F_DUMP, seq=1, pid=0},
           {rtm_family=AF_INET6, rtm_dst_len=0, rtm_src_len=0, rtm_tos=0, rtm_table=RT_TABLE_UNSPEC,
            rtm_protocol=RTPROT_UNSPEC, rtm_scope=RT_SCOPE_UNIVERSE, rtm_type=RTN_UNICAST,
            rtm_flags=0},
           {{nla_len=8, nla_type=RTA_TABLE}, 0x7}},
          36, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 16) = 36
```

Maybe it's that iproute adds a second message at the end of the same packet?

**Comment by jdccdevel** [comment]
This issue is still present in Version 245.6. Kernel 5.6.15 and 5.7.2

In my case it's being triggered by a reverse-dns lookup, for a IPv4 address without a PTR record, via the nss_myhostname shared library. 

I have several servers that are encountering a rather severe version of this issue. Both systems are running BGP, and have 828k+ routes loaded. This issue causes some processes to use 1.3GB of memory, just to do a reverse DNS lookup!

For debugging purposes, I'm triggering it using local (RFC1918) IPv4 address without a PTR record present, but any IPv4 address from the Internet does the same thing if it has no PTR record. (I have not tested IPv6)

I can trigger the issue with the following command:
getent -s myhostname hosts 172.20.1.1

To me, this issue is very significant, as it has the potential to be the basis for a Denial Of Service attack via Memory Exhaustion. 

Many processes (i.e. postfix, sshd, etc) do a reverse dns lookup before authenticating, some simply for logging purposes. It would be very easy to trigger an out-of-memory condition this way. (That's how I encountered this bug.) It's also not straightforward for a sysadmin to track down, since it can happen basically anywhere a DNS lookup occurs, (but only for some lookups).

My BGP process sends routes to table 50, so they aren't in the main or default table.
My routing tables have the following counts:
main: 24 routes
50: 828872 routes 
default: 3 routes

Perhaps a sanity check could/should be implemented? Is it possible to limit the routes queried for resolving "_gateway" to a particular routing table(s) (i.e. main and/or default)? Perhaps the library could disable "_gateway" resolution entirely if there's more than a certain number of routes loaded, or the if the address isn't in a local subnet. 

I can reproduce this issue pretty consistently, although not as severely, in a VM (~250 to 350MB memory used, vs 1.3GB). I would be happy to help test any potential fixes.

**Comment by bjo81** [comment]
I come from #11384 and in my case, I have around  98000 IPv6 routes in a special routing table. The issue also occurs when e.g. trying to `mtr` an IPv4 host though the IPv4 table has only 3 routes. So all 98000 IPv6 routes are loaded every time though IPv4 is used?

**Comment by yuwata** [comment]
> Unfortunately the kernel doesn't seem to allow filtering by dst (e.g. requesting only routes for ::/0 and 0.0.0.0/0), but I think filtering by table would already improve things.

@grawity Filtering by table is implemented in #19716. If possible, please try the current main branch.

**Comment by grawity** [comment]
> @grawity Filtering by table is implemented in #19716. If possible, please try the current main branch.

Seems to work nicely in manual tests.

Before:

```
$ /bin/time getent -s myhostname hosts 1.2.3.4
0.08user 0.13system 0:00.21elapsed 99%CPU (0avgtext+0avgdata 207416maxresident)k
```

After:

```
$ /bin/time getent -s myhostname hosts 1.2.3.4
0.00user 0.00system 0:00.00elapsed 100%CPU (0avgtext+0avgdata 3220maxresident)k
```

**Comment by yuwata** [comment]
Thank you for testing. Let's close this.
