### ISSUE TITLE
[systemd >=242] LACP no longer works on NetworkManager bond interfaces

### ISSUE THREAD

**Issue by chenxiaolong** [systemd/systemd#15208]
**systemd version the issue has been seen with** / **Used distribution**

* `systemd-245~rc1-4.fc32.x86_64` (Fedora 32 Beta)
* `systemd-243.7-1.fc31.x86_64` (Fedora 31)
* Self-built systemd 242, 243, 245

**Expected behaviour you didn't see**

Ever since systemd 242 (possibly around the `MACAddressPolicy` changes), LACP (802.3ad) seems to be broken when the interfaces are configured with NetworkManager. This happened somewhere between version 241 and 242, but I was unable to find the exact commit with git bisect due to some commits not building or not being bootable on my system.

Setup:
* Completely clean Fedora Server installation (with versions above) and no config changes beyond NetworkManager
* Network Manager configuration: https://gist.github.com/chenxiaolong/8236466ddc7e75ab3fc3b2d03232ef1d
  * All settings are defaults created by the Fedora installer aside from picking the bond type to be LACP
  * `bond0` (LACP) containing physical interfaces `ens7` and `ens8`
  * `bridge0` has `bond0` attached
  * DHCP on `bridge0`
* NIC: Intel X540-AT2 (ixgbe driver) w/10Gbps RJ45
* Switch: Arista DCS-7050TX-64-R with default settings + LACP configuration for two ports: https://gist.github.com/chenxiaolong/263f5bc576ec85a15d43514aef719ec5

When bringing up the interface with `nmcli con up 'Bridge connection 1'`, LACP never converges and the `bond0` link never comes up. Doing a `tcpdump` on the physical interfaces, `ens7` and `ens8`, when the system is in this state shows `packets dropped by interface` increasing by 1 every 30 seconds. I suspect LACPDUs are being dropped.

On the exact same F31 or F32 beta system with no configuration files changed, if I compile and install systemd 241, everything works fine. It also does not happen if I use either of the following workarounds:

1. Create `/etc/systemd/network/98-bond-mac.link` with:

    ```ini
    [Match]
    Type=bond

    [Link]
    MACAddressPolicy=none
    ```

2. ~Set any MAC address for `bond0` in `/etc/sysconfig/network-scripts/ifcfg-bridge0_slave_1`:~ EDIT: This works for ixgbe, but not mlx5_core (Mellanox).

    ```bash
    # This value literally works--seems to be ignored
    HWADDR=aa:bb:cc:dd:ee:ff
    ```

I have no idea why this would be impacting LACP. With or without the workarounds, `ens7`, `ens8`, and `bond0` have the same MAC address. 

Also, what's interesting is that once the interface comes up with one of these workarounds, they continue working even after I get rid of the workaround. If I reload the `bonding` kernel module or reboot, then it breaks again. Are my workarounds with the MAC address stuff triggering some sort of side effect in systemd or udev that's "unbreaking" LACP?

**Unexpected behaviour you saw**

Something related to the MAC address policy seems to cause LACPDUs to get dropped and the bond link to never come up.

**Steps to reproduce the problem**

1. Set up switch for LACP on two ports
2. On the Linux side, use NetworkManager
3. Create a bond interface consisting of two physical interfaces
4. Create a bridge interface with the bond interface attached
5. (Optionally) set up DHCP on the bridge interface
6. Check `/proc/net/bonding/bond0` and note that LACP doesn't converge

---

Side note: I also tested on Ubuntu 20.04 daily builds (systemd 245.2-1ubuntu1). It does _not_ have this problem, which is suspect is due to their patch: https://git.launchpad.net/ubuntu/+source/systemd/tree/debian/patches/Skip-falling-back-to-device-name-when-net_get_name-device.patch?h=applied/245.2-1ubuntu1

**Comment by jmontleon** [comment]
There's a bug filed for this against Fedora with a few others besides myself experiencing the issue.
https://bugzilla.redhat.com/show_bug.cgi?id=1786978

I had the same problem and the workaround of creating /etc/systemd/network/98-bond-mac.link worked for me.

**Comment by snowsnoot** [comment]
Looks like it has been fixed, no longer able to reproduce on systemd-245.7-1.fc32.x86_64 and on kernel 5.7.14-200.fc32.x86_64

**Comment by yuwata** [comment]
Interesting. If my check is correct, we have not changed anything related to this issue. Did kernel fix this issue? @snowsnoot If possible, could you test with older kernels?

**Comment by jmontleon** [comment]
I should have some time tomorrow to remove the workaround and see if I can confirm that it is working (my system is also running Fedora 32).

**Comment by AKS74n** [comment]
Hi, I can confirm that the issue still exist. But may only happen if directly upgrade from F30 to F32 or F33.
My platform is using two Intel I350 ethernet interface bond as LACP mode, and connect to DELL N2048 switch.

Everyone works fine before upgrade, but after upgrade to F32, Bonding seems working but can't ping out.
Then tried to use other port and set as single connection to get temperately internet connection and upgrade to F33.
But the issue still exist.

Now everything back normal by add 98-bond-mac.link into /etc/systemd/network/.

The F33 system is combined:
Kernel: 5.9.10-200.fc33.x86_64
Systemd: 2.4.6.6-3.fc33

**Comment by llunved** [comment]
I ran into the issue after an upgrade from F31->F32. The solution for me was as described above creating /etc/systemd/network/98-bond-mac.link with:
```
[Match]
Type=bond

[Link]
MACAddressPolicy=none
```

**Comment by admered1** [comment]
I just had this issue on two machines, a F31 and a F32, when I changed the bond types to integrate a new switch.

In both cases the bond simply didn't work, but with the above file now in place they both work fine.

**Comment by keszybz** [comment]
This needs to be debugged by someone who has the appropriate hardware... *Something* must be different between the two setups, most likely how MAC addresses are assigned.

**Comment by marcelbrouwers** [comment]
We had this same issue on Fedora CoreOS 33 after migrating from 32 with a network bond and Mellanox CX516A-CCAT cards, during an OKD upgrade to 4.6. Creating /etc/systemd/network/98-bond-mac.link like mentioned above worked as a solution.

**Comment by bac-w** [comment]
FCOS 32, Systemd version 245.8-2.fc32, kernel 5.8.17-200.fc32, driver ixgbe
Add on all slave interfaces via nmcli
`cloned-mac-address=permanent`
solves this problem for me

**Comment by mattblack** [comment]
Can confirm this problem in Fedora 33. Strangely it only comes when the bond is set to manual in networkmanager. It doesn't appear when it is set to automatic. The 98-bond-mac.link fix works for me.

**Comment by csmart** [comment]
My machines have two x 802.3ad bonds each and I ran into this same issue on Fedora 33 and 34 with the following NICs (not that it seems to matter):

 - Intel x710 (`i40e`) 10GbE
 - Intel x520 (`ixgbe`) 10GbE
 - Intel i210 (`igb`) 1GbE

On a fresh boot the bond never comes up and the interfaces are still in `monitoring` churn state.

```
$ uptime
 22:33:02 up 6 min,  1 user,  load average: 0.02, 0.05, 0.03

$ cat /proc/net/bonding/bond-* |grep -i "state"
Actor Churn State: monitoring
Partner Churn State: monitoring
Actor Churn State: monitoring
Partner Churn State: monitoring
Actor Churn State: monitoring
Partner Churn State: monitoring
Actor Churn State: monitoring
Partner Churn State: monitoring
```

I noticed that if I unload and re-load the NIC kernel modules (_without_ having the `/etc/systemd/network/98-bond-mac.link` work around in place) that the bond is able to come up in about 1 minute.

```
$ for x in i40iw i40e igb ; do sudo rmmod ${x} ; done
$ sudo modprobe i40e
$ sudo modprobe igb
$ date > bond.log ; sleep 5
$ while true ; do cat /proc/net/bonding/bond-* |grep monitoring || { date >> bond.log ; break ;} ; sleep 0.5 ; done
$ cat bond.log
Sat 01 May 2021 22:33:25 AEST
Sat 01 May 2021 22:34:35 AEST
```

After a fresh boot, each interface in a bond has a `permaddr`, take `bond-lab` for example:

```
$ ip l show dev enp8s0
2: enp8s0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 9000 qdisc mq master bond-prov state UP mode DEFAULT group default qlen 1000
    link/ether 42:71:19:89:71:95 brd ff:ff:ff:ff:ff:ff permaddr d0:50:99:dc:d0:2b

$ ip l show dev enp9s0
3: enp9s0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 9000 qdisc mq master bond-prov state UP mode DEFAULT group default qlen 1000
    link/ether 42:71:19:89:71:95 brd ff:ff:ff:ff:ff:ff permaddr d0:50:99:dc:d0:2c

$ ip l show bond-lab
7: bond-prov: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 42:71:19:89:71:95 brd ff:ff:ff:ff:ff:ff
```

After I reload the kernel modules, the same interfaces look like this, noting that only one has a `permaddr` set:

```
$ ip l show dev enp8s0
11: enp8s0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 9000 qdisc mq master bond-prov state UP mode DEFAULT group default qlen 1000
    link/ether d0:50:99:dc:d0:2b brd ff:ff:ff:ff:ff:ff

$ ip l show dev enp9s0
12: enp9s0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 9000 qdisc mq master bond-prov state UP mode DEFAULT group default qlen 1000
    link/ether d0:50:99:dc:d0:2b brd ff:ff:ff:ff:ff:ff permaddr d0:50:99:dc:d0:2c

$ ip l show dev bond-prov
7: bond-prov: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether d0:50:99:dc:d0:2b brd ff:ff:ff:ff:ff:ff
```

So reloading the module seems to have the same effect as the workaround.

**Comment by csmart** [comment]
I don't know if any of this is helpful, but @chenxiaolong mentioned potential dropped LACP packets, I've captured LACP packets on all interfaces on one of my nodes from a fresh boot (without work around, so bond is down) for a few minutes and didn't see any dropped packets (note one bond on the node is configured for fast and one is slow).

```
$ sudo tcpdump -ni any -e ether proto 0x8809
...
09:26:48.505941 enp8s0 M   ifindex 2 f4:92:bf:7c:b5:0b ethertype Slow Protocols (0x8809), length 130: LACPv1, length 110
09:26:48.506091 enp9s0 M   ifindex 3 f4:92:bf:7c:b5:0b ethertype Slow Protocols (0x8809), length 130: LACPv1, length 110
09:26:48.586333 enp2s0f0 M   ifindex 4 74:ac:b9:ad:79:4d ethertype Slow Protocols (0x8809), length 130: LACPv1, length 110
09:26:49.509979 enp8s0 M   ifindex 2 f4:92:bf:7c:b5:0b ethertype Slow Protocols (0x8809), length 130: LACPv1, length 110
09:26:49.510128 enp9s0 M   ifindex 3 f4:92:bf:7c:b5:0b ethertype Slow Protocols (0x8809), length 130: LACPv1, length 110
...
354 packets captured
354 packets received by filer
0 packets dropped
```

Looking at the port info, actor is in state `7` while partner is in state `69`:

```
Slave Interface: enp2s0f0
MII Status: up
Speed: 10000 Mbps
Duplex: full
Link Failure Count: 0
Permanent HW addr: 3c:fd:fe:de:fe:24
Slave queue ID: 0
Aggregator ID: 1
Actor Churn State: monitoring
Partner Churn State: monitoring
Actor Churned Count: 0
Partner Churned Count: 0
details actor lacp pdu:
    system priority: 65535
    system mac address: be:c8:52:2c:78:09
    port key: 15
    port priority: 255
    port number: 1
    port state: 7
details partner lacp pdu:
    system priority: 32768
    system mac address: 74:ac:b9:ad:79:4c
    oper key: 30
    port priority: 128
    port number: 9
    port state: 69

```

So given the definitions:
```
/* Port state definitions (43.4.2.2 in the 802.3ad standard) */
#define AD_STATE_LACP_ACTIVITY   0x1
#define AD_STATE_LACP_TIMEOUT    0x2
#define AD_STATE_AGGREGATION     0x4
#define AD_STATE_SYNCHRONIZATION 0x8
#define AD_STATE_COLLECTING      0x10
#define AD_STATE_DISTRIBUTING    0x20
#define AD_STATE_DEFAULTED       0x40
#define AD_STATE_EXPIRED         0x80
```

I guess state 7 means:
 - AD_STATE_AGGREGATION
 - AD_STATE_LACP_TIMEOUT
 - AD_STATE_LACP_ACTIVITY

And I guess state 69 means:
 - AD_STATE_DEFAULTED
 - AD_STATE_DISTRIBUTING
 - AD_STATE_SYNCHRONIZATION
 - AD_STATE_LACP_ACTIVITY

In case it's useful for anyone, I've enabled debug on one of my nodes before the workaround is applied:

```
$ echo 'module bonding =p' | sudo tee /sys/kernel/debug/dynamic_debug/control 
```

Some dmesg info from fresh boot with no workaround in place, I guess `[  129.865048] bond-lab: bond_should_notify_peers: slave NULL` is probably related:
```
$ [csmart@dev2 ~]$ cat dmesg |egrep "bond|igb|i40|enp"
[    1.865717] i40e: Intel(R) Ethernet Connection XL710 Network Driver
[    1.865719] i40e: Copyright (c) 2013 - 2019 Intel Corporation.
[    1.869547] igb: Intel(R) Gigabit Ethernet Network Driver
[    1.869548] igb: Copyright (c) 2007-2014 Intel Corporation.
[    1.879105] i40e 0000:02:00.0: fw 6.0.48442 api 1.7 nvm 6.01 0x800035cf 1.1747.0 [8086:1572] [8086:0007]
[    1.896773] igb 0000:08:00.0: added PHC on eth0
[    1.896774] igb 0000:08:00.0: Intel(R) Gigabit Ethernet Network Connection
[    1.896775] igb 0000:08:00.0: eth0: (PCIe:2.5Gb/s:Width x1) d0:50:99:dc:d0:2b
[    1.896838] igb 0000:08:00.0: eth0: PBA No: 001300-000
[    1.896839] igb 0000:08:00.0: Using MSI-X interrupts. 4 rx queue(s), 4 tx queue(s)
[    1.925422] igb 0000:09:00.0: added PHC on eth1
[    1.925423] igb 0000:09:00.0: Intel(R) Gigabit Ethernet Network Connection
[    1.925424] igb 0000:09:00.0: eth1: (PCIe:2.5Gb/s:Width x1) d0:50:99:dc:d0:2c
[    1.925487] igb 0000:09:00.0: eth1: PBA No: 001300-000
[    1.925488] igb 0000:09:00.0: Using MSI-X interrupts. 4 rx queue(s), 4 tx queue(s)
[    2.139569] i40e 0000:02:00.0: MAC address: 3c:fd:fe:de:fe:24
[    2.139712] i40e 0000:02:00.0: FW LLDP is enabled
[    2.146269] igb 0000:08:00.0 enp8s0: renamed from eth0
[    2.148557] i40e 0000:02:00.0 eth2: NIC Link is Up, 10 Gbps Full Duplex, Flow Control: RX/TX
[    2.150295] i40e 0000:02:00.0: PCI-Express: Speed 8.0GT/s Width x8
[    2.158979] i40e 0000:02:00.0: Features: PF-id[0] VFs: 64 VSIs: 66 QP: 20 RSS FD_ATR FD_SB NTUPLE VxLAN Geneve PTP VEPA
[    2.161106] igb 0000:09:00.0 enp9s0: renamed from eth1
[    2.171119] i40e 0000:02:00.1: fw 6.0.48442 api 1.7 nvm 6.01 0x800035cf 1.1747.0 [8086:1572] [8086:0000]
[    2.428337] i40e 0000:02:00.1: MAC address: 3c:fd:fe:de:fe:25
[    2.428503] i40e 0000:02:00.1: FW LLDP is enabled
[    2.437338] i40e 0000:02:00.1 eth0: NIC Link is Up, 10 Gbps Full Duplex, Flow Control: RX/TX
[    2.439099] i40e 0000:02:00.1: PCI-Express: Speed 8.0GT/s Width x8
[    2.447814] i40e 0000:02:00.1: Features: PF-id[1] VFs: 64 VSIs: 66 QP: 20 RSS FD_ATR FD_SB NTUPLE VxLAN Geneve PTP VEPA
[    2.448569] i40e 0000:02:00.1 enp2s0f1: renamed from eth0
[    2.456602] i40e 0000:02:00.0 enp2s0f0: renamed from eth2
[    3.722164] i40e: Registered client i40iw
[    3.752525] cdc_ether 1-8.2:2.0 enp0s20f0u8u2c2: renamed from usb0
[    8.524957] IPv6: ADDRCONF(NETDEV_CHANGE): enp2s0f0: link becomes ready
[    8.846110] i40e 0000:02:00.0 enp2s0f0: set new mac address be:c8:52:2c:78:09
[    8.856609] bond-lab: (slave enp2s0f0): Enslaving as a backup interface with an up link
[    8.910422] i40e 0000:02:00.1 enp2s0f1: set new mac address be:c8:52:2c:78:09
[    8.921026] bond-lab: (slave enp2s0f1): Enslaving as a backup interface with an up link
[    8.921075] IPv6: ADDRCONF(NETDEV_CHANGE): bond-lab: link becomes ready
[   11.540027] igb 0000:09:00.0 enp9s0: igb: enp9s0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[   11.745685] IPv6: ADDRCONF(NETDEV_CHANGE): enp9s0: link becomes ready
[   11.827657] bond-prov: (slave enp9s0): Enslaving as a backup interface with a down link
[   12.080044] igb 0000:08:00.0 enp8s0: igb: enp8s0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[   12.290305] IPv6: ADDRCONF(NETDEV_CHANGE): enp8s0: link becomes ready
[   12.372141] bond-prov: (slave enp8s0): Enslaving as a backup interface with a down link
[   15.334951] igb 0000:09:00.0 enp9s0: igb: enp9s0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[   15.577622] bond-prov: (slave enp9s0): link status definitely up, 1000 Mbps full duplex
[   15.577635] bond-prov: Warning: No 802.3ad response from the link partner for any adapters in the bond
[   15.577646] bond-prov: active interface up!
[   15.577666] IPv6: ADDRCONF(NETDEV_CHANGE): bond-prov: link becomes ready
[   15.813020] igb 0000:08:00.0 enp8s0: igb: enp8s0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[   16.097620] bond-prov: (slave enp8s0): link status definitely up, 1000 Mbps full duplex
[  129.553072] bond-lab: bond_should_notify_peers: slave NULL
[  129.561066] bond-prov: bond_should_notify_peers: slave enp9s0
[  129.657042] bond-lab: bond_should_notify_peers: slave NULL
[  129.665042] bond-prov: bond_should_notify_peers: slave enp9s0
[  129.761041] bond-lab: bond_should_notify_peers: slave NULL
[  129.770059] bond-prov: bond_should_notify_peers: slave enp9s0
[  129.865048] bond-lab: bond_should_notify_peers: slave NULL
[  129.873041] bond-prov: bond_should_notify_peers: slave enp9s0
[  129.890468] bond-prov: (slave enp8s0): Received LACPDU on port 2
[  129.890488] bond-prov: (slave enp8s0): Rx Machine: Port=2, Last State=6, Curr State=6
[  129.890495] bond-prov: (slave enp8s0): partner sync=0
[  129.890627] bond-prov: (slave enp9s0): Received LACPDU on port 1
[  129.890642] bond-prov: (slave enp9s0): Rx Machine: Port=1, Last State=6, Curr State=6
[  129.890649] bond-prov: (slave enp9s0): partner sync=0
[  129.969044] bond-lab: bond_should_notify_peers: slave NULL
[  129.977044] bond-prov: bond_should_notify_peers: slave enp9s0
[  130.073039] bond-lab: bond_should_notify_peers: slave NULL
[  130.081051] bond-prov: bond_should_notify_peers: slave enp9s0
[  130.177039] bond-lab: bond_should_notify_peers: slave NULL
[  130.185041] bond-prov: bond_should_notify_peers: slave enp9s0
[  130.281050] bond-lab: bond_should_notify_peers: slave NULL
[  130.289037] bond-prov: bond_should_notify_peers: slave enp9s0
...
```

And `/sys`:
```
$ sudo grep bond /sys/kernel/debug/dynamic_debug/control
drivers/net/bonding/bond_main.c:5187 [bonding]bond_init =p "Begin bond_init\012"
drivers/net/bonding/bond_main.c:5060 [bonding]bond_check_params =p "Warning: either miimon or arp_interval and arp_ip_target module parameters must be specified, otherwise bonding will not detect link failures! see bonding.txt for details\012"
drivers/net/bonding/bond_main.c:4373 [bonding]bond_update_slave_arr =p "(slave %s): Adding slave to tx hash array[%d]\012"
drivers/net/bonding/bond_main.c:4349 [bonding]bond_update_slave_arr =p "bond_3ad_get_active_agg_info failed\012"
drivers/net/bonding/bond_main.c:4082 [bonding]bond_set_mac_address =p "(slave %s): %s: unwind err %d\012"
drivers/net/bonding/bond_main.c:4058 [bonding]bond_set_mac_address =p "(slave %s): %s: err %d\012"
drivers/net/bonding/bond_main.c:4048 [bonding]bond_set_mac_address =p "(slave %s): %s: slave=%p\012"
drivers/net/bonding/bond_main.c:4035 [bonding]bond_set_mac_address =p "%s: bond=%p\012"
drivers/net/bonding/bond_main.c:4010 [bonding]bond_change_mtu =p "(slave %s): unwind err %d\012"
drivers/net/bonding/bond_main.c:3990 [bonding]bond_change_mtu =p "(slave %s): err %d setting mtu to %d\012"
drivers/net/bonding/bond_main.c:3976 [bonding]bond_change_mtu =p "(slave %s): s %p c_m %p\012"
drivers/net/bonding/bond_main.c:3973 [bonding]bond_change_mtu =p "bond=%p, new_mtu=%d\012"
drivers/net/bonding/bond_main.c:3844 [bonding]bond_do_ioctl =p "(slave %s): slave_dev=%p:\012"
drivers/net/bonding/bond_main.c:3783 [bonding]bond_do_ioctl =p "bond_ioctl: cmd=%d\012"
drivers/net/bonding/bond_main.c:3429 [bonding]bond_netdev_event =p "%s received %s\012"
drivers/net/bonding/bond_main.c:3326 [bonding]bond_slave_netdev_event =p "(slave %s): %s called\012"
drivers/net/bonding/bond_main.c:3318 [bonding]bond_slave_netdev_event =p "%s called on NULL slave\012"
drivers/net/bonding/bond_main.c:3288 [bonding]bond_master_netdev_event =p "%s called\012"
drivers/net/bonding/bond_main.c:2782 [bonding]bond_arp_rcv =p "(slave %s): %s: %s/%d av %d sv %d sip %pI4 tip %pI4\012"
drivers/net/bonding/bond_main.c:2757 [bonding]bond_arp_rcv =p "(slave %s): %s: skb->dev %s\012"
drivers/net/bonding/bond_main.c:2728 [bonding]bond_validate_arp =p "(slave %s): %s: sip %pI4 not found in targets\012"
drivers/net/bonding/bond_main.c:2721 [bonding]bond_validate_arp =p "(slave %s): %s: sip %pI4 tip %pI4 not found\012"
drivers/net/bonding/bond_main.c:2702 [bonding]bond_arp_send_all =p "(slave %s): no path to arp_ip_target %pI4 via rt.dev %s\012"
drivers/net/bonding/bond_main.c:2670 [bonding]bond_arp_send_all =p "(slave %s): %s: target %pI4\012"
drivers/net/bonding/bond_main.c:2612 [bonding]bond_arp_send =p "(slave %s): outer tag: proto %X vid %X\012"
drivers/net/bonding/bond_main.c:2599 [bonding]bond_arp_send =p "(slave %s): inner tag: proto %X vid %X\012"
drivers/net/bonding/bond_main.c:2576 [bonding]bond_arp_send =p "(slave %s): arp %d on slave: dst %pI4 src %pI4\012"
drivers/net/bonding/bond_main.c:2077 [bonding]__bond_release_one =p "(slave %s): cannot release slave\012"
drivers/net/bonding/bond_main.c:1927 [bonding]bond_enslave =p "(slave %s): Error %d calling bond_sysfs_slave_add\012"
drivers/net/bonding/bond_main.c:1921 [bonding]bond_enslave =p "(slave %s): Error %d calling bond_master_upper_dev_link\012"
drivers/net/bonding/bond_main.c:1915 [bonding]bond_enslave =p "(slave %s): Error %d calling netdev_rx_handler_register\012"
drivers/net/bonding/bond_main.c:1883 [bonding]bond_enslave =p "(slave %s): This slave is always active in trunk mode\012"
drivers/net/bonding/bond_main.c:1840 [bonding]bond_enslave =p "(slave %s): Initial state of slave is BOND_LINK_%s\012"
drivers/net/bonding/bond_main.c:1637 [bonding]bond_enslave =p "(slave %s): change device type from %d to %d\012"
drivers/net/bonding/bond_main.c:1615 [bonding]bond_enslave =p "(slave %s): is esp-hw-offload capable\012"
drivers/net/bonding/bond_main.c:1611 [bonding]bond_enslave =p "(slave %s): is !NETIF_F_VLAN_CHALLENGED\012"
drivers/net/bonding/bond_main.c:1602 [bonding]bond_enslave =p "(slave %s): is NETIF_F_VLAN_CHALLENGED\012"
drivers/net/bonding/bond_main.c:937 [bonding]bond_should_notify_peers =p "bond_should_notify_peers: slave %s\012"
drivers/net/bonding/bond_main.c:758 [bonding]bond_set_dev_addr =p "(slave %s): bond_dev=%p slave_dev=%p slave_dev->addr_len=%d\012"
drivers/net/bonding/bond_3ad.c:2543 [bonding]bond_3ad_handle_link_change =p "(slave %s): Port %d changed link status to %s\012"
drivers/net/bonding/bond_3ad.c:2497 [bonding]bond_3ad_adapter_speed_duplex_changed =p "(slave %s): Port %d changed speed/duplex\012"
drivers/net/bonding/bond_3ad.c:2410 [bonding]bond_3ad_rx_indication =p "(slave %s): Received an unknown Marker subtype on port %d\012"
drivers/net/bonding/bond_3ad.c:2405 [bonding]bond_3ad_rx_indication =p "(slave %s): Received Marker Response on port %d\012"
drivers/net/bonding/bond_3ad.c:2400 [bonding]bond_3ad_rx_indication =p "(slave %s): Received Marker Information on port %d\012"
drivers/net/bonding/bond_3ad.c:2384 [bonding]bond_3ad_rx_indication =p "(slave %s): Received LACPDU on port %d\012"
drivers/net/bonding/bond_3ad.c:2190 [bonding]bond_3ad_unbind_slave =p "(slave %s): Unbinding port %d\012"
drivers/net/bonding/bond_3ad.c:2134 [bonding]bond_3ad_unbind_slave =p "(slave %s): Some port(s) related to LAG %d - replacing with LAG %d\012"
drivers/net/bonding/bond_3ad.c:2095 [bonding]bond_3ad_unbind_slave =p "(slave %s): Unbinding Link Aggregation Group %d\012"
drivers/net/bonding/bond_3ad.c:1939 [bonding]ad_marker_info_received =p "(slave %s): Sent Marker Response on port %d\012"
drivers/net/bonding/bond_3ad.c:1909 [bonding]ad_disable_collecting_distributing =p "(slave %s): Disabling port %d (LAG %d)\012"
drivers/net/bonding/bond_3ad.c:1888 [bonding]ad_enable_collecting_distributing =p "(slave %s): Enabling port %d (LAG %d)\012"
drivers/net/bonding/bond_3ad.c:1789 [bonding]ad_clear_agg =p "%s: LAG %d was cleared\012"
drivers/net/bonding/bond_3ad.c:1732 [bonding]ad_agg_selection_logic =p "(slave %s): Agg=%d; P=%d; a k=%d; p k=%d; Ind=%d; Act=%d\012"
drivers/net/bonding/bond_3ad.c:1729 [bonding]ad_agg_selection_logic =p "(slave %s): LAG %d chosen as the active LAG\012"
drivers/net/bonding/bond_3ad.c:1716 [bonding]ad_agg_selection_logic =p "(slave %s): Agg=%d; P=%d; a k=%d; p k=%d; Ind=%d; Act=%d\012"
drivers/net/bonding/bond_3ad.c:1709 [bonding]ad_agg_selection_logic =p "(slave %s): best ports %p slave %p\012"
drivers/net/bonding/bond_3ad.c:1703 [bonding]ad_agg_selection_logic =p "(slave %s): best Agg=%d; P=%d; a k=%d; p k=%d; Ind=%d; Act=%d\012"
drivers/net/bonding/bond_3ad.c:1515 [bonding]ad_port_selection_logic =p "(slave %s): Port %d joined LAG %d (new LAG)\012"
drivers/net/bonding/bond_3ad.c:1468 [bonding]ad_port_selection_logic =p "(slave %s): Port %d joined LAG %d (existing LAG)\012"
drivers/net/bonding/bond_3ad.c:1419 [bonding]ad_port_selection_logic =p "(slave %s): Port %d left LAG %d\012"
drivers/net/bonding/bond_3ad.c:1340 [bonding]ad_periodic_machine =p "(slave %s): Periodic Machine: Port=%d, Last State=%d, Curr State=%d\012"
drivers/net/bonding/bond_3ad.c:1258 [bonding]ad_tx_machine =p "(slave %s): Sent LACPDU on port %d\012"
drivers/net/bonding/bond_3ad.c:1136 [bonding]ad_rx_machine =p "(slave %s): Rx Machine: Port=%d, Last State=%d, Curr State=%d\012"
drivers/net/bonding/bond_3ad.c:1018 [bonding]ad_mux_machine =p "(slave %s): Mux Machine: Port=%d, Last State=%d, Curr State=%d\012"
drivers/net/bonding/bond_3ad.c:784 [bonding]__update_lacpdu_from_port =p "(slave %s): update lacpdu: actor port state %x\012"
drivers/net/bonding/bond_3ad.c:497 [bonding]__record_pdu =p "(slave %s): partner sync=0\012"
drivers/net/bonding/bond_3ad.c:493 [bonding]__record_pdu =p "(slave %s): partner sync=1\012"
drivers/net/bonding/bond_3ad.c:358 [bonding]__get_duplex =p "(slave %s): Port %d Received status NOT full duplex update from adapter\012"
drivers/net/bonding/bond_3ad.c:352 [bonding]__get_duplex =p "(slave %s): Port %d Received status full duplex update from adapter\012"
drivers/net/bonding/bond_3ad.c:327 [bonding]__get_link_speed =p "(slave %s): Port %d Received link speed %d update from adapter\012"
drivers/net/bonding/bond_alb.c:929 [bonding]alb_send_lp_vid =p "(slave %s): Send learning packet: mac %pM vlan %d\012"
drivers/net/bonding/bond_alb.c:692 [bonding]rlb_arp_xmit =p "(slave %s): Server sent ARP Request packet\012"
drivers/net/bonding/bond_alb.c:671 [bonding]rlb_arp_xmit =p "(slave %s): Server sent ARP Reply packet\012"
drivers/net/bonding/bond_alb.c:298 [bonding]rlb_arp_recv =p "(slave %s): Server received an ARP Reply from client\012"
drivers/net/bonding/bond_options.c:1486 [bonding]bond_option_ad_user_port_key_set =p "Setting ad_user_port_key to %llu\012"
drivers/net/bonding/bond_options.c:1472 [bonding]bond_option_ad_actor_system_set =p "Setting ad_actor_system to %pM\012"
drivers/net/bonding/bond_options.c:1446 [bonding]bond_option_ad_actor_sys_prio_set =p "Setting ad_actor_sys_prio to %llu\012"
drivers/net/bonding/bond_options.c:1436 [bonding]bond_option_tlb_dynamic_lb_set =p "Setting dynamic-lb to %s (%llu)\012"
drivers/net/bonding/bond_options.c:1415 [bonding]bond_option_slaves_set =p "(slave %s): Releasing interface\012"
drivers/net/bonding/bond_options.c:1410 [bonding]bond_option_slaves_set =p "(slave %s): Enslaving interface\012"
drivers/net/bonding/bond_options.c:1402 [bonding]bond_option_slaves_set =p "interface %s does not exist!\012"
drivers/net/bonding/bond_options.c:1379 [bonding]bond_option_queue_id_set =p "invalid input for queue_id set\012"
drivers/net/bonding/bond_options.c:1317 [bonding]bond_option_ad_select_set =p "Setting ad_select to %s (%llu)\012"
drivers/net/bonding/bond_options.c:1306 [bonding]bond_option_lacp_rate_set =p "Setting LACP rate to %s (%llu)\012"
drivers/net/bonding/bond_options.c:1286 [bonding]bond_option_pps_set =p "Setting packets per slave to %llu\012"
drivers/net/bonding/bond_options.c:1267 [bonding]bond_option_min_links_set =p "Setting min links value to %llu\012"
drivers/net/bonding/bond_options.c:1228 [bonding]bond_option_resend_igmp_set =p "Setting resend_igmp to %llu\012"
drivers/net/bonding/bond_options.c:1218 [bonding]bond_option_xmit_hash_policy_set =p "Setting xmit hash policy to %s (%llu)\012"
drivers/net/bonding/bond_options.c:1208 [bonding]bond_option_fail_over_mac_set =p "Setting fail_over_mac to %s (%llu)\012"
drivers/net/bonding/bond_options.c:1194 [bonding]bond_option_primary_reselect_set =p "Setting primary_reselect to %s (%llu)\012"
drivers/net/bonding/bond_options.c:1182 [bonding]bond_option_primary_set =p "Recording %s as primary, but it has not been enslaved yet\012"
drivers/net/bonding/bond_options.c:1175 [bonding]bond_option_primary_set =p "Setting primary slave to None\012"
drivers/net/bonding/bond_options.c:1165 [bonding]bond_option_primary_set =p "(slave %s): Setting as primary slave\012"
drivers/net/bonding/bond_options.c:1156 [bonding]bond_option_primary_set =p "Setting primary slave to None\012"
drivers/net/bonding/bond_options.c:1135 [bonding]bond_option_arp_all_targets_set =p "Setting arp_all_targets to %s (%llu)\012"
drivers/net/bonding/bond_options.c:1125 [bonding]bond_option_arp_validate_set =p "Setting arp_validate to %s (%llu)\012"
drivers/net/bonding/bond_options.c:1073 [bonding]bond_option_arp_ip_target_rem =p "Removing ARP target %pI4\012"
drivers/net/bonding/bond_options.c:1037 [bonding]_bond_option_arp_ip_target_add =p "Adding ARP target %pI4\012"
drivers/net/bonding/bond_options.c:976 [bonding]bond_option_arp_interval_set =p "ARP monitoring has been set up, but no ARP targets have been specified\012"
drivers/net/bonding/bond_options.c:972 [bonding]bond_option_arp_interval_set =p "ARP monitoring cannot be used with MII monitoring. Disabling MII monitoring\012"
drivers/net/bonding/bond_options.c:967 [bonding]bond_option_arp_interval_set =p "Setting ARP monitoring interval to %llu\012"
drivers/net/bonding/bond_options.c:953 [bonding]bond_option_use_carrier_set =p "Setting use_carrier to %llu\012"
drivers/net/bonding/bond_options.c:920 [bonding]_bond_option_delay_set =p "Setting %s to %d\012"
drivers/net/bonding/bond_options.c:873 [bonding]bond_option_miimon_set =p "MII monitoring cannot be used with ARP monitoring - disabling ARP monitoring...\012"
drivers/net/bonding/bond_options.c:870 [bonding]bond_option_miimon_set =p "Note: Updating peer_notif_delay (to %d) since it is a multiple of the miimon value\012"
drivers/net/bonding/bond_options.c:867 [bonding]bond_option_miimon_set =p "Note: Updating downdelay (to %d) since it is a multiple of the miimon value\012"
drivers/net/bonding/bond_options.c:864 [bonding]bond_option_miimon_set =p "Note: Updating updelay (to %d) since it is a multiple of the miimon value\012"
drivers/net/bonding/bond_options.c:860 [bonding]bond_option_miimon_set =p "Setting MII monitoring interval to %llu\012"
drivers/net/bonding/bond_options.c:839 [bonding]bond_option_active_slave_set =p "(slave %s): Setting as active slave\012"
drivers/net/bonding/bond_options.c:835 [bonding]bond_option_active_slave_set =p "(slave %s): is already the current active slave\012"
drivers/net/bonding/bond_options.c:824 [bonding]bond_option_active_slave_set =p "Clearing current active slave\012"
drivers/net/bonding/bond_options.c:775 [bonding]bond_option_mode_set =p "Setting MII monitoring interval to %d\012"
drivers/net/bonding/bond_options.c:766 [bonding]bond_option_mode_set =p "%s mode is incompatible with arp monitoring, start mii monitoring\012"
```

**Comment by BirknerAlex** [comment]
I can confirm that this issue still exists in Fedora 34. 

What I can tell is:

* NIC: Broadcom and subsidiaries BCM57416 NetXtreme-E Dual-Media
* Driver: bnxt_en
* OS: Fedora 34 
* Config: ifcfg-rh and keyfile tested, both does not work

My configuration files:

ifcfg-bond0:
```
DEVICE="bond0"
NAME="bond0"
BRIDGE="bridge2010"
ONBOOT="yes"
TYPE="Bond"
BONDING_MASTER=yes
BONDING_OPTS="mode=802.3ad miimon=100 xmit_hash_policy=layer2+3"
BOOTPROTO="none"
```

ifcfg-enp2s0f0np0:
```
DEVICE="enp2s0f0np0"
NAME="enp2s0f0np0"
MASTER="bond0"
SLAVE=yes
ONBOOT="yes"
TYPE="Ethernet"
BOOTPROTO="none"
```

ifcfg-enp2s0f1np1:
```
DEVICE="enp2s0f1np1"
NAME="enp2s0f1np1"
MASTER="bond0"
SLAVE=yes
ONBOOT="yes"
TYPE="Ethernet"
BOOTPROTO="none"
```

ifcfg-bridge0:
```
# This file is managed by Ansible, do not modify!
DEVICE="bridge2010"
NAME="bridge2010"
ONBOOT="yes"
TYPE="bridge"
IPADDR="xxx"
PREFIX="24"
BOOTPROTO="static"
GATEWAY="xxx"
DNS1="8.8.8.8"
DNS2="8.8.4.4"
```

The workaround from @llunved fixed the issue for me, without the workaround I needed to run `nmcli c u bond0` after each reboot to get it also working. 

Can I help somehow to provide you more information to get this fixed? What do you need?

**Comment by jdbarnes-isi** [comment]
CoreOS 34.20210611.3.0-35.20211119.3.0 have the same issue, and the workaround (/etc/systemd/network/98-bond-mac.link w/ MacAddressPolicy=none) solves the issue.

**Comment by ipaqmaster** [comment]
Same issue on Archlinux on a host with dual Broadcom network interfaces (NetXtreme II BCM5709 Gigabit Ethernet).

The 98-bond-mac.link solution has worked around the problem for me as well.

The LACP/802.3ad bond to my switch would send packets, but even ARP responses were not making it back. The bond interface churn state stayed in "monitoring" for both interfaces. This worked just fine with the CentOS 7.9 install which were on this machine prior.

I stopped NetworkManager and tested making my own bond from scratch and that also worked fine:

`ip link add bond0 type bond miimon 250 mode 802.3ad`
`ip link add link bond0 bond0.10 type vlan id 10`
`ip link set enp11s0f0 master bond0`
`ip link set enp11s0f1 master bond0`
`ip link set enp11s0f0 up`
`ip link set enp11s0f1 up`
`ip link set bond0 up`
`dhclient -v bond0.10 # Success`

So I figured at this point it was somewhere networkmanager or systemd related. Huge thank you for posting a solution.

**Comment by JHBoricua** [comment]
> Same issue on Archlinux on a host with dual Broadcom network interfaces (NetXtreme II BCM5709 Gigabit Ethernet).
> 
> `Kernel 5.16.0-arch1-1` (current at time of comment)
> 
> `systemd 250.2-2`
> 
> `networkmanager 1.34.0-1`
> 
> The 98-bond-mac.link solution has worked around the problem for me as well.
> 
> The LACP/802.3ad bond to my switch would send packets, but even ARP responses were not making it back. The bond interface churn state stayed in "monitoring" for both interfaces. This worked just fine with the CentOS 7.9 install which were on this machine prior.
> 
> I stopped NetworkManager and tested making my own bond from scratch and that also worked fine:
> 
> `ip link add bond0 type bond miimon 250 mode 802.3ad` `ip link add link bond0 bond0.10 type vlan id 10` `ip link set enp11s0f0 master bond0` `ip link set enp11s0f1 master bond0` `ip link set enp11s0f0 up` `ip link set enp11s0f1 up` `ip link set bond0 up` `dhclient -v bond0.10 # Success`
> 
> So I figured at this point it was somewhere networkmanager or systemd related. Huge thank you for posting a solution.

@ipaqmaster Can you clarify something for me? When you say you stopped NetworkManager and created the bond manually and it works (which I presume means the LACP bond comes up after reboot), does that still requires the 98-bond-mac.link file to be present?

**Comment by ipaqmaster** [comment]
Apologies I'll edit the post to be more clear as well - I mean that I stopped the NetworkManager service (giving up) and tried making the bond myself with the `ip` command just to see how that goes and that worked fine. It was only bonds created by NetworkManager experiencing this problem.

After I added the 98-bond-mac.link file with its contents and rebooted, NetworkManager was able to create the bond and actually establish it at boot. Unrelated to my manual successful `ip` test earlier that day.

Using the ip command to make a bond interface before applying the 98-bond-mac.link file was just a non-networkmanager test to see if I could get it to work at all even manually.

**Comment by thom311** [comment]
@ipaqmaster regarding https://github.com/systemd/systemd/issues/15208#issuecomment-1013639283, it's not clear to me what is going on.

Presumably, if you run `ip link add` commands, udev would also change the MAC address of the bond (or why not)? So the MAC address does not seem to be the difference, and it's not clear why the setup using NetworkManager wouldn't work.

**Comment by alkisg** [comment]
I too just got this after upgrading my servers from Ubuntu 20.04 to 22.04:

- It didn't happen on Ubuntu 20.04, kernel 5.4, systemd 245 (that includes the aforementioned Ubuntu patch),
- After upgrading to 22.04, kernel 5.15, systemd 249 it started happening
- All my NICs are affected, igb and mlx4_core
- The 98-bond-mac.link workaround works (or rmmod/modprobe)
- I noticed that if slave1 got up before slave0, it worked even without the workaround; i.e. it worked randomly in a few of the boots.

**Comment by vot4anto** [comment]
I just install a RL9 and have the same the same issue.

- systemd250, kernel 5.14 
- nics are NetXtreme BCM5720 Gigabit Ethernet PCIe, module tg3 

With same hardware and RL8 have no issue.

- systemd239, kernel 4.18

**Comment by ipaqmaster** [comment]
> I just install a RL9 and have the same the same issue.
> 
>     * systemd250, kernel 5.14
> 
>     * nics are NetXtreme BCM5720 Gigabit Ethernet PCIe, module tg3
> 
> 
> With same hardware and RL8 have no issue.
> 
>     * systemd239, kernel 4.18

> I just install a RL9 and have the same the same issue.
> 
>     * systemd250, kernel 5.14
> 
>     * nics are NetXtreme BCM5720 Gigabit Ethernet PCIe, module tg3
> 
> 
> With same hardware and RL8 have no issue.
> 
>     * systemd239, kernel 4.18

Have you tried the `/etc/systemd/network/98-bond-mac.link` trick? With content:

```
[Match]
Type=bond

[Link]
MACAddressPolicy=none
```

**Comment by vot4anto** [comment]
This trick works perfect and after use It I have no errors in messagge.

Antonio

Il gio 23 feb 2023, 23:12 Jared J ***@***.***> ha scritto:

**Comment by ipaqmaster** [comment]
Glad to hear it. The same fix has been part of my saltstack states for just over a year now. Not sure why this behavior has not yet been corrected.

**Comment by thom311** [comment]
> I just install a RL9 and have the same the same issue.
> ...
> With same hardware and RL8 have no issue.

I assume RL means RHEL? RHEL9 and RHEL8 carry [a downstream patch](https://gitlab.com/redhat/centos-stream/rpms/systemd/-/blob/d005486d571afd51e8f5ce3a00dbf04ab14670f5/0110-udev-net-setup-link-change-the-default-MACAddressPol.patch) which sets `MACAddressPolicy=none`. It's not clear to me, what "same issue" you have.

Btw, in the meantime, Fedora 38+ ships a (downstream only) file `/usr/lib/systemd/network/98-default-mac-none.link` which sets policy `none` for bridge,bond,team devices. See [here](https://fedoraproject.org/wiki/Changes/MAC_Address_Policy_none#Current_status).

**Comment by vot4anto** [comment]
I'm sorry, RL for me is Rocky Linux and not RHEL
