### ISSUE TITLE
"Unexpected error response from GetNameOwner(): Connection terminated" messages + boot takes a lot of time

### ISSUE THREAD

**Issue by tomgar** [systemd/systemd#15316]
**systemd version the issue has been seen with**
245.4

**Used distribution**
Archlinux

**Expected behaviour you didn't see**
* Not taking more than 5 seconds to get to the graphical target at boot
* No error messages
* Expected systemd-analyze output:
```
% systemd-analyze
Startup finished in 6.791s (firmware) + 3.762s (loader) + 1.088s (kernel) + 25.338s (initrd) + 5.208s (userspace) = 42.189s 
graphical.target reached after 4.606s in userspace

% systemd-analyze critical-chain 
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

graphical.target @4.606s
└─lightdm.service @3.476s +1.129s
  └─systemd-user-sessions.service @3.469s +6ms
    └─nss-user-lookup.target @4.332s

```

**Unexpected behaviour you saw**
 * Odd errors in the journal. Here's the relevant log lines:
```
Apr 02 20:47:23 nix lightdm[1054]: Error getting user list from org.freedesktop.Accounts: Timeout was reached
Apr 02 20:47:23 nix accounts-daemon[1176]: error getting polkit authority: Error initializing authority: Error calling StartServiceByName for org.freedesktop.PolicyKit1: Timeout was reached
Apr 02 20:47:23 nix dbus-daemon[989]: [system] Failed to activate service 'org.freedesktop.Accounts': timed out (service_start_timeout=25000ms)
Apr 02 20:47:23 nix dbus-daemon[989]: [system] Failed to activate service 'org.freedesktop.PolicyKit1': timed out (service_start_timeout=25000ms)
Apr 02 20:47:23 nix systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 02 20:47:23 nix systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 02 20:47:23 nix systemd[1]: systemd-homed.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 02 20:47:23 nix systemd[1]: bluetooth.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 02 20:47:23 nix systemd[1]: lightdm.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 02 20:47:23 nix systemd[1]: systemd-hostnamed.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 02 20:47:23 nix systemd[1]: wpa_supplicant.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 02 20:47:23 nix systemd[1]: NetworkManager-dispatcher.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 02 20:47:23 nix systemd[1]: polkit.service: Unexpected error response from GetNameOwner(): Connection terminated
Apr 02 20:47:24 nix systemd-logind[1745]: User or group name "1000" starts with a digit, accepting for compatibility.
Apr 02 20:47:24 nix systemd-logind[1745]: Failed to add user by file name 1000, ignoring: Invalid argument
Apr 02 20:47:24 nix systemd-logind[1745]: User enumeration failed: Invalid argument

```
* NetworkManager was sigterm by systemd and didn't recover gracefully after that.

* systemd-analyze output:
```
% systemd-analyze 
Startup finished in 6.750s (firmware) + 3.459s (loader) + 1.102s (kernel) + 16.838s (initrd) + 31.023s (userspace) = 59.174s 
graphical.target reached after 30.012s in userspace

% systemd-analyze critical-chain 
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

graphical.target @30.012s
└─lightdm.service @3.747s +26.264s
  └─systemd-user-sessions.service @3.739s +7ms
    └─nss-user-lookup.target @4.676s
```

**Steps to reproduce the problem**
Nothing relevant to trigger the problem. It happens randomly although frequently with 245.

I found that removing the "systemd" value from the passwd / group lines in /etc/nsswitch.conf prevents this issue from happening at all.

**Comment by poettering** [comment]
looks like a deadlock between dbus and systemd in some way...

could you get a backtrace of dbus-daemon when this happens? (or are you using dbus-broker?)

**Comment by tomgar** [comment]
Thanks for answering.

I added systemd back to those lines in /etc/nsswitch.conf and now I couldn't trigger the issue. It's because now Archlinux distributes systemd with the patch for having systemd-homed, systemd-repart, systemd-userdbd, etc. in installable form.

I enabled systemd-userdbd and I couldn't trigger the issue. I enabled systemd-homed and now the issue is triggered. I installed dbus-broker thinking that will make things easier regarding having a backtrace, but with dbus-broker I cannot trigger the issue... I disabled dbus-broker and the issue came back, so definitely it's a bad interaction between systemd-homed and the regular dbus implementation.

I'll try to come back as soon as possible with a backtrace of dbus-daemon (strace I guess).

**Comment by tomgar** [comment]
I did systemctl edit dbus.service and put in there:
[Service]
ExecStart=
ExecStart=/usr/bin/strace -o /root/dbus_strace.log /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only

Got this:
[dbus_strace.log](https://github.com/systemd/systemd/files/4462074/dbus_strace.log)

But the system didn't boot. It seems that dbus never loaded:
```
Apr 10 15:47:55 nix systemd[1]: Started D-Bus System Message Bus.
Apr 10 15:47:55 nix dbus-daemon[1009]: Failed to start message bus: No socket received.
Apr 10 15:47:55 nix systemd[1]: dbus.service: Main process exited, code=exited, status=1/FAILURE
Apr 10 15:47:55 nix systemd[1]: dbus.service: Failed with result 'exit-code'.
Apr 10 15:47:55 nix systemd[1]: Started D-Bus System Message Bus.
Apr 10 15:47:56 nix dbus-daemon[1052]: Failed to start message bus: No socket received.
Apr 10 15:47:56 nix systemd[1]: dbus.service: Main process exited, code=exited, status=1/FAILURE
Apr 10 15:47:56 nix systemd[1]: dbus.service: Failed with result 'exit-code'.
Apr 10 15:47:56 nix systemd[1]: Started D-Bus System Message Bus.
Apr 10 15:47:56 nix dbus-daemon[1056]: Failed to start message bus: No socket received.
Apr 10 15:47:56 nix systemd[1]: dbus.service: Main process exited, code=exited, status=1/FAILURE
Apr 10 15:47:56 nix systemd[1]: dbus.service: Failed with result 'exit-code'.
Apr 10 15:47:56 nix systemd[1]: Started D-Bus System Message Bus.
Apr 10 15:47:56 nix dbus-daemon[1060]: Failed to start message bus: No socket received.
Apr 10 15:47:56 nix systemd[1]: dbus.service: Main process exited, code=exited, status=1/FAILURE
Apr 10 15:47:56 nix systemd[1]: dbus.service: Failed with result 'exit-code'.
Apr 10 15:47:56 nix systemd[1]: Started D-Bus System Message Bus.
Apr 10 15:47:56 nix dbus-daemon[1064]: Failed to start message bus: No socket received.
Apr 10 15:47:56 nix systemd[1]: dbus.service: Main process exited, code=exited, status=1/FAILURE
Apr 10 15:47:56 nix systemd[1]: dbus.service: Failed with result 'exit-code'.
Apr 10 15:47:56 nix systemd[1]: dbus.service: Start request repeated too quickly.
Apr 10 15:47:56 nix systemd[1]: dbus.service: Failed with result 'exit-code'.
Apr 10 15:47:56 nix systemd[1]: Failed to start D-Bus System Message Bus.
``` 
, so I'm not sure if this trace is useful for the issue at hand. Anyway, please, point me out how to get that backtrace better.

Thanks.

**Comment by mammo0** [comment]
Hello,

can also confirm after enabling `systemd-userdbd.socket` (and reboot) the described error was resolved.

Don't really know why this is happening...
I've got two desktop computers running Arch Linux. Both have the latest systemd version (245.5-1). But only one pc produces the above problem, the other doesn't. So as a workaround I enabled the userdbd socket.

**Comment by poettering** [comment]
use strace's `-D` switch, so that fd passing can work.

**Comment by tomgar** [comment]
Thanks. Now it worked. Although it made it harder actually to trigger the issue. 

I had to install systemd-homed and systemd-userdbd to trigger it with the strace command.

Here's the trace:
[dbus_strace_2.log](https://github.com/systemd/systemd/files/4524866/dbus_strace_2.log)

**Comment by AstroProfundis** [comment]
Can confirm with `245.6-4-arch`, and enabling `systemd-userdbd.socket` does not help on my system.

```
$ sudo systemd-analyze critical-chain
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

graphical.target @49.614s
└─multi-user.target @49.612s
  └─systemd-logind.service @49.778s +472ms
    └─basic.target @1.984s
      └─sockets.target @1.984s
        └─docker.socket @1.983s +700us
          └─sysinit.target @1.981s
            └─systemd-userdbd.service @3.889s +338ms
              └─systemd-userdbd.socket @191ms
                └─-.mount @175ms
                  └─system.slice @175ms
                    └─-.slice @175ms
```

**Comment by nicofossa** [comment]
I have the very same problem. Unfortunately, upgrading to `systemd 245 (245.6-6-arch)` does not fix the issue.
Distribution: ArchLinux
Kernel version: Linux 5.7.2-arch1-1
Dbus version: dbus 1.12.18-1

**Comment by alienscience** [comment]
I had the same problem:
* Slow boot
* Network Manager Service not running after login

As a temporary workaround I commented out two lines in `/etc/nswitch.conf`:
```diff
@@ -1,9 +1,12 @@
 # Name Service Switch configuration file.
 # See nsswitch.conf(5) for details.
 
-passwd: files mymachines systemd
-group: files mymachines systemd
+# Commented out because of boot problems and NetworkManager failure
+#passwd: files mymachines systemd
+#group: files mymachines systemd
 
+passwd: files mymachines
+group: files mymachines
 shadow: files
 
 publickey: files
```

I hope this workaround is useful to other people.

**Comment by huntekah** [comment]
Same problem here.  NetworkManager won't load on boot, fans started going like crazy, error like this shown.

Can confirm this solution works on ThinkPad X1C6 arch Linux

> I had the same problem:
> 
> * Slow boot
> * Network Manager Service not running after login
> 
> As a temporary workaround I commented out two lines in `/etc/nswitch.conf`:
> 
> ```diff
> @@ -1,9 +1,12 @@
>  # Name Service Switch configuration file.
>  # See nsswitch.conf(5) for details.
>  
> -passwd: files mymachines systemd
> -group: files mymachines systemd
> +# Commented out because of boot problems and NetworkManager failure
> +#passwd: files mymachines systemd
> +#group: files mymachines systemd
>  
> +passwd: files mymachines
> +group: files mymachines
>  shadow: files
>  
>  publickey: files
> ```
> 
> I hope this workaround is useful to other people.

P.S.
I think you meant /etc/ns**s**witch.conf

**Comment by nicofossa** [comment]
> I had the same problem:
> 
>     * Slow boot
> 
>     * Network Manager Service not running after login
> 
> 
> As a temporary workaround I commented out two lines in `/etc/nswitch.conf` _CORRECTION nsswitch.conf_:
> 
> ```diff
> @@ -1,9 +1,12 @@
>  # Name Service Switch configuration file.
>  # See nsswitch.conf(5) for details.
>  
> -passwd: files mymachines systemd
> -group: files mymachines systemd
> +# Commented out because of boot problems and NetworkManager failure
> +#passwd: files mymachines systemd
> +#group: files mymachines systemd
>  
> +passwd: files mymachines
> +group: files mymachines
>  shadow: files
>  
>  publickey: files
> ```
> 
> I hope this workaround is useful to other people.

Thank you, the proposed solution works and prevents NetworkManager, SDDM and other services to hang or crash at boot, without causing any side effect at the moment.

**Comment by Termuellinator** [comment]
I'm also using this workaround - unfortunately, that breaks Polkit-Support for Kate :/

**Comment by oold** [comment]
This also happens whenever a USB mass storage device is attached to one of my USB ports.

systemd version: 245.4
Distribution: Pop!_OS 20.04 LTS
[Output of `journalctl -b`.](https://github.com/systemd/systemd/files/4975781/journal.log)
```
$ systemd-analyze 
Startup finished in 8.136s (firmware) + 956ms (loader) + 25.459s (kernel) + 1min 14.585s (userspace) = 1min 49.137s 
graphical.target reached after 1min 14.572s in userspace
```
```
$ systemd-analyze critical-chain 
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

graphical.target @1min 14.572s
└─multi-user.target @1min 14.572s
  └─ModemManager.service @1min 13.474s +38ms
    └─polkit.service @48.711s +6ms
      └─basic.target @1.548s
        └─sockets.target @1.548s
          └─uuidd.socket @1.548s
            └─sysinit.target @1.543s
              └─systemd-timesyncd.service @1.112s +428ms
                └─systemd-tmpfiles-setup.service @1.094s +14ms
                  └─local-fs.target @1.089s
                    └─run-user-1000-doc.mount @59.473s
                      └─run-user-1000.mount @3.077s
                        └─local-fs-pre.target @363ms
                          └─lvm2-monitor.service @238ms +124ms
                            └─systemd-journald.socket @233ms
                              └─system.slice @230ms
                                └─-.slice @230ms
```

**Comment by oold** [comment]
This Ubuntu bug might be related: https://bugs.launchpad.net/ubuntu/+source/accountsservice/+bug/1871538.

**Comment by poettering** [comment]
@tomgar hmm, that strace shows nothing interesting, i.e. it seems dbus-daemon just work. Maybe add "-s 500 -t" or so to make the output more useful, and see where things are slow...

also, any chance to get backtraces when this freezes? i.e. gdb attach to dbus-daemon (and to PID 1) and do "bt full".

Is it just dbus-daemon that hangs? What happens when you issue "systemctl status dbus-daemon" when this freezes?

**Comment by markusressel** [comment]
Not sure if it is related, but I got this error, after I set up a wireguard configuration on my system. It could be a coincidence, but I thought I'd mention it.

**Comment by oold** [comment]
And for me, the error stopped occurring once I had disabled auto-login for GNOME. Weird.

**Comment by tomgar** [comment]
@poettering To avoid the issue I was using dbus-broker. I disabled it, now using regular dbus, enabled systemd-homed & systemd-userdbd, and now surprisingly I cannot reproduce the problem. Possibly a component update fix it, whether it was regular dbus or a systemd update I'm not sure.

So I'm going to keep this configuration for a while to see if the issue is now gone.

To the rest, please, don't take whatever is said in an issue as a definitive "fix". Those of you that did the nsswitch.conf change, please, revert it since it's easy to forget about it, and then in the future that will be a source of problems and you'll be quite confused about what's going on when the time comes.

Update your systems and if the issue is still going-on the current workaround is using dbus-broker and please, help @poettering give the feedback he needs since I cannot give it for now. 

If in a couple of weeks I don't manage to reproduce the issue or noone else gives that feedback, I'll close this issue. Thanks.

**Comment by Termuellinator** [comment]
for me, dbus-broker no longer works for a workaround - i still have to use the nsswitch.conf workaround :/

**Comment by Faerbit** [comment]
I'm not sure if my problem is related to this, but my symptoms look similar, so here goes nothing:
I use Arch btw and my dbus log showed the following line:
```
Aug 02 12:21:46 ryzen dbus-daemon[597]: [system] Connection has not authenticated soon enough, closing it (auth_timeout=30000ms, elapsed: 45105ms)
```
The root cause of the problem on my machine was actually CUPS misbehaving, which lead to the mentioned timeout. I think this cascaded through the whole boot process and caused the problem discussed here.
I resolved the issue by switching the CUPS service to socket activation (before the service was started on boot directly).
To summarize my troubleshooting steps:
 * Look for the log entry in dbus log (`journalctl -b -u dbus`)
 * Switch CUPS to socket activation, since it was the first activator of dbus:
   * `systemctl disable org.cups.cupsd.service`
   * `systemctl enable org.cups.cupsd.socket`
* Reboot

**Comment by tomgar** [comment]
@poettering I stand corrected. Today it happened again. The trigger I think it was the xfs_scrub_all timer which started the xfs_scrub_all process at boot since it's configured to happen at 3:00 AM on Sundays and my PC was already turned off at that hour. 

I only captured the output of systemd-analyze blame. Here's the head of it:

```
1min 52.678s xfs_scrub_all.service                                                                    
     43.933s xfs_scrub@-home.service                                                                  
     26.184s lightdm.service                                                                          
     25.530s tlp.service                                                                              
     25.481s user@1000.service                                                                        
      2.476s initrd-switch-root.service                                                               
      1.297s lvm2-monitor.service
```

I'll leave the strace on, for now on. Although I configured xfs_scrub_all to run it at every boot, trying to make this error deterministic, it only happened once more but after that, everything's working ok for now.

About getting that backtrace, how I can run those lines at the moment of the freeze which happens in the middle of the startup? I only can run those things after the system finally finished booting the graphical target. If it's ok doing it at that moment, I'll do it.

**Comment by Termuellinator** [comment]
@Faerbit You Sir, are a genius!
I can confirm that disabling cupsd.service is a much better workaround than the nsswitch.conf thing :+1:

**Comment by tomgar** [comment]
About that cupsd.service, that's not my case unfortunately:
```
# systemctl status org.cups.cupsd.service
● org.cups.cupsd.service - CUPS Scheduler
     Loaded: loaded (/usr/lib/systemd/system/org.cups.cupsd.service; disabled; vendor preset: disabled)
     Active: inactive (dead)
       Docs: man:cupsd(8)
```

Today, the issue happened again, here's the output of systemctl status dbus:

```
# systemctl status dbus.service
● dbus.service - D-Bus System Message Bus
     Loaded: loaded (/usr/lib/systemd/system/dbus.service; static; vendor preset: disabled)
    Drop-In: /etc/systemd/system/dbus.service.d
             └─override.conf
     Active: active (running) since Mon 2020-08-03 16:06:30 WEST; 7min ago
TriggeredBy: ● dbus.socket
       Docs: man:dbus-daemon(1)
   Main PID: 1307 (dbus-daemon)
      Tasks: 2 (limit: 18976)
     Memory: 9.3M
     CGroup: /system.slice/dbus.service
             ├─1307 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
             └─1323 /usr/bin/strace -D -s 500 -t -o /root/dbus_strace.log /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only

Aug 03 16:07:10 nix dbus-daemon[1307]: [system] Activating via systemd: service name='org.freedesktop.UDisks2' unit='udisks2.service' requested by ':1.38' (uid=1000 pid=2177 comm="/usr/lib/gvfs-udisks2-volume-monitor ")
Aug 03 16:07:10 nix dbus-daemon[1307]: [system] Activating via systemd: service name='org.freedesktop.UPower' unit='upower.service' requested by ':1.42' (uid=1000 pid=2174 comm="/usr/lib/xfce4/panel/wrapper-2.0 /usr/lib/xfce4/pa")
Aug 03 16:07:10 nix dbus-daemon[1307]: [system] Successfully activated service 'org.freedesktop.UDisks2'
Aug 03 16:07:11 nix dbus-daemon[1307]: [system] Activating via systemd: service name='org.blueman.Mechanism' unit='blueman-mechanism.service' requested by ':1.44' (uid=1000 pid=2160 comm="/usr/bin/python /usr/bin/blueman-applet ")
Aug 03 16:07:11 nix dbus-daemon[1307]: [system] Successfully activated service 'org.blueman.Mechanism'
Aug 03 16:07:11 nix dbus-daemon[1307]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service' requested by ':1.44' (uid=1000 pid=2160 comm="/usr/bin/python /usr/bin/blueman-applet ")
Aug 03 16:07:11 nix dbus-daemon[1307]: [system] Successfully activated service 'org.bluez'
Aug 03 16:07:11 nix dbus-daemon[1307]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.48' (uid=0 pid=2347 comm="/usr/lib/bluetooth/bluetoothd ")
Aug 03 16:07:11 nix dbus-daemon[1307]: [system] Successfully activated service 'org.freedesktop.UPower'
Aug 03 16:07:11 nix dbus-daemon[1307]: [system] Successfully activated service 'org.freedesktop.hostname1'
```

```
# systemctl status NetworkManager        
● NetworkManager.service - Network Manager
     Loaded: loaded (/usr/lib/systemd/system/NetworkManager.service; enabled; vendor preset: disabled)
    Drop-In: /usr/lib/systemd/system/NetworkManager.service.d
             └─NetworkManager-ovs.conf
     Active: inactive (dead) since Mon 2020-08-03 16:06:57 WEST; 7min ago
       Docs: man:NetworkManager(8)
   Main PID: 1308 (code=exited, status=0/SUCCESS)

Aug 03 16:06:57 nix systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
Aug 03 16:06:57 nix NetworkManager[1308]: <info>  [1596467217.2442] caught SIGTERM, shutting down normally.
Aug 03 16:06:57 nix NetworkManager[1308]: <info>  [1596467217.2838] dhcp4 (enp5s0): canceled DHCP transaction
Aug 03 16:06:57 nix NetworkManager[1308]: <info>  [1596467217.2838] dhcp4 (enp5s0): state changed bound -> done
Aug 03 16:06:57 nix NetworkManager[1308]: <info>  [1596467217.2838] device (enp5s0): DHCPv4: trying to acquire a new lease within 90 seconds
Aug 03 16:06:57 nix NetworkManager[1308]: <info>  [1596467217.2843] manager: NetworkManager state is now CONNECTED_SITE
Aug 03 16:06:57 nix NetworkManager[1308]: <info>  [1596467217.2857] device (p2p-dev-wlp2s0): state change: disconnected -> unmanaged (reason 'removed', sys-iface-state: 'removed')
Aug 03 16:06:57 nix NetworkManager[1308]: <info>  [1596467217.2861] manager: startup complete
Aug 03 16:06:57 nix NetworkManager[1308]: <info>  [1596467217.3548] exiting (success)
```

 I'm not sure what we have in common, since no one else is gathering logs. Please, could someone else who is suffering from this in a more deterministic manner to gather logs and post them here? Thanks.

**Comment by oold** [comment]
Logs with strace from booting my system with GNOME auto-login turned on.
```
● cups.service - CUPS Scheduler
     Loaded: loaded (/lib/systemd/system/cups.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2020-08-03 20:09:44 CEST; 4min 36s ago
TriggeredBy: ● cups.path
             ● cups.socket
       Docs: man:cupsd(8)
   Main PID: 1224 (cupsd)
      Tasks: 1 (limit: 19037)
     Memory: 6.8M
     CGroup: /system.slice/cups.service
             └─1224 /usr/sbin/cupsd -l

Aug 03 20:09:44 pop-os systemd[1]: Started CUPS Scheduler.
```
```
● dbus.service - D-Bus System Message Bus
     Loaded: loaded (/lib/systemd/system/dbus.service; static; vendor preset: enabled)
    Drop-In: /etc/systemd/system/dbus.service.d
             └─override.conf
     Active: active (running) since Mon 2020-08-03 20:09:44 CEST; 5min ago
TriggeredBy: ● dbus.socket
       Docs: man:dbus-daemon(1)
   Main PID: 1225 (dbus-daemon)
      Tasks: 3 (limit: 19037)
     Memory: 33.6M
     CGroup: /system.slice/dbus.service
             ├─1225 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
             ├─1252 /usr/bin/strace -D -s 500 -t -o /root/dbus_strace.log /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
             └─2854 /usr/bin/python3 /usr/lib/pop-transition/service.py

Aug 03 20:10:43 pop-os dbus-daemon[1225]: [system] Successfully activated service 'org.freedesktop.bolt'
Aug 03 20:10:43 pop-os dbus-daemon[1225]: [system] Successfully activated service 'org.freedesktop.fwupd'
Aug 03 20:10:57 pop-os dbus-daemon[1225]: [system] Failed to activate service 'org.freedesktop.RealtimeKit1': timed out (service_start_timeout=25000ms)
Aug 03 20:10:57 pop-os dbus-daemon[1225]: [system] Activating via systemd: service name='org.freedesktop.RealtimeKit1' unit='rtkit-daemon.service' requested by ':1.83' (uid=1000 pid=1749 comm="/usr/bin/pulseaudio --daemonize=no --log-target=jo" label="kernel")
Aug 03 20:10:57 pop-os dbus-daemon[1225]: [system] Successfully activated service 'org.freedesktop.RealtimeKit1'
Aug 03 20:10:57 pop-os dbus-daemon[1225]: [system] Failed to activate service 'org.freedesktop.nm_dispatcher': timed out (service_start_timeout=25000ms)
Aug 03 20:10:57 pop-os dbus-daemon[1225]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service' requested by ':1.85' (uid=1000 pid=1749 comm="/usr/bin/pulseaudio --daemonize=no --log-target=jo" label="kernel")
Aug 03 20:10:58 pop-os dbus-daemon[1225]: [system] Activating service name='org.pop_os.transition_system' requested by ':1.92' (uid=1000 pid=2593 comm="/usr/bin/python3 /usr/bin/pop-transition -d " label="kernel") (using servicehelper)
Aug 03 20:10:58 pop-os dbus-daemon[1225]: [system] Successfully activated service 'org.pop_os.transition_system'
Aug 03 20:11:22 pop-os dbus-daemon[1225]: [system] Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)
```
```
● NetworkManager.service - Network Manager
     Loaded: loaded (/lib/systemd/system/NetworkManager.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Mon 2020-08-03 20:10:32 CEST; 4min 34s ago
       Docs: man:NetworkManager(8)
    Process: 1230 ExecStart=/usr/sbin/NetworkManager --no-daemon (code=exited, status=0/SUCCESS)
   Main PID: 1230 (code=exited, status=0/SUCCESS)

Aug 03 20:10:32 pop-os NetworkManager[1230]: <info>  [1596478232.1210] Config: added 'ssid' value 'Oliver’s iPhone'
Aug 03 20:10:32 pop-os NetworkManager[1230]: <info>  [1596478232.1210] Config: added 'scan_ssid' value '1'
Aug 03 20:10:32 pop-os NetworkManager[1230]: <info>  [1596478232.1210] Config: added 'bgscan' value 'simple:30:-70:86400'
Aug 03 20:10:32 pop-os NetworkManager[1230]: <info>  [1596478232.1210] Config: added 'key_mgmt' value 'WPA-PSK WPA-PSK-SHA256 FT-PSK'
Aug 03 20:10:32 pop-os NetworkManager[1230]: <info>  [1596478232.1210] Config: added 'psk' value '<hidden>'
Aug 03 20:10:32 pop-os systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
Aug 03 20:10:32 pop-os NetworkManager[1230]: <info>  [1596478232.1364] caught SIGTERM, shutting down normally.
Aug 03 20:10:32 pop-os NetworkManager[1230]: <info>  [1596478232.1378] manager: startup complete
Aug 03 20:10:32 pop-os NetworkManager[1230]: <info>  [1596478232.2802] exiting (success)
Aug 03 20:10:32 pop-os systemd[1]: NetworkManager.service: Succeeded.
```
```
● gdm.service - GNOME Display Manager
     Loaded: loaded (/lib/systemd/system/gdm.service; static; vendor preset: enabled)
     Active: active (running) since Mon 2020-08-03 20:10:33 CEST; 10min ago
    Process: 1910 ExecStartPre=/usr/share/gdm/generate-config (code=exited, status=0/SUCCESS)
    Process: 1912 ExecStartPre=/usr/lib/gdm3/gdm-wait-for-drm (code=exited, status=0/SUCCESS)
   Main PID: 1913 (gdm3)
      Tasks: 3 (limit: 19037)
     Memory: 4.7M
     CGroup: /system.slice/gdm.service
             └─1913 /usr/sbin/gdm3

Aug 03 20:10:33 pop-os systemd[1]: Starting GNOME Display Manager...
Aug 03 20:10:33 pop-os systemd[1]: Started GNOME Display Manager.
Aug 03 20:10:36 pop-os gdm3[1913]: GdmLocalDisplayFactory: Failed to issue method call: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
Aug 03 20:10:37 pop-os gdm-autologin][1993]: gkr-pam: unable to locate daemon control file
Aug 03 20:10:37 pop-os gdm-autologin][1993]: gkr-pam: stashed password to try later in open session
Aug 03 20:10:37 pop-os gdm-autologin][1993]: pam_unix(gdm-autologin:session): session opened for user oliver by (uid=0)
Aug 03 20:10:37 pop-os gdm-autologin][1993]: gkr-pam: unlocked login keyring
```
[dbus_strace.log](https://mega.nz/file/xFUwDSCB#5EVa1jTpZytibM1RcUsBrjt5tAWkd_u9AURu5-bE6mM)

**Comment by Termuellinator** [comment]
Interesting - i re-enabled cupsd.service to grab the logs and now the issue is gone?
Only other thing i tried (unfortunately) simultaneously was to disable auto-login in SDDM. I then re-enabled it (same user and session) it to check if it was this or cupsd.service. and thus concluded it had to be cups.
I'll keep an eye on it an report back if the issue comes back. But for now it seems to be a somehow corrupted auto-login-config or something like that? Do others experiencing this also have auto-login enabled?

**Comment by tycho** [comment]
I've experienced it and not had auto-login enabled -- I think auto-login thing (as well as cups) are not the issue. In my case, `sddm.service` is enabled, but it was showing up in the journal long before sddm actually started. I think the problem is so sporadic that it's difficult to find any kind of repro case, and when people try things and think they've "fixed" it, they just got lucky for a while.

**Comment by chandradeepdey** [comment]
Disabling `systemd-resolved` was a workaround for me.

**Comment by Faerbit** [comment]
After a kernel updates it seems that @tycho is correct. Disabling `cupsd` didn't have anything to do with it. The issue is happening to me again.
Therefore I produced an strace log with `/usr/bin/strace -s 500 -tt -D -A -o /root/dbus_strace.log /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only` (`dbus_strace.log`) I also attached the log output (`dbus_journald.log`).
I am not aware of how I could attach a debugger, since this happens during boot time. Is there any other way, I could provide information to resolve this issue, @poettering ?
[dbus_journald.log](https://github.com/systemd/systemd/files/5078551/dbus_journald.log)
[dbus_strace.log](https://github.com/systemd/systemd/files/5078552/dbus_strace.log)

**Comment by pteromys** [comment]
I appear to have symptoms deterministically.

@alienscience's workaround at https://github.com/systemd/systemd/issues/15316#issuecomment-643599192 worked for me, and when I backed it out I was able to collect some logs.

For me, it's lightdm that appears to pause:

```sh
$ systemd-analyze critical-chain
graphical.target @4.416s
└─lightdm.service @51.471s +633ms
  └─systemd-user-sessions.service @3.230s +23ms
    └─nss-user-lookup.target @4.419s
```

@Faerbit, I set up a temporary service to wait for lightdm to start and capture backtraces; crappy scripts attached in case you wish to try adapting them:

[gdb-lightdm.service.txt](https://github.com/systemd/systemd/files/5093585/gdb-lightdm.service.txt)
[gdb-lightdm.sh.txt](https://github.com/systemd/systemd/files/5093580/gdb-lightdm.sh.txt)
[gdb-script.txt](https://github.com/systemd/systemd/files/5093581/gdb-script.txt)

The logs during the pause reference something related to dbus:

```
Aug 18 20:38:08.087642 delia systemd[737]: Startup finished in 207ms.
Aug 18 20:38:08.100818 delia systemd[1]: getty.target: Wants dependency dropin /etc/systemd/system/getty.target.wants/getty@tty1.service is not a symlink, ignoring.
Aug 18 20:38:10.901681 delia acpid[486]: client 613[0:0] has disconnected
Aug 18 20:38:14.837825 delia acpid[486]: client connected from 613[0:0]
Aug 18 20:38:14.837825 delia acpid[486]: 1 client rule loaded
Aug 18 20:38:37.056341 delia acpid[486]: client 613[0:0] has disconnected
Aug 18 20:38:53.140768 delia dbus-daemon[490]: [system] Connection has not authenticated soon enough, closing it (auth_timeout=30000ms, elapsed: 45079ms)
```

...after which startup resumes, or at least X starts.

[journal.log (complete, 209K)](https://github.com/systemd/systemd/files/5093559/journal.log)

Backtraces of systemd (1) and lightdm (525) are attached. Unclear how useful they are since I didn't make a debug build. Eyeballing it without any relevant knowledge, I'm guessing PID 1 isn't directly involved but lightdm is waiting on a dbus response.

[1.bt.log](https://github.com/systemd/systemd/files/5093603/1.bt.log)
[525.bt.log](https://github.com/systemd/systemd/files/5093604/525.bt.log)

Let me know if you want me to collect more info!

**Comment by ysolis** [comment]
I have Archlinux installed in two laptops, with `gdm` and `Gnome Shell`, and in both ones the problems appeared some weeks ago (July)

in both ones disabling  all the related systemd `NetworkManager` services (`NetworkManager`, `NetworkManager-wait-online` and `NetworkManager-dispatcher`) the problem sometimes is avoided.

delete `systemd` from `user` and `group` in `/etc/nsswitch.conf` helped me, right, but i don't like the idea to do a change in this important file.

so, i re-enabled `NetworkManager` services, restored `/etc/nsswitch.conf`, installed dbus-broker in both laptops and enabled this at system and user level:

```
sudo pacman -S dbus-broker
sudo systemctl enable dbus-broker.service
sudo systemctl --global status dbus-broker.service
```

afhter this change, rebooted and the problem dissapears in both ones. I think that is some problem between `systemd` and `dbus` at boot/launch level too.

**Comment by hexiaowen** [comment]
I had the same problem when I was using ISO to install the system on a physical machine.
It is found that the hostnamectl and systemctl restart systemd-hostnamed commands are suspended and the same error is reported.
`Unexpected error response from GetNameOwner(): timed out`

**Comment by Geass-LL** [comment]
Any updates?
I had the same problem when updating packages by rpm. This problem may be related to daemon-reload.

**Comment by showgood163** [comment]
> I have Archlinux installed in two laptops, with `gdm` and `Gnome Shell`, and in both ones the problems appeared some weeks ago (July)
> 
> in both ones disabling all the related systemd `NetworkManager` services (`NetworkManager`, `NetworkManager-wait-online` and `NetworkManager-dispatcher`) the problem sometimes is avoided.
> 
> delete `systemd` from `user` and `group` in `/etc/nsswitch.conf` helped me, right, but i don't like the idea to do a change in this important file.
> 
> so, i re-enabled `NetworkManager` services, restored `/etc/nsswitch.conf`, installed dbus-broker in both laptops and enabled this at system and user level:
> 
> ```
> sudo pacman -S dbus-broker
> sudo systemctl enable dbus-broker.service
> sudo systemctl --global enable dbus-broker.service
> ```
> 
> after this change, I rebooted and the problem dissapears in both ones. I think that is some problem between `systemd` and `dbus` at boot/launch level too (and `dbus-broker` is hidding the problem in my case).

Thank you for the solution.

I also have latest arch installed on both my laptop and PC. However, this problem only happens on my PC. Don't know the reason here.

**Comment by petsam** [comment]
I faced this issue since a couple of days ago (Archlinux, KDE, SDDM). Initially I found sddm to delay to show up and after login, no network (NM active-running, NM-wait-online failed). After a lot of research and workarounds attempts, installing and using `dbus-broker` [thanks to this](https://github.com/systemd/systemd/issues/15316#issuecomment-680950770), clears the issue for me.
My question was how and why this happened now, so searching for updates just before it started happening gave me only `nss (3.60.1-1 -> 3.61-1) Last Updated: 2021-01-24 13:55 UTC`, from all possible reasons described above (and also concluded myself).

I hope the real problem is found soon.

**Comment by arun54321** [comment]
I have same network manager issue (arch linux + systemd 247).
1. If I disable systemd-swap.service/zram, system boot fine. ( with default /etc/nsswitch.conf)
2. Also If I edit nsswitch.conf and enable systemd-swap, system boots fine.

**Comment by omeringen** [comment]
I was using a workaround (i have created a systemd timer, to late start for zram). Thanks to @ysolis for [dbus-broker trick](https://github.com/systemd/systemd/issues/15316#issuecomment-680950770). Works fine now !

**Comment by fdev31** [comment]
Same issue here, happening consistently on each boot, no cups installed... dbus-broker trick also fixed it for me (archlinux).

**Comment by slyon** [comment]
We got some more activity around this issue in https://bugs.launchpad.net/ubuntu/+source/dbus/+bug/1871538 where the problem happens (sometimes) when booting Azure cloud images. Apparently it can be fixed by using `dbus-broker`.

Do you have any idea what might trigger this crash in `dbus-daemon`?

**Comment by slyon** [comment]
Hey! We now have a way to reproduce this issue consistently, by spawning ~50 instances on the Azure cloud, at least one of those will hit this issue. So we collected some journal and strace logs.

The logs have been collected on a Ubuntu Focal machine (using systemd 245.4-4ubuntu3.7 & dbus 0.105-30ubuntu0.1 & policykit 0.105-26ubuntu1.1), but the same issue happens on Ubuntu Hirsute (using systemd 247.3-3ubuntu3.1 & dbus 1.12.20-1ubuntu3 & policykit 0.105-30ubuntu0.1). We collected a "good" log, where everything works as expected and a "bad" log where issue happens, those were executed in parallel on separate Azure cloud instances.

We observed that `polkit.service` is always affected, also in the log posted by the other reporters above, so we gave some special attention to this service. But we were not able to find anything useful in the logs so far, except for a strange ~45 sec "break" in dbus_strace.log, which is approximately the same time when the problem happens (i.e. systemd killing polkit.service):
```
08:50:48.785370 epoll_wait(22, [{EPOLLIN, {u32=3828447984, u64=94866771114736}}], 4, -1) = 1
08:51:33.854264 read(23, "\1\0\0\0\0\0\0\0", 8) = 8
```
```
Jul 01 08:51:34.001829 systemd[1]: Unable to add match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.PolicyKit1', failing connection: Connection terminated
Jul 01 08:51:34.001843 systemd[1]: polkit.service: Unexpected error response from GetNameOwner(): Connection terminated
Jul 01 08:51:34.001846 systemd[1]: polkit.service: D-Bus name org.freedesktop.PolicyKit1 now not owned by anyone.
Jul 01 08:51:34.001891 systemd[1]: polkit.service: Changed running -> stop-sigterm
Jul 01 08:51:34.001897 systemd[1]: polkit.service: Failed to send unit change signal for polkit.service: Transport endpoint is not connected
Jul 01 08:51:34.001931 systemd[1]: Bus bus-api-system: changing state CLOSING → CLOSED
```

On the failed/bad system, the polkit.service is not started after boot (see bad-analyze.log), while on the good system it is started (good-analyze.log).

@poettering Could you please have another look at this?
CC @smcv @gjolly

[bad-analyze.log](https://github.com/systemd/systemd/files/6748599/bad-analyze.log)
[bad-dbus_strace.log](https://github.com/systemd/systemd/files/6748600/bad-dbus_strace.log)
[bad-journal.log](https://github.com/systemd/systemd/files/6748624/bad-journal.log)
[bad-polkit_strace.log](https://github.com/systemd/systemd/files/6748609/bad-polkit_strace.log)

[good-analyze.log](https://github.com/systemd/systemd/files/6748601/good-analyze.log)
[good-dbus_strace.log](https://github.com/systemd/systemd/files/6748602/good-dbus_strace.log)
[good-journal.log](https://github.com/systemd/systemd/files/6748603/good-journal.log)
[good-polkit_strace.log](https://github.com/systemd/systemd/files/6748604/good-polkit_strace.log)

**Comment by slyon** [comment]
We might have found another workaround by adding `/etc/systemd/system/polkit.service.d/override.conf`:
```
[Service]
Restart=always
```

Maybe some of the other reporters can confirm if that mitigates the issue for them as well?

**Comment by cpaelzer** [comment]
I've hit this again while unattended-upgrades were running, did anyone have a chance to look at these logs yet?

**Comment by nowrep** [comment]
It's a deadlock between nss-systemd and dbus (the dbus call will timeout).
This should work:
```ini
#/etc/systemd/system/dbus.service.d/override.conf
[Service]
Environment=SYSTEMD_NSS_DYNAMIC_BYPASS=1
```

The fix from fd63e712b2025d235ce4bfbb512fada10e2690b5 wasn't updated when dynamic user lookup switched away from d-bus.

```diff
diff --git a/src/core/execute.c b/src/core/execute.c
index e3b9134..f750c33 100644
--- a/src/core/execute.c
+++ b/src/core/execute.c
@@ -1879,7 +1879,7 @@ static int build_environment(
          * users via PID 1, possibly dead-locking the dbus daemon. This way it will not use D-Bus to resolve names, but
          * check the database directly. */
         if (p->flags & EXEC_NSS_BYPASS_BUS) {
-                x = strdup("SYSTEMD_NSS_BYPASS_BUS=1");
+                x = strdup("SYSTEMD_NSS_DYNAMIC_BYPASS=1");
                 if (!x)
                         return -ENOMEM;
                 our_env[n_env++] = x;
```

**Comment by slyon** [comment]
Thanks a lot @nowrep this is looking very promising!
We're running more tests as we speak, but so far everything is green with this change applied.

@poettering you implemented the original fix in https://github.com/systemd/systemd/commit/fd63e712b2025d235ce4bfbb512fada10e2690b5 – can you confirm it is not yet correctly adopted to the new dynamic user lookup method?

**Comment by Zorono** [comment]
this is a very annoying and time wasting problem 😭
i am running Ubhntu 22.04(amd64)  and the problem persistent

**Comment by mailinglists35** [comment]
I have experienced this on a not-up-to-date system where I installed `systemd-journal-remote` and that has pulled updated versions of various systemd packages[1], while not rebooting the machine.

this has triggered some ten days later, not immediately, when I ran some `machinectl shell user@` commands to manage a podman rootless container. soon, I would get this behaviour: login at console fails with "timed out after 60 seconds", `sudo` commands hang for more than a minute, journald logs say:

````
Nov 27 09:08:18 sudo[3397251]: pam_systemd(sudo:session): Failed to create session: Transport endpoint is not connected
Nov 27 09:08:18 sudo[3397251]: pam_unix(sudo:session): session opened for user root(uid=0) by admin(uid=1024)
Nov 27 09:08:18 sudo[3397251]: pam_unix(sudo:session): session closed for user root
Nov 27 09:08:18 systemd[1]: firewalld.service: Unexpected error response from GetNameOwner(): Connection terminated
Nov 27 09:08:18 systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
Nov 27 09:08:18 systemd[1]: polkit.service: Unexpected error response from GetNameOwner(): Connection terminated
Nov 27 09:08:18 systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
Nov 27 09:08:18 systemd[1]: systemd-machined.service: Unexpected error response from GetNameOwner(): Connection terminated
Nov 27 09:08:18 systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
````

and

````
Nov 27 09:15:23 systemd[1]: getty@tty1.service: Deactivated successfully.
Nov 27 09:15:23 systemd[1]: getty@tty1.service: Scheduled restart job, restart counter is at 6.
Nov 27 09:15:23 systemd[1]: Stopped Getty on tty1.
Nov 27 09:15:23 systemd[1]: Started Getty on tty1.
Nov 27 09:15:49 systemd[1]: systemd-logind.service: start operation timed out. Terminating.
Nov 27 09:15:49 systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
Nov 27 09:15:49 systemd[1]: polkit.service: Unexpected error response from GetNameOwner(): Connection terminated
Nov 27 09:15:49 systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
Nov 27 09:15:49 systemd[1]: udisks2.service: Unexpected error response from GetNameOwner(): Connection terminated
Nov 27 09:15:49 systemd[1]: firewalld.service: Unexpected error response from GetNameOwner(): Connection terminated
````

**what I did to remediate without reboot was to restart every service listed by the output of `needs-restarting` [2] including `dbus-broker` and `systemd-logind`**

___
[1]

````
# dnf -C history info 33
Transaction ID : 33
Begin time     : Thu 16 Nov 2023 11:39:17 PM EET
Begin rpmdb    : 9c79a44f636e54680f9c4d296f2f56eead7db639c9538c66cec0b07b45ea4f2a
End time       : Thu 16 Nov 2023 11:39:23 PM EET (6 seconds)
End rpmdb      : d93f69cc18fd95214703d46450efef0dc449fee7c5b08397229c2a32cc7d6748
User           : suport <suport>
Return-Code    : Success
Releasever     : 9
Command Line   : install systemd-journal-remote
Comment        :
Packages Altered:
    Install  info-6.7-15.el9.x86_64                       @ol9_baseos_latest
    Install  libmicrohttpd-1:0.9.72-5.el9.x86_64          @ol9_appstream
    Install  systemd-journal-remote-252-18.0.1.el9.x86_64 @ol9_appstream
    Upgrade  systemd-252-18.0.1.el9.x86_64                @ol9_baseos_latest
    Upgraded systemd-252-14.0.1.el9_2.3.x86_64            @@System
    Upgrade  systemd-container-252-18.0.1.el9.x86_64      @ol9_baseos_latest
    Upgraded systemd-container-252-14.0.1.el9_2.3.x86_64  @@System
    Upgrade  systemd-libs-252-18.0.1.el9.x86_64           @ol9_baseos_latest
    Upgraded systemd-libs-252-14.0.1.el9_2.3.x86_64       @@System
    Upgrade  systemd-pam-252-18.0.1.el9.x86_64            @ol9_baseos_latest
    Upgraded systemd-pam-252-14.0.1.el9_2.3.x86_64        @@System
    Upgrade  systemd-rpm-macros-252-18.0.1.el9.noarch     @ol9_baseos_latest
    Upgraded systemd-rpm-macros-252-14.0.1.el9_2.3.noarch @@System
    Upgrade  systemd-udev-252-18.0.1.el9.x86_64           @ol9_baseos_latest
    Upgraded systemd-udev-252-14.0.1.el9_2.3.x86_64       @@System
````

[2]

$ rpm -qf `which needs-restarting `
yum-utils-4.3.0-5.0.2.el9_2.noarch

**Comment by gearoid-moore** [comment]
I'm aware that I'm commenting on this somewhat late - I'm seeing this issue on Ubuntu 22.04.

I have some remote desktops, and this error disables Network Manager, and in turn takes the devices offline. 

Could anyone suggest a patch or a workaround, that doesn't take the devices offline? 

All I can think of for the moment is a scheduled reboot.

**Comment by NeatNerdPrime** [comment]
FWIW i had this issue as well on an dist-upgrade in debian (bullseye => bookworm) in regards to polkit.

what resolved for me was the following:

* systemctl daemon-reload
* systemctl restart dbus.service
*  systemctl restart polkit service

Hope it helps someone
