### ISSUE TITLE
ExecStart= should resolve binary names immediately before execve(), and not ahead of time, i.e. not affect PID1 serialization

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#16076]
**systemd version the issue has been seen with**
> v245

**Used distribution**
 > Arch Linux

**Steps to reproduce the problem**

- Boot with `systemctl` in /usr/local/bin in the initramfs and /usr/bin in the rootfs. 
- `journalctl -p warning` should contain 

> initrd-switch-root.service: Current command vanished from the unit file, execution of the command list won't be resumed.

So I've been investigationg #15699 and I feel like the current behaviour is missing something somewhere. My current understanding of the process is the following:

- switch-root serializes all existing initramfs units in `prepare_reexecute`
- switch-root kills all existing initramfs units in `do_reexecute` (`broadcast_signal`) but doesn't wait for them so it can handle the SIGCHILD signal for them after deserializing.
- switch-root reexecutes systemd
- systemd deserializes the initramfs units and tries to match serialized data with units read from disk in `service_deserialize_exec_command` so it can continue executing units that were already running. One of these units is initrd-switch-root which causes the warning.

However, this mechanism doesn't seem to take into account that systemd is running in a completely different filesystem. It only checks if the command lines of the service are still the same but since we're running in a new filesystem, for all we know the binaries themselves could be completely different.

I haven't got the slightest idea on how to solve this. Maybe we should separate initramfs units and rootfs units more clearly somehow? Is systemd in the rootfs supposed to manage any storage daemons still running in the initramfs? The issue triggers with initrd-switch-root now but I imagine it's going to trigger with every storage daemon started from the initramfs that also has a unit file in the rootfs as well.

**Comment by poettering** [comment]
The implied assumption is that the initrd is sufficiently similar to the host. i.e. it is our intention and assumption that the initrd is just a subset of what is in the host fs with very few additional files (and no modified files). While that IRL is mostly a wish only, for service files it usually applies just fine.

What kind of initrd are you looking at? Is this simply an experiment, or are you building a real life thing where the initrd and the host fs differ greatly. if that's the case then the "systemctl switch-root" logic should probably not be used with serialization (for example, by spcifiying the init path explicitly, so that systemd doesn't try to serialize its state)

**Comment by DaanDeMeyer** [comment]
I made this issue after investigating an issue with the mkinitcpio (Arch initramfs tool) initrd. It turns out mkinitcpio symlink /usr/local/bin to /usr/bin and since binary paths aren't listed out in full anymore in systemd's service files, systemd was finding systemctl in /usr/local/bin in the initrd and /usr/bin in the actual rootfs which resulted in the warning I mentioned.

Having mkinitcpio not symlink /usr/local/bin to /usr/bin would solve the issue as well since then the initramfs will mostly be a subset of the actual rootfs but I was wondering if there wasn't a more general issue to be solved here. You make a good point though, the initrd will almost be the same as the rootfs if mkinitcpio wasn't weird in symlinking /usr/local/bin to /usr/bin and it doesn't seem wrong to assume that it will be similar in most cases.

It does still seem weird to attach processes started in the initrd to services in the actual rootfs. I'm not too familiar with this but isn't it problematic when a service started in the initrd is still managed by systemd when it has switched root to the actual rootfs? I would assume that systemd can't really do any cleanup for that service since all its initialization logic was done in the initrd instead of in the actual rootfs.

**Comment by poettering** [comment]
So, the idea is that all initrd services exist with their unit files in both the initrd and the host and we can then just leave the processes around and the processes thus get "adopted" by the host service definition, which should be OK if its mostly the same. That said, it is typically a bad idea to leave processes running across the boundary. we pretty much do that only for root storage daemons and if anything else does it it's most likely just misuing things.

And of course, people should set RefuseManualStop= and RefuseManualStart= in services passed over, so that people cannot accidentally start/stop/restart such services from the host, and they are only cleaned up during final shutdown or not at all...

Note that systemd "adopts" processes to its units all the time. Scope units for example just exist for that concept, but we do that during any "systemctl daemon-reexec" too where we continue managing processes that an earlier instance of us forked off.

But I think what you are describing is pointing to a bug in our code: if I understood correctly then in both the initrd definition of that service and the host definition of that service ExecStart= was set to a relative path, i.e. just "systemctl"? and in one case that meant it resolved to `/usr/bin/systemctl` and in the other to `/usr/local/bin/systemctl` because of that weird symlink? i mean, that it resolved differently is probably OK in this case, however, when we try to match up the old and the new service then we really should take the data *before* resolving into account, not *after* resolving. 

Or did I misunderstand the situation?

**Comment by DaanDeMeyer** [comment]
When thinking about it, it is pretty logical that root storage daemons would stay running until final shutdown. I guess my questions were mostly theoritical and unlikely to occur in practice.

In regards to the symlinks, It's the opposite. In the initrd, systemd searches for the "systemctl" executable and finds it in /usr/local/bin which is searched before /usr/bin. In the actual rootfs, /usr/local/bin is not a symlink to /usr/bin, so systemd finds "systemctl" in /usr/bin instead of /usr/local/bin. As the paths don't match, it logs a warning that it won't continue executing initrd-switch-root.service. This isn't exactly a massive problem as initrd-switch-root has already exited by then but it does give an unnecessary warning.

The paths don't match because systemd doesn't resolve the /usr/local/bin/systemctl symlink to /usr/bin/systemctl. If it serialized the resolved path, the "systemctl" paths would match before and after switch-root and the warning wouldn't occur. I'm not sure if we want to resolve executable symlinks when serializing though.

The other solution is poking the Arch devs to not symlink /usr/local/bin to /usr/bin in mkinitcpio which might be the preferred solution. I still haven't received a response from them as to why symlinking /usr/local/bin to /usr/bin is necessary.

**Comment by grazzolini** [comment]
Looking at mkinicpio's source code, I see this symlink was added 8 years ago by https://github.com/archlinux/mkinitcpio/commit/5f81d06e8b879e1778649405b314d60234934dfc. It was refactored later, but the main structured remained. I don't know the rationale behind it, perhaps @falconindy know better. But, keep in mind that we also have the PATH being set and /usr/local/bin comes first. I know this is mostly a harmless warning, but I'm not sure removing the symlinks is the way to go. @poettering, if we change our initrd-switch-root.service to call the full path /usr/bin/systemctl, I think this warning will go away, no?

**Comment by mabod** [comment]
> @poettering, if we change our initrd-switch-root.service to call the full path /usr/bin/systemctl, I think this warning will go away, no?

I have been seeing this message as well.
That fullpath to systemctl and subsequent creation of a new initramfs solved it for me. The message is gone.

**Comment by poettering** [comment]
/cc @keszybz 

I knew supporting non-absolute paths in ExecStart= would bite us eventually.

Qute frankly, I'd make all our units use absolute paths again. Still not a fan for search paths for stuff where we know exactly where it is.

**Comment by poettering** [comment]
i.e. I'd revert cdc6804b6046282a42117678751c126a022cd24a

**Comment by sandsmark** [comment]
cdc6804 looks ripe for a lot of unintended side-effects (probably mostly for people doing weird things on their systems, but unintended nonetheless).

I haven't looked into it yet, but should it be safe to just revert it, or is it better to just wait for 247?

**Comment by keszybz** [comment]
Let's not break the common case that works for 99% of people because of one weird setup ;)

I think the error here is to serialize the full path. In general it seems that we resolve the path too eagerly. We might just as well resolve the path just before executing the binary and never store the full path. We resolve the binary also for units which are never executed, and that is wasted work.

**Comment by HanabishiRecca** [comment]
This hit me suddenly after a v246 update. I don't know why but v245 was totally fine.
And providing the full path to `systemctl` as described here https://github.com/systemd/systemd/issues/15699#issuecomment-645843333 doesn't worked for me. But changing HOOKS https://github.com/systemd/systemd/issues/15699#issuecomment-624448522 from `systemd` to `udev` does.

> probably mostly for people doing weird things on their systems, but unintended nonetheless

> Let's not break the common case that works for 99% of people because of one weird setup ;)

Does using `systemd-boot` as a bootloader and having `systemd` in HOOKS is so unintended and uncommon setup? Does just using of all this convinient systemd features is bad? If so, somewhere is one Poettering crying 🥲

**Comment by grazzolini** [comment]
> This hit me suddenly after a v246 update. I don't know why but v245 was totally fine.

The patch was applied between 246 and 246?

> And providing the full path to `systemctl` as described here [#15699 (comment)](https://github.com/systemd/systemd/issues/15699#issuecomment-645843333) doesn't worked for me. But changing HOOKS [#15699 (comment)](https://github.com/systemd/systemd/issues/15699#issuecomment-624448522) from `systemd` to `udev` does.

Well, this is due to the fact you changed from using a systemd based initramfs to a busybox based one.

> Does using `systemd-boot` as a bootloader and having `systemd` in HOOKS is so unintended and uncommon setup? Does just using of all this convinient systemd features is bad? If so, somewhere is one Poettering crying 🥲

The bootloader plays no part in what happens in the initramfs. Please, let's stay focused.

**Comment by HanabishiRecca** [comment]
> Well, this is due to the fact you changed from using a systemd based initramfs to a busybox based one.
> The bootloader plays no part in what happens in the initramfs.

Thanks for the clarification. I've said that because bootloader played a role for me indirectly. Systemd based initramfs allows to not explicitly set the rootfs location if it's partition has the right type GUID. So my `options` line in the bootloader config was empty. After switching to udev I had to edit bootloader config too.

**Comment by eli-schwartz** [comment]
> Let's not break the common case that works for 99% of people because of one weird setup ;)

I'm not sure I understand this statement. What is breaking here if you revert that commit? The commit message points out it was purely a configure-time optimization, dropping information you didn't think you needed in order to skip a tiny bit of work. And it turns out that that information might in fact be needed...

**Comment by DaanDeMeyer** [comment]
@eli-schwartz This is also fixed if the mkinitcpio initramfs symlink from /usr/local/bin to /usr/bin is removed. Do you know if we still need this? It's been there for years but I'm not sure if it's actually used. While this should probably be fixed in systemd as well, it might not hurt to remove that bit from mkinitcpio as well if we can.

The commit message for the commit that added the symlink mentions the following:

> This also symlinks /usr/local/{lib,bin} into the common /usr/lib and
/usr/bin, respectively, so that there's always a way to override libs
and bins, and they're automatically pulled into our strict early init
path of /usr/bin.

**Comment by falconindy** [comment]
We don't know if the symlink is used. We can't know. The symlink from /usr/local/bin to /usr/bin is a feature, as described by the commit.

+1 for reverting cdc6804 unless it actually fixes a real bug.

**Comment by grazzolini** [comment]
@DaanDeMeyer, also, we have PATH being set with /usr/local/bin coming first. If we just remove the symlink, we might also need to fiddle with PATH. I took a look at mkinitcpio's run hooks and nothing really seems to depend on /usr/local/bin. But, as @falconindy mentioned, it's a feature, and it might be being used.

**Comment by DaanDeMeyer** [comment]
@keszybz I think the problem is the opposite. Instead of resolving too eagerly, we don't resolve eagerly enough. In the initramfs, systemd finds systemctl at /usr/local/bin/systemctl and serializes it without resolving it. In the rootfs, systemd finds systemctl at /usr/bin/systemctl and compares it against the serialized systemctl which differs which results in this issue. If we serialize the resolved path, the issue is fixed as well. However, doing that would break the reverse case where both the initramfs and the rootfs have symlinks at the same location that point to wildly different paths. Maybe we actually want the warning in that case though, I'm not sure. 

I generally think trying to match units from the initramfs up to units in the rootfs is a bit iffy. Ideally they would be kept separate. I think the current setup even prevents running a second instance of a unit in the rootfs if an instance of it is already started in the initramfs. Wouldn't it be possible to put all units that are pulled in from the initramfs under a prefix or something so that they don't get mixed up with units from the rootfs?

Regardless of the right fix, the quick fix is still probably either reverting the path commit or resolving the paths before serializing.

**Comment by HanabishiRecca** [comment]
I've made a little investigation. As mentioned this is the `mkinitcpio` issue so I've tried `dracut`. With a systemd module included of course.
Switch-root seems to be ok, systemctl is working (as expected), BUT except for the one last thing: `systemd-logind` is still broken. It just can't start, drains 100% CPU and the login prompt doesn't appear. After the some time it fails and drops this weird error:
```
systemd-logind[570]: Failed to start autovt@tty2.service: No buffer space available
```
Then it restarts (I think) and the second run turns out successful, login prompt finally appears.

I've checked this several times. It happens every time when systemd module/hook is used. When using udev-busybox the problem disappears.
I don't know is this really related to the discussed issue but maybe the problem is deeper than it seems.

**Comment by eli-schwartz** [comment]
> @eli-schwartz This is also fixed if the mkinitcpio initramfs symlink from /usr/local/bin to /usr/bin is removed. Do you know if we still need this? It's been there for years but I'm not sure if it's actually used. While this should probably be fixed in systemd as well, it might not hurt to remove that bit from mkinitcpio as well if we can.

Well, I'm not the right person to ask. :p But both maintainers of mkinitcpio support keeping it.

It's not entirely clear to me what the commit message is referring to. But if I had to guess purely based on the code, I'd assume it is to:
- ensure, if the user system contains overridden programs in the /usr/local hierarchy, they are propagated to the initramfs rather than introducing inconsistency between the initramfs and the rootfs, and that only one version exists (don't waste space)
- ensure, if the initramfs ends up containing scripts which reference other programs using qualified paths in /usr/local, they still work

I think the first could be alternatively solved by making the symlink only during the initramfs build stage, but deleting it before generating the cpio archive.
The second could be alternatively solved by creating symlinks for all files *if* they came from /usr/local, rather than the entire directory. Which seems complex. Or by removing /usr/local/bin from the PATH used by systemd and friends in the initramfs, but still creating the directory.

It's not clear to me that this is a better solution than making systemd better about not sharing state with the initramfs.

**Comment by HanabishiRecca** [comment]
More details about initramfs investigation. Here https://github.com/systemd/systemd/issues/16076#issuecomment-670993689 I was partially wrong. Seems like `dracut` is also affected. 

Here is the proof:
![image](https://user-images.githubusercontent.com/13597663/89730343-3423e900-da57-11ea-8202-ac22c4dbb156.png)

Systemctl not responding.

And htop capture:
![image](https://user-images.githubusercontent.com/13597663/89730361-633a5a80-da57-11ea-9a8e-4be7d2474a5a.png)

Exaclty the same situation as with mkinitcpio. The only difference is it doesn't appear instantly on boot and doesn't drop `initrd-switch-root.service` warning. But the problem appears when `systemd-logind` is called.

Does someone else tried to reproduce the problem with dracut? Can confirm it?
Because turns out this is **not mkinitcpio exclusive bug**.

**Comment by sandsmark** [comment]
> Let's not break the common case that works for 99% of people because of one weird setup ;)

If you're referring to my command, I don't think reverting will break anything? Unless the revert isn't clean, at least. Even if there's been new additions that need to get the `@rootbindir@/` there's less chance of something breaking.

But I agree with the rest here, I think it's better to have explicit paths instead of trying to play shell and resolve paths in general. Bugs resulting from this can be fairly tricky to track down for your average user/sysadmin/ricer.

(And Hanabishi, considering that Lennart already assigned a milestone I don't think you need to prove the point further. :-)

**Comment by HanabishiRecca** [comment]
@sandsmark I'm just sharing the information. Because roots of the problem might be deeper, not only in this commit.
