### ISSUE TITLE
systemd-resolved: SERVFAIL instead of NXDOMAIN when DNSSEC=allow-downgrade

### ISSUE THREAD

**Issue by seblu** [systemd/systemd#19472]
**systemd version the issue has been seen with**
 > systemd 245 (245.4-4ubuntu3.6)

**Used distribution**
 > 20.04.2 LTS (Focal Fossa)

**Linux kernel version used** (`uname -a`)

 > `Linux ilovelennart 5.12.0-clang-seblu #4 SMP PREEMPT Wed Apr 28 02:41:53 CEST 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
> host -t a plex.tv
> plex.tv has address 108.128.10.254
> plex.tv has address 99.81.164.127
> plex.tv has address 99.81.153.144

> host -t aaaa plex.tv
> plex.tv has no AAAA record

> host -t a foo.plex.tv
>  foo.plex.tv has no A record

**Unexpected behaviour you saw**
> host -t a plex.tv
> plex.tv has address 108.128.10.254
> plex.tv has address 99.81.164.127
> plex.tv has address 99.81.153.144

> host -t aaaa plex.tv
> Host plex.tv not found: 2(SERVFAIL)

> host -t a foo.plex.tv
> Host foo.plex.tv not found: 2(SERVFAIL)

**Steps to reproduce the problem**
 1. Enable systemd-resolved stub and use it
 2. Use `DNSSEC=allow-downgrade`
 3. Resolve non existant record (NXDOMAIN) on a domain with DNSSEC records.

**Rationale**
This may create sneaky breakage by failing to resolve a domain because the domain has a A record but no AAAA records, like `plex.tv`.

Please note the `plex.tv` domain [has a no DS records published](https://dnssec-analyzer.verisignlabs.com/plex.tv) so the DNSSEC validation should always fail.
I also tested this with fully validated domains and the return is also SERVFAIL instead of NXDOMAIN.

So there is maybe 2 different issues : 
1. The resolution of `plex.tv` should always be downgraded and so return NXDOMAIN and not SERVFAIL.
2. Resolution of validated DNSSEC domains, should return NXDOMAIN when records not exists and are NSEC validated. Not SERVFAIL.
```
$ resolvectl query toto.seblu.net 
toto.seblu.net: resolve call failed: DNSSEC validation failed: no-signature
$ host -t a toto.seblu.net
Host toto.seblu.net not found: 2(SERVFAIL)
$ delv @1.1.1.1 toto.seblu.net
;; resolution failed: ncache nxdomain
; negative response, fully validated
; toto.seblu.net.		2828	IN	\-ANY	;-$NXDOMAIN
; seblu.net. SOA dns1.seblu.net. root.seblu.net. 2021042800 14400 3600 31449600 3600
; seblu.net. RRSIG SOA ...
; c2hdoj1ar6nnk4gpjqshke4rv0o17a4r.seblu.net. RRSIG NSEC3 ...
; c2hdoj1ar6nnk4gpjqshke4rv0o17a4r.seblu.net. NSEC3 1 0 1 ADD947E98FB120DB57D4DE3C1ACFB96B C47ICE82D4IBOBGKJJETK6RDKDG3NTP6 A NS SOA MX TXT AAAA RRSIG DNSKEY NSEC3PARAM CAA
; d1rk3ga9eacpvu33ofeonlbufqlgdfit.seblu.net. RRSIG NSEC3 ...
; d1rk3ga9eacpvu33ofeonlbufqlgdfit.seblu.net. NSEC3 1 0 1 ADD947E98FB120DB57D4DE3C1ACFB96B DNJ6L8JSS6MCG5USAOOF9OI86HR9TFAV A SSHFP RRSIG
; gpa9k6servdi1kgqe7266kbvhf9lc1ig.seblu.net. RRSIG NSEC3 ...
; gpa9k6servdi1kgqe7266kbvhf9lc1ig.seblu.net. NSEC3 1 0 1 ADD947E98FB120DB57D4DE3C1ACFB96B HC9HLHAFOU3QV27K4K2JGOMMHP1CDSJQ CNAME RRSIG
```

**Additional program output to the terminal or log subsystem illustrating the issue**

Transaction resolving `host -t a plex.tv`:
```text
SYSTEMD_LOG_LEVEL=debug /lib/systemd/systemd-resolved
...
Got DNS stub UDP query packet for id 64814
Looking up RR for plex.tv IN A.
Cache miss for plex.tv IN A
Transaction 42605 for <plex.tv IN A> scope dns on mv-eth0/*.
Using feature level UDP+EDNS0+DO+LARGE for transaction 42605.
Using DNS server 192.168.242.1 for transaction 42605.
Sending query packet with id 42605.
Processing query...
Processing incoming packet on transaction 42605 (rcode=SUCCESS).
Requesting DNSKEY to validate transaction 42605 (plex.tv, RRSIG with key tag: 34505).
Cache miss for plex.tv IN DNSKEY
Transaction 39614 for <plex.tv IN DNSKEY> scope dns on mv-eth0/*.
Using feature level UDP+EDNS0+DO+LARGE for transaction 39614.
Using DNS server 192.168.242.1 for transaction 39614.
Sending query packet with id 39614.
Processing incoming packet on transaction 39614 (rcode=SUCCESS).
Requesting DS to validate transaction 39614 (plex.tv, DNSKEY with key tag: 2371).
Cache miss for plex.tv IN DS
Transaction 1100 for <plex.tv IN DS> scope dns on mv-eth0/*.
Using feature level UDP+EDNS0+DO+LARGE for transaction 1100.
Using DNS server 192.168.242.1 for transaction 1100.
Sending query packet with id 1100.
Requesting DS to validate transaction 39614 (plex.tv, DNSKEY with key tag: 34505).
Processing incoming packet on transaction 1100 (rcode=SUCCESS).
Requesting DNSKEY to validate transaction 1100 (tv, RRSIG with key tag: 26484).
Cache miss for tv IN DNSKEY
Transaction 40800 for <tv IN DNSKEY> scope dns on mv-eth0/*.
Using feature level UDP+EDNS0+DO+LARGE for transaction 40800.
Using DNS server 192.168.242.1 for transaction 40800.
Sending query packet with id 40800.
Requesting DNSKEY to validate transaction 1100 (E7Q4EUC85B62PB5AJFJ5J1ACUGC1ET4Q.tv, RRSIG with key tag: 26484).
Requesting DNSKEY to validate transaction 1100 (90CGVU51EASICNJPRL9E6CKLJ7I6UNAM.tv, RRSIG with key tag: 26484).
Processing incoming packet on transaction 40800 (rcode=SUCCESS).
Requesting DS to validate transaction 40800 (tv, DNSKEY with key tag: 44904).
Cache miss for tv IN DS
Transaction 49740 for <tv IN DS> scope dns on mv-eth0/*.
Using feature level UDP+EDNS0+DO+LARGE for transaction 49740.
Using DNS server 192.168.242.1 for transaction 49740.
Sending query packet with id 49740.
Requesting DS to validate transaction 40800 (tv, DNSKEY with key tag: 26484).
Processing incoming packet on transaction 49740 (rcode=SUCCESS).
Requesting DNSKEY to validate transaction 49740 (tv, RRSIG with key tag: 14631).
Cache miss for . IN DNSKEY
Transaction 12267 for <. IN DNSKEY> scope dns on mv-eth0/*.
Using feature level UDP+EDNS0+DO+LARGE for transaction 12267.
Using DNS server 192.168.242.1 for transaction 12267.
Sending query packet with id 12267.
Processing incoming packet on transaction 12267 (rcode=SUCCESS).
Requesting DS to validate transaction 12267 (., DNSKEY with key tag: 20326).
Requesting DS to validate transaction 12267 (., DNSKEY with key tag: 14631).
Validating response from transaction 12267 (. IN DNSKEY).
Looking at . IN DNSKEY 257 3 RSASHA256                            AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTOiW1vkIbzxeF3+/4RgWOq7HrxRixHlFlExOLAJr5emLvN7SWXgnLh4+B5xQlNVz8Og8kvArMtNROxVQuCaSnIDdD5LKyWbRd2n9WGe2R8PzgCmr3EgVLrjy
                           BxWezF0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7pr+eoZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLYA4/ilBmSVIzuDWfdRUfhHdY6+cn8HFRm+2hM8AnXGXws9555KrUB5qihylGa
                           8subX2Nn6UwNR1AkUTV74bU=
        -- Flags: SEP ZONE_KEY
        -- Key tag: 20326: validated
Found verdict for lookup . IN DNSKEY: secure
Added positive authenticated cache entry for . IN DNSKEY 7200s on mv-eth0/INET/192.168.242.1
Added positive authenticated cache entry for . IN DNSKEY 7200s on mv-eth0/INET/192.168.242.1
Transaction 12267 for <. IN DNSKEY> on scope dns on mv-eth0/* now complete with <success> from network (authenticated).
Validating response from transaction 49740 (tv IN DS).
Looking at tv IN DS 44904 8 2 1cfe1309925b78f42c8b4862a670b0bab9fc142ed8b4d41e24c65fe6a0d9dfb4: validated
Found verdict for lookup tv IN DS: secure
Added positive authenticated cache entry for tv IN DS 7200s on mv-eth0/INET/192.168.242.1
Transaction 49740 for <tv IN DS> on scope dns on mv-eth0/* now complete with <success> from network (authenticated).
Validating response from transaction 40800 (tv IN DNSKEY).
Looking at tv IN DNSKEY 257 3 RSASHA256                             AQPUXZN37tf3GvSdajRgOtSjTW2kNu7rZyi7BsqB4tjxt9+DIniRdBRxrqNMQRCI7q/xN8F6VB9RMYwkwyN+gt9zaKw9xndID6RwuzNhhTspAEa6r52k/Y3AgghUWrGHmi4zwrUFTAyzKF+V8JzQ/k///g8wAneJF
                            k02va1JYDIkl4SXfIqqtYNFCHa0NMdBtElfvMsrJSD/LB5qQ1dUafSnDZ3ydiOqSOe3mYbu0uUOznGpkvl/ek9v6RgaRgm4GmeAnd5YCGq0YqsXlqo9Ov1fLR8SKc/MXrmLLdRD/67ihtATBItm2Or2JyAKMAobDz
                            R3IuFPfXkTQx8jnsVDgqp/
        -- Flags: SEP ZONE_KEY
        -- Key tag: 44904: validated
Found verdict for lookup tv IN DNSKEY: secure
Added positive authenticated cache entry for tv IN DNSKEY 6239s on mv-eth0/INET/192.168.242.1
Added positive authenticated cache entry for tv IN DNSKEY 6239s on mv-eth0/INET/192.168.242.1
Transaction 40800 for <tv IN DNSKEY> on scope dns on mv-eth0/* now complete with <success> from network (authenticated).
Validating response from transaction 1100 (plex.tv IN DS).
Looking at E7Q4EUC85B62PB5AJFJ5J1ACUGC1ET4Q.tv IN NSEC3 1 1 0 - E82QTN8CDGTCVRGO2NPET7KN70V9NDVJ ( NS SOA RRSIG DNSKEY NSEC3PARAM ): validated
Found verdict for lookup E7Q4EUC85B62PB5AJFJ5J1ACUGC1ET4Q.tv IN NSEC3: secure
Looking at 90CGVU51EASICNJPRL9E6CKLJ7I6UNAM.tv IN NSEC3 1 1 0 - 90FM2BVDED3LT83D7RTMNR7ERH1OBD6T ( NS DS RRSIG ): validated
Found verdict for lookup 90CGVU51EASICNJPRL9E6CKLJ7I6UNAM.tv IN NSEC3: secure
Looking at tv IN SOA ac1.nstld.com info.verisign-grs.com 1619715605 1800 900 604800 86400: validated
Found verdict for lookup tv IN SOA: secure
Data is NSEC3 opt-out via NSEC/NSEC3 for transaction 1100 (plex.tv IN DS)
Found verdict for lookup plex.tv IN DS: insecure
Added positive authenticated cache entry for E7Q4EUC85B62PB5AJFJ5J1ACUGC1ET4Q.tv IN NSEC3 741s on mv-eth0/INET/192.168.242.1
Added positive authenticated cache entry for tv IN SOA 741s on mv-eth0/INET/192.168.242.1
Added NODATA cache entry for plex.tv IN DS 741s
Transaction 1100 for <plex.tv IN DS> on scope dns on mv-eth0/* now complete with <success> from network (unsigned).
Validating response from transaction 39614 (plex.tv IN DNSKEY).
Looking at plex.tv IN DNSKEY 257 3 ECDSAP256SHA256                                        mdsswUyr3DPW132mOi8V9xESWE8jTo0dxCjjnopKl+GqJxpVXckHAeF+KkxLbxILfDLUT0rAK9iUzy1L53eKGQ==
        -- Flags: SEP ZONE_KEY
        -- Key tag: 2371: missing-key
Looking at plex.tv IN DNSKEY 256 3 ECDSAP256SHA256                                        oJMRESz5E4gYzS/q6XDrvU1qMPYIjCWzJaOau8XNEZeqCYKD5ar0IRd8KqXXFJkqmVfRvMGPmM1x8fGAa2XhSA==
        -- Flags: ZONE_KEY
        -- Key tag: 34505: missing-key
Looking at plex.tv IN DNSKEY 257 3 ECDSAP256SHA256                                        mdsswUyr3DPW132mOi8V9xESWE8jTo0dxCjjnopKl+GqJxpVXckHAeF+KkxLbxILfDLUT0rAK9iUzy1L53eKGQ==
        -- Flags: SEP ZONE_KEY
        -- Key tag: 2371: missing-key
Found verdict for lookup plex.tv IN DNSKEY: insecure
Added positive unauthenticated cache entry for plex.tv IN DNSKEY 2247s on mv-eth0/INET/192.168.242.1
Added positive unauthenticated cache entry for plex.tv IN DNSKEY 2247s on mv-eth0/INET/192.168.242.1
Transaction 39614 for <plex.tv IN DNSKEY> on scope dns on mv-eth0/* now complete with <success> from network (unsigned).
Validating response from transaction 42605 (plex.tv IN A).
Looking at plex.tv IN A 108.128.10.254: missing-key
Found verdict for lookup plex.tv IN A: insecure
Added positive unauthenticated cache entry for plex.tv IN A 10s on mv-eth0/INET/192.168.242.1
Added positive unauthenticated cache entry for plex.tv IN A 10s on mv-eth0/INET/192.168.242.1
Added positive unauthenticated cache entry for plex.tv IN A 10s on mv-eth0/INET/192.168.242.1
Transaction 42605 for <plex.tv IN A> on scope dns on mv-eth0/* now complete with <success> from network (unsigned).
Sending response packet with id 64814 on interface 1/AF_INET.
Freeing transaction 42605.
Freeing transaction 39614.
Freeing transaction 1100.
Freeing transaction 40800.
Freeing transaction 49740.
Freeing transaction 12267.
```

Transaction resolving `host -t aaaa plex.tv` (SERVFAIL)
```text
SYSTEMD_LOG_LEVEL=debug /lib/systemd/systemd-resolved
...
Got DNS stub UDP query packet for id 24279
Looking up RR for plex.tv IN AAAA.
Cache miss for plex.tv IN AAAA
Transaction 62533 for <plex.tv IN AAAA> scope dns on mv-eth0/*.
Using feature level UDP+EDNS0+DO+LARGE for transaction 62533.
Using DNS server 192.168.242.1 for transaction 62533.
Sending query packet with id 62533.
Processing query...
Processing incoming packet on transaction 62533 (rcode=SUCCESS).
Requesting DNSKEY to validate transaction 62533 (plex.tv, RRSIG with key tag: 34505).
Cache miss for plex.tv IN DNSKEY
Transaction 12278 for <plex.tv IN DNSKEY> scope dns on mv-eth0/*.
Using feature level UDP+EDNS0+DO+LARGE for transaction 12278.
Using DNS server 192.168.242.1 for transaction 12278.
Sending query packet with id 12278.
Requesting DNSKEY to validate transaction 62533 (plex.tv, RRSIG with key tag: 34505).
Processing incoming packet on transaction 12278 (rcode=SUCCESS).
Requesting DS to validate transaction 12278 (plex.tv, DNSKEY with key tag: 34505).
Cache miss for plex.tv IN DS
Transaction 234 for <plex.tv IN DS> scope dns on mv-eth0/*.
Using feature level UDP+EDNS0+DO+LARGE for transaction 234.
Using DNS server 192.168.242.1 for transaction 234.
Sending query packet with id 234.
Requesting DS to validate transaction 12278 (plex.tv, DNSKEY with key tag: 2371).
Processing incoming packet on transaction 234 (rcode=SUCCESS).
Requesting DNSKEY to validate transaction 234 (tv, RRSIG with key tag: 26484).
Cache miss for tv IN DNSKEY
Transaction 43617 for <tv IN DNSKEY> scope dns on mv-eth0/*.
Using feature level UDP+EDNS0+DO+LARGE for transaction 43617.
Using DNS server 192.168.242.1 for transaction 43617.
Sending query packet with id 43617.
Requesting DNSKEY to validate transaction 234 (E7Q4EUC85B62PB5AJFJ5J1ACUGC1ET4Q.tv, RRSIG with key tag: 26484).
Requesting DNSKEY to validate transaction 234 (90CGVU51EASICNJPRL9E6CKLJ7I6UNAM.tv, RRSIG with key tag: 26484).
Processing incoming packet on transaction 43617 (rcode=SUCCESS).
Requesting DS to validate transaction 43617 (tv, DNSKEY with key tag: 44904).
Cache miss for tv IN DS
Transaction 42637 for <tv IN DS> scope dns on mv-eth0/*.
Using feature level UDP+EDNS0+DO+LARGE for transaction 42637.
Using DNS server 192.168.242.1 for transaction 42637.
Sending query packet with id 42637.
Requesting DS to validate transaction 43617 (tv, DNSKEY with key tag: 26484).
Processing incoming packet on transaction 42637 (rcode=SUCCESS).
Requesting DNSKEY to validate transaction 42637 (tv, RRSIG with key tag: 14631).
Cache miss for . IN DNSKEY
Transaction 44876 for <. IN DNSKEY> scope dns on mv-eth0/*.
Using feature level UDP+EDNS0+DO+LARGE for transaction 44876.
Using DNS server 192.168.242.1 for transaction 44876.
Sending query packet with id 44876.
Processing incoming packet on transaction 44876 (rcode=SUCCESS).
Requesting DS to validate transaction 44876 (., DNSKEY with key tag: 20326).
Requesting DS to validate transaction 44876 (., DNSKEY with key tag: 14631).
Validating response from transaction 44876 (. IN DNSKEY).
Looking at . IN DNSKEY 257 3 RSASHA256                            AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTOiW1vkIbzxeF3+/4RgWOq7HrxRixHlFlExOLAJr5emLvN7SWXgnLh4+B5xQlNVz8Og8kvArMtNROxVQuCaSnIDdD5LKyWbRd2n9WGe2R8PzgCmr3EgVLrjy
                           BxWezF0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7pr+eoZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLYA4/ilBmSVIzuDWfdRUfhHdY6+cn8HFRm+2hM8AnXGXws9555KrUB5qihylGa
                           8subX2Nn6UwNR1AkUTV74bU=
        -- Flags: SEP ZONE_KEY
        -- Key tag: 20326: validated
Found verdict for lookup . IN DNSKEY: secure
Added positive authenticated cache entry for . IN DNSKEY 7200s on mv-eth0/INET/192.168.242.1
Added positive authenticated cache entry for . IN DNSKEY 7200s on mv-eth0/INET/192.168.242.1
Transaction 44876 for <. IN DNSKEY> on scope dns on mv-eth0/* now complete with <success> from network (authenticated).
Validating response from transaction 42637 (tv IN DS).
Looking at tv IN DS 44904 8 2 1cfe1309925b78f42c8b4862a670b0bab9fc142ed8b4d41e24c65fe6a0d9dfb4: validated
Found verdict for lookup tv IN DS: secure
Added positive authenticated cache entry for tv IN DS 4674s on mv-eth0/INET/192.168.242.1
Transaction 42637 for <tv IN DS> on scope dns on mv-eth0/* now complete with <success> from network (authenticated).
Validating response from transaction 43617 (tv IN DNSKEY).
Looking at tv IN DNSKEY 257 3 RSASHA256                             AQPUXZN37tf3GvSdajRgOtSjTW2kNu7rZyi7BsqB4tjxt9+DIniRdBRxrqNMQRCI7q/xN8F6VB9RMYwkwyN+gt9zaKw9xndID6RwuzNhhTspAEa6r52k/Y3AgghUWrGHmi4zwrUFTAyzKF+V8JzQ/k///g8wAneJF
                            k02va1JYDIkl4SXfIqqtYNFCHa0NMdBtElfvMsrJSD/LB5qQ1dUafSnDZ3ydiOqSOe3mYbu0uUOznGpkvl/ek9v6RgaRgm4GmeAnd5YCGq0YqsXlqo9Ov1fLR8SKc/MXrmLLdRD/67ihtATBItm2Or2JyAKMAobDz
                            R3IuFPfXkTQx8jnsVDgqp/
        -- Flags: SEP ZONE_KEY
        -- Key tag: 44904: validated
Found verdict for lookup tv IN DNSKEY: secure
Added positive authenticated cache entry for tv IN DNSKEY 7200s on mv-eth0/INET/192.168.242.1
Added positive authenticated cache entry for tv IN DNSKEY 7200s on mv-eth0/INET/192.168.242.1
Transaction 43617 for <tv IN DNSKEY> on scope dns on mv-eth0/* now complete with <success> from network (authenticated).
Validating response from transaction 234 (plex.tv IN DS).
Looking at E7Q4EUC85B62PB5AJFJ5J1ACUGC1ET4Q.tv IN NSEC3 1 1 0 - E82QTN8CDGTCVRGO2NPET7KN70V9NDVJ ( NS SOA RRSIG DNSKEY NSEC3PARAM ): validated
Found verdict for lookup E7Q4EUC85B62PB5AJFJ5J1ACUGC1ET4Q.tv IN NSEC3: secure
Looking at 90CGVU51EASICNJPRL9E6CKLJ7I6UNAM.tv IN NSEC3 1 1 0 - 90FM2BVDED3LT83D7RTMNR7ERH1OBD6T ( NS DS RRSIG ): validated
Found verdict for lookup 90CGVU51EASICNJPRL9E6CKLJ7I6UNAM.tv IN NSEC3: secure
Looking at tv IN SOA ac1.nstld.com info.verisign-grs.com 1619718605 1800 900 604800 86400: validated
Found verdict for lookup tv IN SOA: secure
Data is NSEC3 opt-out via NSEC/NSEC3 for transaction 234 (plex.tv IN DS)
Found verdict for lookup plex.tv IN DS: insecure
Added positive authenticated cache entry for E7Q4EUC85B62PB5AJFJ5J1ACUGC1ET4Q.tv IN NSEC3 7200s on mv-eth0/INET/192.168.242.1
Added positive authenticated cache entry for tv IN SOA 3585s on mv-eth0/INET/192.168.242.1
Added NODATA cache entry for plex.tv IN DS 3585s
Transaction 234 for <plex.tv IN DS> on scope dns on mv-eth0/* now complete with <success> from network (unsigned).
Validating response from transaction 12278 (plex.tv IN DNSKEY).
Looking at plex.tv IN DNSKEY 256 3 ECDSAP256SHA256                                        oJMRESz5E4gYzS/q6XDrvU1qMPYIjCWzJaOau8XNEZeqCYKD5ar0IRd8KqXXFJkqmVfRvMGPmM1x8fGAa2XhSA==
        -- Flags: ZONE_KEY
        -- Key tag: 34505: missing-key
Looking at plex.tv IN DNSKEY 257 3 ECDSAP256SHA256                                        mdsswUyr3DPW132mOi8V9xESWE8jTo0dxCjjnopKl+GqJxpVXckHAeF+KkxLbxILfDLUT0rAK9iUzy1L53eKGQ==
        -- Flags: SEP ZONE_KEY
        -- Key tag: 2371: missing-key
Looking at plex.tv IN DNSKEY 256 3 ECDSAP256SHA256                                        oJMRESz5E4gYzS/q6XDrvU1qMPYIjCWzJaOau8XNEZeqCYKD5ar0IRd8KqXXFJkqmVfRvMGPmM1x8fGAa2XhSA==
        -- Flags: ZONE_KEY
        -- Key tag: 34505: missing-key
Found verdict for lookup plex.tv IN DNSKEY: insecure
Added positive unauthenticated cache entry for plex.tv IN DNSKEY 695s on mv-eth0/INET/192.168.242.1
Added positive unauthenticated cache entry for plex.tv IN DNSKEY 695s on mv-eth0/INET/192.168.242.1
Transaction 12278 for <plex.tv IN DNSKEY> on scope dns on mv-eth0/* now complete with <success> from network (unsigned).
Validating response from transaction 62533 (plex.tv IN AAAA).
Looking at plex.tv IN NSEC \000.plex.tv ( A NS SOA HINFO MX TXT LOC SRV NAPTR CERT SSHFP RRSIG NSEC DNSKEY TLSA TYPE53 HIP CDS CDNSKEY OPENPGPKEY TYPE64 TYPE65 SPF URI CAA ): missing-key
Looking at plex.tv IN SOA jeremy.ns.cloudflare.com dns.cloudflare.com 2037114027 10000 2400 604800 3600: missing-key
Found verdict for lookup plex.tv IN SOA: insecure
Looking at plex.tv IN NSEC \000.plex.tv ( A NS SOA HINFO MX TXT LOC SRV NAPTR CERT SSHFP RRSIG NSEC DNSKEY TLSA TYPE53 HIP CDS CDNSKEY OPENPGPKEY TYPE64 TYPE65 SPF URI CAA ): missing-key
Found verdict for lookup plex.tv IN NSEC: insecure
Transaction 62533 for <plex.tv IN AAAA> on scope dns on mv-eth0/* now complete with <ENODATA> from network (unsigned).
Sending response packet with id 24279 on interface 1/AF_INET.
Freeing transaction 62533.
Freeing transaction 12278.
Freeing transaction 234.
Freeing transaction 43617.
Freeing transaction 42637.
Freeing transaction 44876.
```

*Workarounds*
1. Do not use the stub-resolver and ask the DNS resolver directly.
2. `DNSSEC=false`

**Comment by seblu** [comment]
I made a test on a more recent operation system, `Arch Linux` with
> systemd 248 (248-5-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

### The downgrading issue

Same issue with recent systemd version.

>  $ resolvectl query -t aaaa plex.tv    
>  plex.tv: resolve call failed: DNSSEC validation failed: no-signature

>  $ resolvectl query -t a plex.tv   
>   plex.tv IN A 99.81.153.144                                  -- link: eth0
>   plex.tv IN A 108.128.10.254                                 -- link: eth0
>   plex.tv IN A 99.81.164.127                                  -- link: eth0
>  -- Information acquired via protocol DNS in 23.1ms.
>  -- Data is authenticated: no; Data was acquired via local or encrypted transport: yes
>  -- Data from: network

**So, resolution of A record is downgraded (because it exists) but not for AAAA (because it doesn't)**


### The servfail on nxdomain with valid DNSSEC

Looks like it has been fixed on recent resolved version.

> $ host -t a ip4.seblu.net
> ip4.seblu.net has address 62.210.204.83

> $ host -t aaaa ip4.seblu.net
ip4.seblu.net has no AAAA record

**Comment by mrc0mmand** [comment]
This still appears to be relevant with the latest main (747bee2662fb611b34c3c594466338c4827b9777 ATTOW).

By having a domain `untrusted.test` with _valid_ signatures but without DS RR being in the parent, the behavior with resolved is as follows:

1) NXDOMAIN instead of NOERROR + NSEC (?) on non-existent RR
```
## Without resolved
# dig @1.2.3.1 AAAA untrusted.test 

; <<>> DiG 9.16.27-RH <<>> @1.2.3.1 AAAA untrusted.test
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11577
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;untrusted.test.			IN	AAAA

;; AUTHORITY SECTION:
untrusted.test.		86400	IN	SOA	ns1.signed.test. root.signed.test. 43 10800 900 604800 86400

;; Query time: 0 msec
;; SERVER: 1.2.3.1#53(1.2.3.1)
;; WHEN: Tue Apr 19 23:22:44 CEST 2022
;; MSG SIZE  rcvd: 95

## With resolved
# dig AAAA untrusted.test

; <<>> DiG 9.16.27-RH <<>> AAAA untrusted.test
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 39468
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;untrusted.test.			IN	AAAA

;; AUTHORITY SECTION:
test.			6859	IN	SOA	ns1.signed.test. root.signed.test. 45 10800 900 604800 86400

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue Apr 19 23:23:07 CEST 2022
;; MSG SIZE  rcvd: 95

# resolvectl query --cache=no --legend=no -t A   untrusted.test
untrusted.test IN A 1.2.3.121                               -- link: dns0
# resolvectl query --cache=no --legend=no -t AAAA   untrusted.test
untrusted.test: resolve call failed: DNSSEC validation failed: no-signature
```

2) SERVFAIL instead of NXDOMAIN on non-existent name
```
## Without resolved
# dig @1.2.3.1 +multiline +dnssec non-existent.untrusted.test

; <<>> DiG 9.16.27-RH <<>> @1.2.3.1 +multiline +dnssec non-existent.untrusted.test
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 53755
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 6, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1232
;; QUESTION SECTION:
;non-existent.untrusted.test. IN	A

;; AUTHORITY SECTION:
untrusted.test.		86400 IN SOA ns1.signed.test. root.signed.test. (
				43         ; serial
				10800      ; refresh (3 hours)
				900        ; retry (15 minutes)
				604800     ; expire (1 week)
				86400      ; minimum (1 day)
				)
mail.untrusted.test.	86400 IN NSEC *.wild.untrusted.test. A RRSIG NSEC
untrusted.test.		86400 IN NSEC mail.untrusted.test. A NS SOA MX RRSIG NSEC DNSKEY
untrusted.test.		86400 IN RRSIG SOA 13 2 86400 (
				20220503204813 20220419191813 14746 untrusted.test.
				jHe+wXAIenvvrqa5EqqFTBgP22th5kCAyx5t9k4Itx4R
				YnACFR82qndpJGfE5DIheWU9obqXoEiOqdSu+zYJbw== )
mail.untrusted.test.	86400 IN RRSIG NSEC 13 3 86400 (
				20220503204813 20220419191813 14746 untrusted.test.
				YfuJKIDMuD39RJ5QiGST81BPUmHxEsDvkpR4JlPShqlV
				xgQpkvpX2zQUMhKBRyFLVYy4ScRTXVKAu/71Qc9HFg== )
untrusted.test.		86400 IN RRSIG NSEC 13 2 86400 (
				20220503204813 20220419191813 14746 untrusted.test.
				9ax/QG9TK/ngOnDEpRe61211H/sHUIB1tLnzEZsHQ5oa
				4Z1pehydi2o9X/GQflsDesVDOTHVjbNSfu2FYSAZQg== )

;; Query time: 0 msec
;; SERVER: 1.2.3.1#53(1.2.3.1)
;; WHEN: Tue Apr 19 23:26:15 CEST 2022
;; MSG SIZE  rcvd: 528

## With resolved
# dig +multiline +dnssec non-existent.untrusted.test

; <<>> DiG 9.16.27-RH <<>> +multiline +dnssec non-existent.untrusted.test
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 57316
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 3, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 65494
;; QUESTION SECTION:
;non-existent.untrusted.test. IN	A

;; AUTHORITY SECTION:
untrusted.test.		86400 IN SOA ns1.signed.test. root.signed.test. (
				43         ; serial
				10800      ; refresh (3 hours)
				900        ; retry (15 minutes)
				604800     ; expire (1 week)
				86400      ; minimum (1 day)
				)
mail.untrusted.test.	86400 IN NSEC *.wild.untrusted.test. A RRSIG NSEC
untrusted.test.		86400 IN NSEC mail.untrusted.test. A NS SOA MX RRSIG NSEC DNSKEY

;; Query time: 1 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue Apr 19 23:26:38 CEST 2022
;; MSG SIZE  rcvd: 198

# resolvectl query --cache=no --legend=no non-existent.untrusted.test
non-existent.untrusted.test: resolve call failed: DNSSEC validation failed: no-signature
```

Should be soon reproducible by #23104.
