### ISSUE TITLE
Sysv-generator skips init.d script when it is a symlink

### ISSUE THREAD

**Issue by michalklempa** [systemd/systemd#2141]
```
lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.2 (Maipo)
Release:        7.2
Codename:       Maipo
```

When script in

```
/etc/init.d/
```

is not a regular file but symlink to script, as it is for ambari-server in my case:

```
ls -alh /etc/init.d/
total 56K
drwxr-xr-x.  2 root root 4.0K Dec 11 07:38 .
drwxr-xr-x. 10 root root 4.0K Sep 16 07:59 ..
-rwxr-xr-x   1 root root 1.6K Nov  2 14:46 ambari-agent
lrwxrwxrwx   1 root root   23 Dec 11 07:38 ambari-server -> /usr/sbin/ambari-server
```

the syv-generator skips the file and does not generate systemd service. Causing systemd to not recognize the service and not listing it  by `systemctl list-unit-files --type service`

When I removed symlink `/etc/init.d/ambari-server` and copied the original file `/usr/sbin/ambari-server` to `/etc/init.d/ambari-server`. I have refreshed systemd configuration `systemctl daemon-reload`. Then the service `ambari-server` appeared in  `systemctl list-unit-files --type service`.

I guess the reason for this behavior is in this line of code:
https://github.com/systemd/systemd/blob/master/src/sysv-generator/sysv-generator.c#L774
where the file is checked whether it is regular file by:

```
                        if (!S_ISREG(st.st_mode))
                                continue;
```

I do not know if this was desired behavior (as it was hard to troubleshoot) or it is a mistake. If this is desired behavior, it should be documented somewhere or at least log message should be emitted. Apparently, there exists at least one piece of software which is shipped with init.d script as symlink.

**Comment by lnykryn** [comment]
This should be already fixed in current systemd.
https://github.com/systemd/systemd/commit/7b729f8686a83b24f3d9a891cde1c

**Comment by michich** [comment]
You did not mention the exact version of systemd that you're using. I'm guessing you have the version that RHEL7.2 ships and did not build systemd from upstream git by yourself.

You are seeing this bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1285492

**Comment by lnykryn** [comment]
219-19 in rhel currently does not have that patch. It will be fixed in next release.

**Comment by PeterHorvathIsento** [comment]
2018-03-09: contrary the answer, the bug is still here, the source is unchanged.

**Comment by lnykryn** [comment]
@PeterHorvathIsento if you are speaking about centos/rhel, can you please open a new bug on our bugzilla https://bugzilla.redhat.com/ ? Upstream issue tracker is not a correct place for this discussion.
