### ISSUE TITLE
Cannot mount /boot after removing usb device

### ISSUE THREAD

**Issue by micah** [systemd/systemd#230]
Hi,

I have my /boot partition on a USB stick. It is inserted to the machine to boot it, and is configured to be mounted read-only in the fstab. 

I used to be able to simply remove the usb from the system after it has booted, and udev would remove the mount point. Then when I wish to have it available again (for example, when I need to regenerate an initramfs), I would insert the USB, and then mount /boot as rw for the operation, then unmount it again. One could argue that I should 'umount /boot' before removing the device from the system, however this shouldn't matter.

Now, if I remove the device from the system (or umount /boot and then remove the device) it is no longer mounted, as before. However, I cannot mount it again, it simply doesn't show up in mount:

```
root@muck:/home/micah# umount /boot

[remove device from system]

root@muck:/home/micah# df
Filesystem     1K-blocks      Used Available Use% Mounted on
udev               10240         0     10240   0% /dev
tmpfs            3274344      1456   3272888   1% /run
/dev/dm-0      113290912 103756284   3756660  97% /
tmpfs            8185860    133016   8052844   2% /dev/shm
tmpfs               5120         4      5116   1% /run/lock
tmpfs            8185860         0   8185860   0% /sys/fs/cgroup
tmpfs            1637172         4   1637168   1% /run/user/1000

[insert device]

root@muck:/home/micah# mount /boot
root@muck:/home/micah# df
Filesystem     1K-blocks      Used Available Use% Mounted on
udev               10240         0     10240   0% /dev
tmpfs            3274344      1456   3272888   1% /run
/dev/dm-0      113290912 103756284   3756660  97% /
tmpfs            8185860    133016   8052844   2% /dev/shm
tmpfs               5120         4      5116   1% /run/lock
tmpfs            8185860         0   8185860   0% /sys/fs/cgroup
tmpfs            1637172         4   1637168   1% /run/user/1000
```

The device is inserted in the system and available, it shows up in dmesg. This is what the journal says when I umounted:

```
Jun 16 12:13:43 muck kernel: EXT4-fs (sde1): mounted filesystem with ordered data mode. Opts: (null)
Jun 16 12:13:43 muck systemd[1]: boot.mount: Unit is bound to inactive unit dev-disk-by\x2duuid-2ddd48ad\x2d2e02\x2d492e\x2db5d7\x2df95e8e91ebac.device. Stopping, too.
Jun 16 12:13:43 muck systemd[1]: Unmounting /boot...
Jun 16 12:13:43 muck systemd[1]: Unmounted /boot.
```

huh, ok, so it immediately unmounted it? Thats odd... 

```
root@muck:/home/micah# systemctl status dev-disk-by\x2duuid-2ddd48ad\x2d2e02\x2d492e\x2db5d7\x2df95e8e91ebac.device
● dev-disk-byx2duuid-2ddd48adx2d2e02x2d492ex2db5d7x2df95e8e91ebac.device
   Loaded: loaded
   Active: inactive (dead)
```

ok its because its inactive, lets activate it:

```
root@muck:/home/micah# systemctl start dev-disk-by\x2duuid-2ddd48ad\x2d2e02\x2d492e\x2db5d7\x2df95e8e91ebac.device
Jun 16 12:15:32 muck polkitd(authority=local)[1549]: Registered Authentication Agent for unix-process:28960:592467 (system bus name :1.138 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jun 16 12:17:01 muck CRON[29160]: pam_unix(cron:session): session closed for user root
systemctl status dev-disk-by\x2duuid-2ddd48ad\x2d2e02\x2d492e\x2db5d7\x2df95e8e91ebac.deviceJun 16 12:17:02 muck systemd[1]: dev-disk-byx2duuid-2ddd48adx2d2e02x2d492ex2db5d7x2df95e8e91ebac.device: Job dev-disk-byx2duuid-2ddd48adx2d2e02x2d492ex2db5d7x2df95e8e91ebac.device/start timed out.
Jun 16 12:17:02 muck systemd[1]: Timed out waiting for device dev-disk-byx2duuid-2ddd48adx2d2e02x2d492ex2db5d7x2df95e8e91ebac.device.
Jun 16 12:17:02 muck systemd[1]: dev-disk-byx2duuid-2ddd48adx2d2e02x2d492ex2db5d7x2df95e8e91ebac.device: Job dev-disk-byx2duuid-2ddd48adx2d2e02x2d492ex2db5d7x2df95e8e91ebac.device/start failed with result 'timeout'.
```

**Comment by poettering** [comment]
THis is already fixed in git. The various distros have already backported patches.

**Comment by dkg** [comment]
Is this a duplicate of some other bug report?  if so, which one?

Is it fixed with a specific git commit?  if so, which one?

How is micah supposed to know which patch to urge his distro to backport, since it clearly isn't fixed for him?
