### ISSUE TITLE
Failed to save link data to /run/systemd/netif/links/

### ISSUE THREAD

**Issue by ltagliamonte-dd** [systemd/systemd#23071]
Creating a new issue for more visibility.
It appears that https://github.com/systemd/systemd/pull/9376 hasn't completely fix the issue with systemd:

```
Failed to save link data to /run/systemd/netif/links/
```

```
systemctl --version
systemd 245 (245.4-4ubuntu3.15)
```

```
uptime
 16:13:20 up 4 days, 22:17,  1 user,  load average: 1.07, 0.60, 0.47
```

```
ls -l /run/systemd/netif
total 4
drwxr-xr-x 2 systemd-timesync systemd-resolve  60 Apr  8 17:56 leases
drwxr-xr-x 2 systemd-timesync systemd-resolve 120 Apr  8 17:59 links
drwxr-xr-x 2 systemd-timesync systemd-resolve  40 Apr  8 17:56 lldp
-rw-r--r-- 1 systemd-network  systemd-network 151 Apr  8 17:59 state
```

```
networkctl status ens5
● 2: ens5                                                              
             Link File: /usr/lib/systemd/network/99-default.link       
          Network File: /run/systemd/network/10-netplan-ens5.network   
                  Type: ether                                          
                 State: routable (configured)
     Alternative Names: enp0s5                                         
                  Path: pci-0000:00:05.0                               
                Driver: ena                                            
                Vendor: Amazon.com, Inc.                               
                 Model: Elastic Network Adapter (ENA)                  
            HW Address: 06:81:3d:e8:2e:3f                              
                   MTU: 9001 (min: 128, max: 9216)                     
  Queue Length (Tx/Rx): 16/16                                          
               Address: 10.4.162.140 (DHCP4)                           
                        fe80::481:3dff:fee8:2e3f                       
               Gateway: 10.4.160.1                                     
                   DNS: 10.4.0.2                                       
        Search Domains: us-west-2.compute.internal                     
     Activation Policy: up                                             
   Required For Online: yes                                            

Apr 13 16:14:21 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Apr 13 16:14:21 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Apr 13 16:14:21 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Apr 13 16:14:21 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Apr 13 16:14:21 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Apr 13 16:14:22 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Apr 13 16:14:22 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Apr 13 16:14:22 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Apr 13 16:14:22 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Apr 13 16:14:22 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
```

```
cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```
uname -a
Linux ip-10-4-162-140 5.11.0-1028-aws #31~20.04.1-Ubuntu SMP Fri Jan 14 14:37:50 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

```
getenforce
Disabled
```

**Comment by poettering** [comment]
Sorry, but 245 is simply too old to be tracked here. The issue submission form should have made that very clear. Only issues with the two most recently released upstream versions should be tracked here (i.e. 249 at 250 right now).

For older stuff, please contact your distro. Or update to something more current.

Sorry if that's disappointing, but given there is a good chance the issue here is already fixed in more recent versions we really don't want to spend time on this, unless reproducible on current versions.

**Comment by ltagliamonte-dd** [comment]
Thank you @poettering, i totally understand.
I've opened this new issue since it was supposed to be fixed in 239.
Will try to update to latest and give it a test, will reopen if i still see the issue.

**Comment by ltagliamonte-dd** [comment]
I confirm that updating the same server to `systemd 250 (250.4-1)` i don't see the issue anymore.

**Comment by jkleckner** [comment]
Noting here for cross-reference purposes that the `Ubuntu 22.04.3 LTS` has systemd version `249.11-0ubuntu3.11` and also sees the `Failed to save` messages.
