### ISSUE TITLE
systemd-resolved /run/systemd/resolve/resolv.conf DNS ordering is nondeterministic and doesn't update entries if interface is destroyed

### ISSUE THREAD

**Issue by XANi** [systemd/systemd#27543]
### systemd version the issue has been seen with

252

### Used distribution

Debian 12

### Linux kernel version used

6.1.0-8-amd64

### CPU architectures issue was seen on

x86_64

### Component

resolvectl, systemd-resolved

### Expected behaviour you didn't see

Selecting DNS server passed via openvpn when tunnel is up.

Selecting DNS server from DHCP when tunnel is down.

### Unexpected behaviour you saw

* Using old DNS server, while new server is first in generated configs
* desync between `resolvectl` view and `/run/systemd/resolve/resolv.conf`

### Steps to reproduce the problem

No idea, it happens randomly. I'm using basic distro scripts with no modification. happens both with `/etc/openvpn/update-resolv-conf` and `/etc/openvpn/update-systemd-resolved  `

I am using `/etc/resolv.conf` symlinked to `/run/systemd/resolve/resolv.conf`  because using it via `127.0.0.53` triggered different bug described at the end

The state of the system is as follows

#### After OpenVPN connected:

resolvectl:
```
Global
       Protocols: +LLMNR +mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: uplink

Link 2 (eth0)
Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
     Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
   DNS Servers: 192.168.1.1
    DNS Domain: home.example.com

...
Link 11 (tun0)
Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
     Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
   DNS Servers: 10.0.2.9 10.0.2.4 10.0.2.5
    DNS Domain: work.example.com
```

cat /run/systemd/resolve/resolv.conf 
```
nameserver 192.168.1.1
nameserver 10.0.2.9
nameserver 10.0.2.4
# Too many DNS servers configured, the following entries may be ignored.
nameserver 10.0.2.5
search home.example.com work.example.com
```

The order is wrong. Sometimes it adds in right order, sometimes it does not. 

### BUT WAIT THERE IS MORE

```
nameserver 10.0.2.9
nameserver 10.0.2.4
nameserver 10.0.2.5
# Too many DNS servers configured, the following entries may be ignored.
nameserver 192.168.1.1
search work.example.com home.example.com
```

order is correct again. Another restart and it is back to being wrong. Sometimes, sometimes it stays right or wrong for few restarts, so my guess is there is no actual ordering.

### BUT WAIT THERE IS MORE

when tun0 goes byebye(openvpn disconnect):

```
Global
       Protocols: +LLMNR +mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: uplink

Link 2 (eth0)
Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
     Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
   DNS Servers: 192.168.1.1
    DNS Domain: home.example.com

```

no tun0 in sight. no entries ACCORDING to daemon itself. Daemon knows link does not exist yet generates wrong config.

```
nameserver 10.0.2.9
nameserver 10.0.2.4
nameserver 10.0.2.5
# Too many DNS servers configured, the following entries may be ignored.
nameserver 192.168.1.1
search work.example.com home.example.com
```
so it put 3 DNS addresses that are no longer accessible into the config. Restart "fixes" it.

The workaround is to delete the interface via `resolvectl` before it is going down but if that is not done, it stays in the generated file. Note that it isn't "just" misconfiguration of the app managing the tunnel it could simply die/be killed for other reasons and not be able to run any script before teardown. 

In before "why I am not using systemd question as resolver": when I did I had similar problems with it using wrong DNS server (after updating from resolvconf -based setup that worked but were obsoleted by distro)

### BUT WAIT, THERE IS MORE

When config is "correct":
```
nameserver 10.0.2.9
nameserver 10.0.2.4
nameserver 10.0.2.5
# Too many DNS servers configured, the following entries may be ignored.
nameserver 192.168.1.1
search work.example.com home.example.com
```

it doesn't mean it uses presented servers AT ALL 
![image](https://user-images.githubusercontent.com/147394/236459113-7d3ec034-4343-4c0a-acf6-cbb4a8a54e49.png)

The top window is dumping DNS traffic on eth0, interface from DHCP, which has DNS server `192.168.1.1`, the one at the bottom of the list.

The bottom window

* queries systemd-resolved directly via `127.0.0.53`. It uses eth0 to fulfil query and it shows on `resolvectl monitor` (which should probably also show interface, it is currently only shown as interface id in JSON mode)
* queries system resolver that uses `/run/systemd/resolve/resolv.conf`, which uses tun0 (DNS from OpenVPN)

I only started using `systemd-resolved` now because Debian upgrade dependencies forced it upon me, so it is quite likely it is not a new thing.

There is also no way to query what the generated order of DNS server is (resolvectl has no such option), aside from looking at the file (that apparently isn't synced correctly) or guess via tcpdump.

Also maybe "priority" option for when adding address would be a good idea ? then the DHCP or static entries could have lowest one and VPNs and such could just have higher.

I'd also LOVE option "use this DNS server only for that domains", that would be nice way to direct the corporate VPN DNS traffic only on the corporate domains. But that's tangential to the problem.

**Comment by Winterhuman** [comment]
"use this DNS server only for that domains" is already a thing with search/routing domains: https://github.com/systemd/systemd/blob/main/docs/RESOLVED-VPNS.md

**Comment by str1x** [comment]
same problem on fedora 39 with stub mode

**Comment by poettering** [comment]
> The order is wrong. Sometimes it adds in right order, sometimes it does not.

Why do you say that? Which order would be the "right" one? afaics, the order in resolvectl and your resolv.conf fragment is identical?

**Comment by poettering** [comment]
So I think there's a misunderstanding here: resolved stays with the same DNS server as long as it responds, and it will ask on all links in parallel if there's no better routing info available. In your case there is none (i.e. no ~. listed among your network interfaces), hence it will be asked on all interfaces at the same time.

resolved will retain the order of DNS servers configured when writing out resolve.conf, but the order between interfaces is not defined. 

There's a bug regarding not refreshing the resolv.conf file when a link goes away. That is addressed by #34817. 

Other than that I think there's nothing actionable here. It seems everything works as it should.

**Comment by XANi** [comment]
>resolved will retain the order of DNS servers configured when writing out resolve.conf, but the order between interfaces is not defined.

@poettering  Yes, that is entire problem. I connect via VPN (in this case OpenVPN). The VPN script adds another DNS servers to the list in result of
```
 gdbus introspect --system   --dest org.freedesktop.resolve1   --object-path /org/freedesktop/resolve1 |grep ' DNS = \['
      readonly a(iiay) DNS = [(2, 2, [0xc0, 0xa8, 0x01, 0x01]), (6, 2, [0x0a, 0x64, 0x65, 0x33]), (6, 2, [0x0a, 0x64, 0x65, 0x31]), (6, 2, [0x0a, 0x64, 0x65, 0x32])];
```

with id `2` being the wired connection and id `6` being the ones on VPN interface. Then systemd picks the order of those 2 groups (iface id 2 and 6) randomly (what's the purpose of it being random?) so sometimes it is working, sometimes it is not.

I *need* the ones added by OpenVPN to be first on the list else I'm not getting any internal IPs involved. Not sure how it was handled pre-systemd, my assumption is that it dumped it in reverse interface ID order because that would prefer DNS from newer (usually VPN) interface over older (already detected NIC) one. Of course "pick one with highest ID" is heuristic that still might break in some cases but it is far better than DNS server lottery...

**Comment by sgozdzicki-sgkomp** [comment]
Same problem on Ubuntu 24.04, exactly as @XANi describes.

**Comment by XANi** [comment]
Still a problem in systemd 259

There generally needs to be way of setting DNS server priority because (AFAIK) currently there is no method to tell systemd resolver to prefer one server over another 

For example, currently it for some ungodly reason thinks there are 2 default routes on my machine
```
Link 2 (eth0)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
       DNS Servers: 192.168.1.1
        DNS Domain: example.com
     Default Route: yes

Link 4 (tun0)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
       DNS Servers: 10.100.101.51 10.100.101.49 10.100.101.50
        DNS Domain: example2.com
     Default Route: yes

```
and in addition to that that hint isn't even useful; we don't push default GW to users for privacy reasons (we don't really want to VPN user's youtube traffic, we just push some routes for the actual corporate networks to go thru the VPN), we just use DNS to steer users into VPN addresses for our corporate stuff. Previously it worked because resolvconf kinda just preferred last interface added but systemd behaviour of just roll a dice on order just makes it broken
