### ISSUE TITLE
"systemctl reenable --now" does not stop/restart service

### ISSUE THREAD

**Issue by brad2014** [systemd/systemd#31541]
### systemd version the issue has been seen with

systemd-252-18.el9.0.1.rocky.x86_64

### Used distribution

Rocky 9

### Linux kernel version used

5.14.0-362.18.1.el9_3.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

After updating a template service unit file and executable, I expected `systemctl reenable --now` to  stop the service and remove the /etc/ links (as it would for `systemctl disable --now` currently) followed by reestablishing the links and starting the service (as it does for `systemctl enable --now` currently).  

### Unexpected behaviour you saw

After running `systemctl reenable --now`, no restart was observed (as would have happened with disable --now followed by enable --now).

### Steps to reproduce the problem

1. Install syncthing-linux-amd64-v1.27.1 in /opt/syncthing-linux-amd64-v1.27.1
```
# tar xgf syncthing-linux-amd64-v1.27.1.tgz -C /opt
# ln -sf /opt/syncthing-linux-amd64-v1.27.1/syncthing /usr/bin
# ln -sf "/opt/syncthing-linux-amd64-v1.27.1/etc/linux-systemd/system/syncthing@.service" /usr/lib/systemd/system/
# systemctl enable --now syncthing@brad
Created symlink /etc/systemd/system/syncthing@brad.service → /opt/syncthing-linux-amd64-v1.27.1/etc/linux-systemd/system/syncthing@.service.
Created symlink /etc/systemd/system/multi-user.target.wants/syncthing@brad.service → /opt/syncthing-linux-amd64-v1.27.1/etc/linux-systemd/system/syncthing@.service.
# lsof -n -P | grep /opt/syncthing | head -1
syncthing  143674                               brad  txt       REG              253,3   25839535   67141675 /opt/syncthing-linux-amd64-v1.27.1/syncthing
```

2. Later, upgrade to syncthing-linux-amd64-v1.27.3 in /opt/syncthing-linux-amd64-v1.27.3
```
# tar xgf syncthing-linux-amd64-v1.27.3.tgz -C /opt
# ln -sf /opt/syncthing-linux-amd64-v1.27.3/syncthing /usr/bin
# ln -sf "/opt/syncthing-linux-amd64-v1.27.3/etc/linux-systemd/system/syncthing@.service" /usr/lib/systemd/system/
# systemctl reenable --now syncthing@brad
Removed "/etc/systemd/system/multi-user.target.wants/syncthing@brad.service".
Removed "/etc/systemd/system/syncthing@brad.service".
Created symlink /etc/systemd/system/syncthing@brad.service → /opt/syncthing-linux-amd64-v1.27.1/etc/linux-systemd/system/syncthing@.service.
Created symlink /etc/systemd/system/multi-user.target.wants/syncthing@brad.service → /opt/syncthing-linux-amd64-v1.27.1/etc/linux-systemd/system/syncthing@.service.
# lsof -n -P | grep /opt/syncthing | head -1
syncthing  143674                               brad  txt       REG              253,3   25839535   67141675 /opt/syncthing-linux-amd64-v1.27.1/syncthing
```

Oops, we're still running the old executable!

## Workaround:

Explicitly disable and enable:
```
# systemctl disable --now syncthing@brad
# systemctl enable --now syncthing@brad
```

or reenable then restart

```
# systemctl reenable --now syncthing@brad
# systemctl restart --now syncthing@brad # workaround fault in reenable --now


### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

**Comment by poettering** [comment]
See 1baa0415ae612266c77016567390a8232a60d9db

**Comment by poettering** [comment]
Closing as already fixed in git main, hence.

**Comment by brad2014** [comment]
I'm looking at https://github.com/systemd/systemd/blob/836a06db0d07f8ae6058be24256695615f83ad0f/src/systemctl/systemctl-enable.c#L318C1-L320C1 (thank you @YHNdnzj) and it seems that the update causes --now to only work with enable, disable, and mask.  Was the functionality for reenable --now removed, or am I misunderstanding something?

**Comment by brad2014** [comment]
I think I see what is happening.  In v252, the --now flag is silently ignored for "systemctl reenable --now".  With the recent changes by @YHNdnzj, it looks to me like it is ignored with an err message (it does not fix the bug as described above, but it does make it apparent).  If that is the case, I'll file a separate feature request that the --now flag also work with reenable.

**Comment by YHNdnzj** [comment]
> I think I see what is happening. In v252, the --now flag is silently ignored for systemctl reenable --now (consistent with my original finding), returning (otherwise) successfully.

Yeah, it was never supported, hence bug -> RFE
