### ISSUE TITLE
On Fedora with systemd 256 dracut cannot write hooks to `/lib/dracut/hooks` during boot because `/lib` is `/usr/lib`, which is read-only with new ProtectSystem feature

### ISSUE THREAD

**Issue by AdamWill** [systemd/systemd#32511]
### systemd version the issue has been seen with

256

### Used distribution

Fedora Rawhide

### Linux kernel version used

6.9.0-0.tc5

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

System with systemd 256 should not show "Read-only file system" errors.

### Unexpected behaviour you saw

System with systemd 256 shows errors like `//lib/dracut/hooks/cmdline/00-parse-root.sh: line 28: /lib/dracut/hooks/initqueue/finished/devexists-\x2fdev\x2fdisk\x2fby-uuid\x2ff18e44fc-458a-483d-ae4f-fe5ee8ba011c.sh: Read-only file system`.

### Steps to reproduce the problem

Install Fedora Rawhide, update systemd to 256 from https://koji.fedoraproject.org/koji/buildinfo?buildID=2444479 , regenerate initramfs with `dracut -f`, reboot.

**Comment by AdamWill** [comment]
This is a bit fuzzy because there is *also* a `Failed to start systemd-modules-load.service - Load Kernel Modules.` error which points to a different problem (see https://github.com/systemd/systemd/issues/32508#issuecomment-2080063182 ). It's not clear whether either the read-only filesystem problem or the missing libkmod problem alone breaks the boot, since we encounter both at once. At a guess, though, I would expect *both* of them to break boot, so we need to fix both.

I'm going to try doing a scratch build of systemd patched so ProtectSystem default to off in initramfs environments, and see what happens with that.

**Comment by AdamWill** [comment]
Some testing suggests this bug *doesn't* prevent boot, at least of a simple default Fedora install in a VM; patching ProtectSystem to default to off for initramfses doesn't get the system booting again, but patching dracut to pull in the kmod library does get it booting again.

Surely the inability to write hooks must have some fairly significant consequences in some cases, though.

**Comment by poettering** [comment]
Fix dracut to not write around in /usr/ or turn off the feature in systemd if you need a quick workaround. This is not a bug in systemd but intended behaviour, really. What dracut is doing there is just wrong and should be fixed.

**Comment by poettering** [comment]
We probably should add a bigger note about this to NEWS however.

(And about the libkmod pitfall too I guess)

**Comment by keszybz** [comment]
This is fixed in dracut: https://github.com/dracut-ng/dracut-ng/commit/a45048b80c27ee5a45a380052a6d29ab1925f7f9

**Comment by guyru** [comment]
> Fix dracut to not write around in /usr/ or turn off the feature in systemd if you need a quick workaround.

I tried turning off the feature by overriding `ProtectSystem=no` in system.conf, regenerating the initramfs using dracut (and verifying my override file made it into the initramfs). However, it had no effect and the system still won't boot due to dracut being unable to write hooks.
