### ISSUE TITLE
delayed boot on UEFI tpm 1.2 system 

### ISSUE THREAD

**Issue by gene-git** [systemd/systemd#33077]
### systemd version the issue has been seen with

256 rc3

### Used distribution

Arch

### Linux kernel version used

6.9.2 and 6.10-rc1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Unexpected behaviour you saw

On booting we find tpm2.target (invoked via  sysinit.taget) stalls waiting on dev-tpmrm0.device.

There is no /dev/tpmrm0 on this machine (only /dev/tpm0) since tpm is 1.2 only. On machines with tpm 2 
everything works well.

Since the device is non-existent - it waits for the default  90 second timeout.
Since it happens in initramfs and after pivot root,  boot is delayed twice for a total of 3 minutes .

Boot loader is systemd-boot and machine is an older lenovo thinkpad W540 with UEFI and tpm 1.2.
The bios has 3 options for 'secure chip' - when set to disabled the problem is not seen.
When set to active or inactive - problem happens.

Reverting this commit :  4b3391158197e9158cc754e56bbeaf94e2fd8395 makes the problem go away
Reverted systemd build provided by Arch dev eworm,

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
n/a
```

**Comment by DaanDeMeyer** [comment]
@gene-git Can you attach the contents of /sys/kernel/security/tpm0/binary_bios_measurements on your system after booting?

**Comment by poettering** [comment]
(please generate a copy of that file via `cat /sys/kernel/security/tpm0/binary_bios_measurements > tpm12.blob` or so, i.e. use a simple tool such as "cat" to copy out the binar data it contains. it's a weird sysfs pseudo file, hence fancier tools typically don't work with it nicely)

**Comment by poettering** [comment]
if possible i'd like to permission to commit the dump to our git repo for CI/testing later, if that's OK?

**Comment by gene-git** [comment]
@poettering  - yes no problem to commit the dump.

[tpm12.blob.TGZ](https://github.com/systemd/systemd/files/15486668/tpm12.blob.TGZ)

**Comment by poettering** [comment]
@gene-git #33090 should be your fix. Any chance you can give that a whirl?

**Comment by eworm-de** [comment]
Want me to build a package? Or can you handle it yourself?

**Comment by gene-git** [comment]
@eworm-de thank you that would be helpful

**Comment by eworm-de** [comment]
Please install [systemd-256rc3-2.2](https://pkgbuild.com/~eworm/systemd-boot-delay/systemd-256rc3-2.2-x86_64.pkg.tar.zst) and give it a try...

**Comment by gene-git** [comment]
Thank you @eworm-de 

Confirm that works fine. 

Thanks everyone - closing as fixed by #33090

**Comment by malomehi** [comment]
> Please install [systemd-256rc3-2.2](https://pkgbuild.com/~eworm/systemd-boot-delay/systemd-256rc3-2.2-x86_64.pkg.tar.zst) and give it a try...

Where can I download the deb package for this version (amd64)?

**Comment by Safari77** [comment]
is this a different problem? Fedora 40 worked ok, Fedora 41 with newer systemd not. I don't use TPM for anything on my system. LUKS2 partitions do not mount on boot (except the root which is ZFS).  /sys/class/tpm and /sys/class/tpmrm are empty. Asus Pro WS W680-ACE.

```
Feb 27 20:50:47 kernel: efi: ACPI=0x741b7000 ACPI 2.0=0x741b7014 TPMFinalLog=0x7467b000 SMBIOS=0x75d2d000 SMBIOS 3.0=0x75d2c000 MEMATTR=0x6383c018 ESRT=0x68f59c18 RNG=0x74112c18 TPMEventLog=0x73fb9018 
Feb 27 20:50:47 kernel: ACPI: TPM2 0x0000000073FC3000 00004C (v04 ALASKA A M I    00000001 AMI  00000000)
Feb 27 20:50:47 kernel: ACPI: Reserving TPM2 table memory at [mem 0x73fc3000-0x73fc304b]
Feb 27 20:50:47 systemd[1]: systemd 256.11-1.fc41 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP -GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT +LIBARCHIVE)
Feb 27 20:50:47 systemd[1]: Expecting device dev-tpmrm0.device - /dev/tpmrm0...
Feb 27 20:50:47 systemd-sysusers[1863]: Creating user 'tss' (Account used for TPM access) with UID 59 and GID 59.
Feb 27 20:51:32 systemd[1]: dev-tpmrm0.device: Job dev-tpmrm0.device/start timed out.
Feb 27 20:51:32 systemd[1]: Timed out waiting for device dev-tpmrm0.device - /dev/tpmrm0.
Feb 27 20:51:32 systemd[1]: dev-tpmrm0.device: Job dev-tpmrm0.device/start failed with result 'timeout'.
Feb 27 20:51:32 systemd[1]: Reached target tpm2.target - Trusted Platform Module.
Feb 27 20:51:32 systemd[1]: systemd-pcrphase-initrd.service - TPM PCR Barrier (initrd) was skipped because of an unmet condition check (ConditionSecurity=measured-uki).
```

**Comment by Ghurir** [comment]
Has this been solved, because it is still happening on fedora 43:

```
01:15:13 pkexec: pam_systemd(polkit-1:session): Failed to check if /run/user/0/bus exists, ignoring: Permission denied
01:13:08 sudo: pam_systemd(sudo:session): Failed to check if /run/user/0/bus exists, ignoring: Permission denied
01:04:34 pkexec: pam_systemd(polkit-1:session): Failed to check if /run/user/0/bus exists, ignoring: Permission denied
00:18:11 sudo: pam_systemd(sudo:session): Failed to check if /run/user/0/bus exists, ignoring: Permission denied
00:14:22 systemd-xdg-aut: /home/ghurir/.config/autostart/nohup.out:9: Invalid section header '[57596:0308/235120.281407:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!'
00:14:22 gdm-session-wor: gkr-pam: unable to locate daemon control file
00:13:54 bluetoothd: Failed to set mode: Failed (0x03)
00:13:53 systemd: Timed out waiting for device dev-tpm0.device - /dev/tpm0.
00:13:10 kernel: Bluetooth: hci0: Reading supported features failed (-16)
00:13:09 systemd-udevd: /etc/udev/rules.d/65-brother-libsane-type1-inst.rules:14 Invalid key 'SYSFS'.
01:13:07 systemd: Timed out waiting for device dev-tpmrm0.device - /dev/tpmrm0.
01:12:22 systemd-udevd: /etc/udev/rules.d/65-brother-libsane-type1-inst.rules:14 Invalid key 'SYSFS'.
01:12:22 kernel: tpm_crb MSFT0101:00: probe with driver tpm_crb failed with error -16
01:12:22 kernel: x86/cpu: SGX disabled or unsupported by BIOS.
```
