### ISSUE TITLE
Since 256, suspend fails over 50% of the time: Freezing user space processes failed

### ISSUE THREAD

**Issue by mahkoh** [systemd/systemd#33626]
### systemd version the issue has been seen with

256

### Used distribution

Arch

### Linux kernel version used

6.10.0-rc6

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

`systemctl suspend` suspends the system

### Unexpected behaviour you saw

Suspending fails with

```
Jul 03 17:47:54 desk kernel: Freezing user space processes failed after 20.009 seconds (1 tasks refusing to freeze, wq_busy=0):
Jul 03 17:47:54 desk kernel: task:jay             state:R stack:0     pid:1550  tgid:1550  ppid:1533   flags:0x00024002
```

I originally reported this issue here: https://bugzilla.kernel.org/show_bug.cgi?id=219004

In there I already suspected that systemd might be involved since the issue started appearing immediately after upgrading systemd from 255 to 256 and knowing that systemd restarts itself without requiring a system reboot. I had not rebooted the system for around two weeks at that point.

I have now performed the following experiment which makes it look more likely that some behavior in systemd changed that has unintended consequences:

- I downgraded systemd, systemd-libs, and systemd-sysvcompat to 255 and tried to suspend 4 times in a row. They all succeeded.
- I upgraded to 256 and tried the same. 2 out of 4 attempts failed with the error above.
- I again downgraded to 255 and again all attempts succeeded.

The issue seems to happen with at least two stable 6.9.x kernels and also 6.10.0-rc6.

I've added logging to the kernel to see why the process cannot be frozen and it shows that the condition https://github.com/torvalds/linux/blob/795c58e4c7fc6163d8fb9f2baa86cfe898fa4b19/kernel/freezer.c#L112 is always true. More precisely, `p->on_rq == TASK_ON_RQ_QUEUED`.

Is it possible that systemd 256 has started doing something that would prevent a task with `p->on_rq == TASK_ON_RQ_QUEUED` during suspend to leave that state?

### Steps to reproduce the problem

You can try to install https://github.com/mahkoh/jay to reproduce. But the issue might be specific to my system.

**Comment by mahkoh** [comment]
I saw https://github.com/systemd/systemd/blob/a79b6dc0706dd5fe76ec56b3308b402c133ead23/NEWS#L92-L99 and adding that environment variable seems to have fixed the issue.

However, I'm not using any nvidia hardware nor any proprietary modules.

**Comment by mahkoh** [comment]
I've debugged this some more:

It is easy to reproduce the core of the issue as follows:

- Run https://github.com/mahkoh/jay on a separate VT.
- On the normal TTY, run `sleep 5; chvt 1` (or whatever the number of the normal VT is)
- Switch to the separate VT and run `echo 1 >/sys/fs/cgroup/user.slice/user-1000.slice/session-9.scope/cgroup.freeze` (or whatever the user ID and session ID of the separate VT are)

After 5 seconds you will get switched back to the normal VT and can inspect the state of the frozen session.

You can see that the `jay` process is now running at 100%. By using tracing, you can see that it is stuck in an infinite loop inside `get_signal` (in the kernel):

- Freezing the cgroup has set `task->jobctl |= JOBCTL_TRAP_FREEZE`
- Inside `get_signal`, this causes the logic to shortcut and to execute
  ```
  clear_thread_flag(TIF_SIGPENDING);
  schedule();
  ```
  in a loop.

However, `schedule` will wake up immediately since the `TIF_NOTIFY_SIGNAL` thread flag is set. This flag is set by io-uring because io-uring calls `task_work_add` with `TWA_SIGNAL` for the `jay` process with the following stack trace:

```
	io_req_normal_work_add
	io_poll_wake
	__wake_up_common
	__wake_up
	ep_poll_callback
	__wake_up_common
	__wake_up
	evdev_events
	input_to_handler
	input_pass_values.part.0
	input_event_dispose
	input_event
	hidinput_report_event
	hid_report_raw_event
	hid_input_report
	hid_irq_in
	__usb_hcd_giveback_urb
	usb_giveback_urb_bh
    [...]
```

The question is if the `task_work_add` call in io-uring must be guarded somehow or if `get_signal` should also clear the `TIF_NOTIFY_SIGNAL` flag. As far as I could tell, io-uring is the only user of `task_work_add` that uses the problematic `TWA_SIGNAL` argument.

@axboe maybe you have an idea?

Something similar might or might not happen in #33083 but they users in there might want to try similar debug steps as the ones I described at the start of the message.

**Comment by axboe** [comment]
I'm OOO for a few weeks, please ping Pavel Begunkov (@isilence which it GH won't link for some reason...)

**Comment by isilence** [comment]
Great report! I'll take a closer look, but @mahkoh pretty much debugged to the core of the issue.

**Comment by isilence** [comment]
@mahkoh, can you try the diff below?

Also, what's your full name / email? It'd accompany patches as a "suggested-by" tag in the commit message.

```diff
diff --git a/io_uring/io-wq.c b/io_uring/io-wq.c
index 913c92249522..b6e9b9819189 100644
--- a/io_uring/io-wq.c
+++ b/io_uring/io-wq.c
@@ -753,6 +753,8 @@ static inline bool io_should_retry_thread(long err)
 	 */
 	if (fatal_signal_pending(current))
 		return false;
+	if (current->jobctl & JOBCTL_TRAP_FREEZE)
+		return false;
 
 	switch (err) {
 	case -EAGAIN:
diff --git a/kernel/signal.c b/kernel/signal.c
index 1f9dd41c04be..790d60fcfff0 100644
--- a/kernel/signal.c
+++ b/kernel/signal.c
@@ -2694,6 +2694,10 @@ bool get_signal(struct ksignal *ksig)
 	try_to_freeze();
 
 relock:
+	clear_notify_signal();
+	if (unlikely(task_work_pending(current)))
+		task_work_run();
+
 	spin_lock_irq(&sighand->siglock);
 
 	/*
```

**Comment by mahkoh** [comment]
> @mahkoh, can you try the diff below?

That seems to have fixed the issue. I'll run it for a few more days to see if I notice anything odd.

> Also, what's your full name / email? It'd accompany patches as a "suggested-by" tag in the commit message.

`Julian Orth <ju.orth@gmail.com>`

**Comment by isilence** [comment]
> > @mahkoh, can you try the diff below?
> 
> That seems to have fixed the issue. I'll run it for a few more days to see if I notice anything odd.

Great, thanks. It also survived a beating with an improvised reproducer, but let know if you find anything

**Comment by callegar** [comment]
Is this expected to be an issue limited to machines with NVIDIA graphics? I am experiencing something very similar on a Celeron netbook with integrated graphics. What is "freezing user sessions" ultimately? The name of this feature searched on google does not appear to return anything significant (and its name is particularly unfortunate for web search). What are the implications of having it on or disabled (a pointer to the documentation is equally appreciated).

**Comment by YHNdnzj** [comment]
> What is "freezing user sessions" ultimately? ... What are the implications of having it on or disabled (a pointer to the documentation is equally appreciated).

A detailed explanation can be found at https://github.com/systemd/systemd/issues/33083#issuecomment-2191889790

**Comment by callegar** [comment]
Thanks for the clarification.

In the meantime, the `SYSTEMD_SLEEP_FREEZE_USER_SESSIONS=false` seems to work around the issue on my system (Intel, Intel graphics). Will wait a couple more days to see if this is really the case.

In the meantime, I would recommend not to underestimate the issue. *Failing suspend may not just end up in data loss but also in permanent hardware damage*. If you close the lid of a laptop and store it in a bag expecting the laptop to suspend and the laptop does not, in a short time it will reach crazy temperatures in that bag, that can permanently damage the screen. To make the matter worse, there are cheap laptops around (mine, for instance) that do not have a visible led providing visual feedback about successful suspending when the laptop lid is closed, so you really cannot check.

From what I understand:
1. The advantage of freezing the user session is significant only when you have encrypted homes and much more modest in other cases.
2. The fix being proposed is on the kernel side.

Because kernel and systemd updates are often not aligned, may I suggest that the freezing of user sessions is kept off by default for some more time on systems that do not use home encryption?

As a further recommendation, I think that the notes in https://github.com/systemd/systemd/issues/33083#issuecomment-2191889790 are also introduced in the systemd documentation (in case they are not yet there).

Finally, I have a question. I have read that the freezing of the user session may lead to the screen locking happening when the laptop is resumed rather than when it is put to sleep. Is this the case? If so, this may lead to the screen content being shown in an uncontrolled way (even if for a short time) by merely opening the lid of a sleeping laptop left on a desk.

**Comment by superm1** [comment]
There are reports of this exploding on AMD systems too specifically when KVM is in use.

**Comment by callegar** [comment]
In my case, the issue is both on Intel (N4120) and AMD. In neither case, I use KVM. On the low-powered Intel machine the issue is particularly frequent.

Is the drop in file for the environment configuration also needed as `/etc/systemd/system/systemd-hibernate.service.d/disable_freeze_user_session.conf` as suggested in the last link?

**Comment by YHNdnzj** [comment]
> Because kernel and systemd updates are often not aligned, may I suggest that the freezing of user sessions is kept off by default for some more time on systems that do not use home encryption?

We had some discussions about this, but overall the conclusion is leaving this enabled by default upstream is more favorable, which might drive kernel to eventually fixing this. But distros are always free to patch this out if they deem the adverse impact are more intolerable.

**Comment by callegar** [comment]
Thanks for this clarification. IMHO the worst issue is the overheating in the bag that may permanently ruin the hardware, so if the choice is left to downstream, I would at least clarify the situation more clearly (e.g., Manjaro assumes that the issue is limited to the 6.10RC series and not the stable ones and/or that it is fixed by some point release in the 256 systemd series).

A final question: how about the interaction between the session freezing and the screen locking? Can it be the case that the screen locking gets postponed so that opening the lid of a sleeping laptop may for an instant reveal the screen content?

**Comment by superm1** [comment]
> Thanks for this clarification. IMHO the worst issue is the overheating in the bag that may permanently ruin the hardware

Permanent hardware damage I see as more unlikely. The EC will monitor thermal sensors and will do an emergency power off.

To me the data loss from any running processes without warning is the worst. It's not at all obvious that this happens from running virtualization and will probably cause pointing fingers at a lot of other things until concluding it's virtualization + systemd change.

**Comment by callegar** [comment]
> The EC will monitor thermal sensors and will do an emergency power off.

I would not be confident in it. In my own experience, this is one of the most unreliable thing in modern PCs. Even when the emergency power off happens, it is often too late because of poor calibration and sensor placement. Often the power off will not happen at all, because the temperature remains just below threshold or will happen after a long time. Yes, it may save the CPU, battery and hd, but still result in screen damage, palmrest color variations, reduced battery health, trackpad popping out, etc. The board and some other components are monitored, everything else is not and longstanding heat in a configuration that is not meant for it (closed in a bag) where the heat distribution is totally different from what is probably tested by the manufacturer.

**Comment by isilence** [comment]
> We had some discussions about this, but overall the conclusion is leaving this enabled by default upstream is more favorable, which might drive kernel to eventually fixing this.

It's fixed upstream in the kernel, at least for the problem @mahkoh reproduced. IIRC it's in soon to be released 6.11, and was picked by stable. I don't remember the stable release cadence, need to check if they've already cut a kernel with it. Please let know if that still happens with the patch. Also, a quick note, it's much more likely to hit that problem with io_uring, but it wasn't an io_uring specific issue, potentially could've been seen without any io_uring.

**Comment by dmarkey** [comment]
FYI still getting a hard freeze on `6.11.0-rc7` while attempting s2idle with `qemu-system-x86_64 --accel kvm` running.

**Comment by Artim96** [comment]
I can also confirm, on a Ryzen 7040HX, suspend can still hard-freeze on 6.11. It might be a little more reliable now, but probably not by much. The only KVM-related thing that's running in the background are virtlockd.service and virtlogd.service.

**Comment by callegar** [comment]
Still seeing the issue on AMD Ryzen and Intel N4120 with 6.11.0 kernel.

**Comment by pvj** [comment]
I can confirm the same, with 6.11 version with AMD Ryzen (Manjaro, arch, xfce4) still occurs, while leaving qemu unattended. I have the same symptoms and logs as all commenters before nothing new to add in that regard. 

After an evening of trying to see if this has been reported I eventually found this obscure addition to the [Arch wiki](https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate#System_freezes_for_60_seconds_and_then_wakes_back_up_or_hangs_after_waking_up).

I was very surprised to get to the systemd repository since I would think the Arch stuff and the category of Power management might have other more obvious sources and teams responsible, still it was great that someone added a write-up in the troubleshoot section. 

Since this issue has been referenced not just on comm. forums but in a prominent article as well, systemd has now been a teeny bit dragged into this which is why I second the idea that systemd could prominently mark this in the changelogs (nothing yet about it in NEWS/257), or sync with the kernel and manjaro teams.

Thanks for providing the workaround until this is sorted out!

**Comment by Werkov** [comment]
Thanks for the report, @Gpinchon .

>  issue accross both OpenSUSE TW and Fedora 40 for the past month or so.

FTR, openSUSE TW has [not enabled the user.slice freezing](https://build.opensuse.org/projects/openSUSE:Factory/packages/systemd/files/5004-disable-session-freeze.patch?expand=1) yet (despite v256), AFAICS F40 doesn't do freezing neither (it has v255). Also, beware freezing != suspending.

> I don't get any system log during the "sleep" duration but I'm quite positive it's not sleeping...

You may try the workaround inverted, i.e. explicitly enabling freeze `SYSTEMD_SLEEP_FREEZE_USER_SESSIONS=true` on openSUSE TW. (But I wouldn't hold my breath since suspend should work regardless of freezing. dmesg should tell you whether kernel really reached the suspend state.)

**Comment by Gpinchon** [comment]
Hello @Werkov, sorry but I forgot to update on this issue.
I tried about every tricks in the book, even manually enabling session freeze on sleep to no avail.
The problem was in fact related to a kernel bug that appeared around version 6.10 and was fixed with version 6.11.5 with [commit f3eaf7c8b432c24dcab0fea12a8e1e17483a3a1d](https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.11.5)

**Comment by dimitris-personal** [comment]
@Gpinchon I've reproduced this (system unresponsive when attempting to resume) on Fedora 41 with 6.11.5-300.fc41.x86_64.  I have to apply the `SYSTEMD_SLEEP_FREEZE_USER_SESSIONS=false` workaround to avoid this.

**Comment by Gpinchon** [comment]
> @Gpinchon I've reproduced this (system unresponsive when attempting to resume) on Fedora 41 with 6.11.5-300.fc41.x86_64. I have to apply the `SYSTEMD_SLEEP_FREEZE_USER_SESSIONS=false` workaround [as described here](https://bugzilla.redhat.com/show_bug.cgi?id=2321268) to avoid this.

I know I had issues with freezes when coming out of hibernation or S3 with my device (Lenovo Yoga Pro 7 14APH8) and tried that to no avail, I abandonned the idea of activating hibernation after s2idle was fixed with kernel 6.11.5 sorry 🤷‍♂️

**Comment by bluca** [comment]
There are two freezing issues, this is more about the io-uring one which has already been fixed and backported to 6.11, so we can close this one.
The KVM one is tracked at https://github.com/systemd/systemd/issues/33083 and a kernel fix has been just posted today, and can confirm it fixes the problem

**Comment by mahkoh** [comment]
Ironically there now seems to be a different bug (unrelated to systemd) that is fixed by re-enabling userspace freezing: https://gitlab.freedesktop.org/drm/amd/-/issues/4178

**Comment by mahrud** [comment]
> Great, thanks. It also survived a beating with an improvised reproducer, but let know if you find anything

@isilence could you point me to your improvised reproducer? I think I have a similar issue (#37590) but currently can't reproduce it.

**Comment by isilence** [comment]
@mahrud, I can't find it, unfortunately, but it should've been trying to freeze/check/unfreeze/repeat while running some task_work intensive job. Some fio/t/io_uring doing O_DIRECT reads against a block device / nvme, should do the trick.

From a quick glance it doesn't look like the same issue. Do you see any task unexpectedly burning 100% of CPU after the freezing attempt? The problem we had before led to a busy loop, but from your logs the tasks are sleeping waiting for a page.

**Comment by xuancong84** [comment]
No need version 256, I am at version 249, experience the problem 100% of the time whenever an IDE has opened a project on a network mounted folder, see #38304 . I have already figured out the cause.
