### ISSUE TITLE
systemd-resolved returns synthesized DNS records for the local host

### ISSUE THREAD

**Issue by tomhughes** [systemd/systemd#34897]
### systemd version the issue has been seen with

256

### Used distribution

Fedora 41

### Linux kernel version used

6.11.5-300.fc41.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

When resolving the local host systemd-resolved should return the address in the DNS and nothing else.

### Unexpected behaviour you saw

When resolving the local host systemd-resolved returned DNS records and also every other IP address assigned to a local interface.

### Steps to reproduce the problem

After upgrading to Fedora 41 (and hence systemd 256) this is what I see:

```
bericote [~] % resolvectl query bericote.compton.nu           
bericote.compton.nu: 172.16.15.2               -- link: br0
                     10.88.0.1                 -- link: podman0
                     2001:8b0:bd:1:1881:14ff:fe46:3cc7 -- link: br0
                     fd96:7c2e:b8d2:bf65::1    -- link: podman0
                     fe80::1881:14ff:fe46:3cc7%2 -- link: br0
                     fe80::bec7:46ff:fe9a:cf7c%4 -- link: wlp6s0
                     fe80::24b9:eff:fef3:5f08%5 -- link: podman0
                     fe80::8453:1eff:feb0:970f%6 -- link: veth0

-- Information acquired via protocol DNS in 516us.
-- Data is authenticated: yes; Data was acquired via local or encrypted transport: yes
-- Data from: synthetic
```

Despite the claim that the data comes from DNS only `172.16.15.2` and `2001:8b0:bd:1:1881:14ff:fe46:3cc7` are actually present in the DNS.

It appears the default value of `SYSTEMD_RESOLVED_SYNTHESIZE_HOSTNAME` has changed from false to true in https://github.com/systemd/systemd/pull/31621/commits/6399be223b73ce520654242ad08de387b08b738a and explicitly setting it to false in `systemd-resolved.service` fixes this.

If you're wondering why this is a problem it's because my firefox happily picked one of the link local addresses to use and then apache 403ed because that address was not in it's ACL list.

**Comment by pemensik** [comment]
I think the main problem is manual page for systemd-resovled nor resolved.conf does not contain any information, how to disable such synthesis. From manual page(s) it seems impossible. It is mentioned in ENVIRONMENT.md, but that is part of systemd package. Not where user would find it.

**Comment by tomhughes** [comment]
As far as I could see there's nothing in NEWS either.

**Comment by poettering** [comment]
This behaviour is clearly documented in the man page and the addresses returned are sorted by scope, i.e. link-local comes last.

Moroever the resolvectl output explicitly tells you that the data is synthetic.

The env var *is* documented, but we consider it a bit hackish and hence its in ENVIRONMENT.md and not on the main man page 

I am not seeing anything actionable here?

**Comment by tomhughes** [comment]
I've just been doing a bit more digging and I think that part of the problem is that glibc is sometimes resorting the address. Here's a different machine with `resolvectl`:

```
gosford.compton.nu: 172.16.15.1                -- link: br0
                    172.16.15.1                -- link: wg0
                    217.169.17.27              -- link: ppp0
                    2001:8b0:bd:1:6cd2:7aff:fea1:9164 -- link: br0
                    2001:8b0:bd:1:21c:c0ff:fede:937a -- link: wg0
                    2001:8b0:bd:1:e2d5:5eff:fee7:6698 -- link: ppp0
                    fe80::e2d5:5eff:fee7:6698%2 -- link: enp1s0
                    fe80::20e:8eff:fe1f:4239%4 -- link: wlp5s0
                    fe80::807a:5eff:fe76:6e55%5 -- link: br0
                    fe80::edba:c5d6:4149:e12c%7 -- link: ppp0

-- Information acquired via protocol DNS in 6.2ms.
-- Data is authenticated: yes; Data was acquired via local or encrypted transport: yes
-- Data from: synthetic
```

and then using `getent ahosts` to do a `getaddrinfo` query:

```
gosford [~] % getent ahosts gosford.compton.nu
fe80::e2d5:5eff:fee7:6698%2 STREAM gosford.compton.nu
fe80::e2d5:5eff:fee7:6698%2 DGRAM  
fe80::e2d5:5eff:fee7:6698%2 RAW    
fe80::20e:8eff:fe1f:4239%4 STREAM 
fe80::20e:8eff:fe1f:4239%4 DGRAM  
fe80::20e:8eff:fe1f:4239%4 RAW    
fe80::807a:5eff:fe76:6e55%5 STREAM 
fe80::807a:5eff:fe76:6e55%5 DGRAM  
fe80::807a:5eff:fe76:6e55%5 RAW    
2001:8b0:bd:1:6cd2:7aff:fea1:9164 STREAM 
2001:8b0:bd:1:6cd2:7aff:fea1:9164 DGRAM  
2001:8b0:bd:1:6cd2:7aff:fea1:9164 RAW    
2001:8b0:bd:1:21c:c0ff:fede:937a STREAM 
2001:8b0:bd:1:21c:c0ff:fede:937a DGRAM  
2001:8b0:bd:1:21c:c0ff:fede:937a RAW    
2001:8b0:bd:1:e2d5:5eff:fee7:6698 STREAM 
2001:8b0:bd:1:e2d5:5eff:fee7:6698 DGRAM  
2001:8b0:bd:1:e2d5:5eff:fee7:6698 RAW    
fe80::edba:c5d6:4149:e12c%7 STREAM 
fe80::edba:c5d6:4149:e12c%7 DGRAM  
fe80::edba:c5d6:4149:e12c%7 RAW    
172.16.15.1     STREAM 
172.16.15.1     DGRAM  
172.16.15.1     RAW    
172.16.15.1     STREAM 
172.16.15.1     DGRAM  
172.16.15.1     RAW    
217.169.17.27   STREAM 
217.169.17.27   DGRAM  
217.169.17.27   RAW    
```

which seems to have moved host of the link local addresses to the front of the list.

**Comment by pemensik** [comment]
The order of DNS records returned is not supposed to be fixed or mean anything specific. A good cache should rotate returned records for each query. Yes, man systemd-resolved(8) has SYNTHETIC RECORDS section, which describes this behaviour. It is not documented *why* these synthetized records are preferred over real responses from the network. What does it fix, when network has positive answers for such queries?

Link local ipv6 cannot be received via DNS with interface index included. AAAA record encodes just sin6_addr part of ``struct sockaddr_in6``. It may confuse some programs.

I confirm my rawhide instance returns fe80::* first, followed by ipv4 address. When *resolve* and *myhostname* plugins are used, ipv6 link-local is listed first. With dns plugin ipv4 is listed first instead.

```python
import socket
for i in socket.getaddrinfo(socket.gethostname(), 0): print(i)
```

Matches the order which ``getent ahosts $HOSTNAME`` returns with ``glibc-2.40.9000-7.fc42.x86_64``. IPv4 private address is listed *after* link-local ipv6.

```
# rpm -q systemd-resolved
systemd-resolved-256.7-1.fc42.x86_64

# getent ahosts -s resolve $HOSTNAME
fe80::7c85:92ff:fe43:8871%2 STREAM rawhide
fe80::7c85:92ff:fe43:8871%2 DGRAM  
fe80::7c85:92ff:fe43:8871%2 RAW    
192.168.122.184 STREAM 
192.168.122.184 DGRAM  
192.168.122.184 RAW    

# getent ahosts -s resolve $HOSTNAME
fe80::7c85:92ff:fe43:8871%2 STREAM rawhide
fe80::7c85:92ff:fe43:8871%2 DGRAM  
fe80::7c85:92ff:fe43:8871%2 RAW    
192.168.122.184 STREAM 
192.168.122.184 DGRAM  
192.168.122.184 RAW    

# getent ahosts -s dns $HOSTNAME
192.168.122.184 STREAM rawhide
192.168.122.184 DGRAM  
192.168.122.184 RAW    
fe80::7c85:92ff:fe43:8871 STREAM 
fe80::7c85:92ff:fe43:8871 DGRAM  
fe80::7c85:92ff:fe43:8871 RAW    

# dig +short $HOSTNAME @192.168.122.1 
192.168.122.184
```

It seems the combination used with glibc does not work as advertised in the man page. Which does not explain why it does not just cache network response and generates own response without asking. Or why there this behaviour should not be configurable a normal way.

**Comment by pemensik** [comment]
Man page says: 
> The local, configured hostname is resolved to all locally configured IP addresses ordered by their scope, or — if none are  configured — the IPv4 address 127.0.0.2 (which is on the local loopback interface) and the IPv6 address ::1 (which is the  local host).

The above reports state that is not true. Still this is marked with *not-a-bug* tag.

The second part is why this is even done and why simple documented way to disable the behaviour is not in a man page. That part might be to discussion, whether or not this is desired feature, not a bug.

But the minimal part reporting wrong order could not be considered a feature. Lennart himself [posted](https://github.com/systemd/systemd/issues/34897#issuecomment-2438350766) link-locals should be last, yet they are not. I have to say I don't understand.

**Comment by salahcoronya** [comment]
This also prevents from discovering their FQDN, which can cause problem. In my case, OpenLDAP / slapd stopped working because of this synthesis. OpenLDAP was configured to listen on all interface, but it stopped being able to start because it could no longer discover the canonical hostname and match it to olcServerID (used for mirror and multi-provider setups) anymore. You'll see this problem if the the machine hostname is bare (just "machine"), the client is listed in DNS (machine,example.com), there's a search domain for example.com, and you try to run "hostname --fqdn". With synthesis it just displays the hostname, without synthesis the full FQDN is returned as expected.

**Comment by gucci-on-fleek** [comment]
This also makes any queries about the system's hostname for non-`A`/`AAAA` rrtypes (`MX`, `TXT`, etc.) return an empty answer, even if the DNS contains records for those. Among other issues, this means that it's impossible to send email to the hostname of the system:

```console
$ resolvectl --version
systemd 256 (256.9-2.fc41)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP -GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT +LIBARCHIVE

$ resolvectl status
Global
         Protocols: LLMNR=resolve -mDNS +DNSOverTLS DNSSEC=yes/supported
  resolv.conf mode: stub
Current DNS Server: 1.1.1.1
       DNS Servers: 1.1.1.1 1.0.0.1 2606:4700:4700::1111 2606:4700:4700::1001

Link 2 (ens3)
    Current Scopes: LLMNR/IPv4 LLMNR/IPv6
         Protocols: -DefaultRoute LLMNR=resolve -mDNS +DNSOverTLS DNSSEC=yes/supported

$ cat /etc/hostname
maxchernoff.ca

$ resolvectl query --type=mx maxchernoff.ca
maxchernoff.ca: resolve call failed: Name 'maxchernoff.ca' does not have any RR of the requested type

$ busybox nslookup -type=mx maxchernoff.ca
Server:		127.0.0.53
Address:	127.0.0.53:53

$ printf '[Service]\nEnvironment=SYSTEMD_RESOLVED_SYNTHESIZE_HOSTNAME=0\n' | sudo tee /etc/systemd/system/systemd-resolved.service.d/override.conf
[...]

$ sudo systemctl daemon-reload && sudo systemctl restart systemd-resolved.service

$ resolvectl query --type=mx maxchernoff.ca
maxchernoff.ca IN MX 10 aspmx1.migadu.com                   -- link: ens3
maxchernoff.ca IN MX 20 aspmx2.migadu.com                   -- link: ens3

-- Information acquired via protocol DNS in 22.8ms.
-- Data is authenticated: yes; Data was acquired via local or encrypted transport: yes
-- Data from: network

$ busybox nslookup -type=mx maxchernoff.ca
Server:		127.0.0.53
Address:	127.0.0.53:53

Non-authoritative answer:
maxchernoff.ca	mail exchanger = 10 aspmx1.migadu.com
maxchernoff.ca	mail exchanger = 20 aspmx2.migadu.com
```

Even if this is working as documented, I'd argue that it's both unexpected and undesirable for `MX` and `TXT` queries about the local system to fail.

**Comment by pemensik** [comment]
Note: resolve plugin can have synthesis disabled by SYSTEMD_NSS_RESOLVE_SYNTHESIZE environment. Its nice this can be toggled per request. myhostname plugin cannot disable it like that, at least not documented. But via those plugins at least other DNS records types would not be affected, like mentioned MX record.

**Comment by ekohl** [comment]
In my setup I expose systemd-resolved as a recursor to my local network. When clients query the address it returns all addresses on AAAA, including link local addresses. Since my router has multiple networks it also includes link local addresses that clients can never reach.

```console
$ dig @192.168.1.1 redacted.example.com aaaa +short | grep '^f[de]'
fdf4:cf85:cd85:f6ed::1
fe80::fcac:5bff:fe0e:bb28
fe80::689c:1ff:fea4:f081
fe80::fcac:5bff:fe0e:bb28
fe80::8859:77ff:fec5:a5f0
fe80::f43e:ccff:fe69:7961
fe80::fc54:ff:fe5d:1acc
fe80::85b1:c261:d3a4:1c82
```

Note the fdf4 address is from a podman isolated network that clients should never be able to reach.

**Comment by mozzieongit** [comment]
Bringing some attention back to this, @poettering, as I have had multiple issues with running DNS nameserver software on systems with resolved now.

Earlier you said the following, but might have missed the follow-ups:

> This behaviour is clearly documented in the man page and the addresses returned are sorted by scope, i.e. link-local comes last.
>
> Moroever the resolvectl output explicitly tells you that the data is synthetic.

While, true, it is documented, this (ordering and that it is synthetic) is only the case when using systemd tools like resolvectl.  However, as @pemensik already described [above](https://github.com/systemd/systemd/issues/34897#issuecomment-2440181304), DNS records are not supposed to be in fixed order or have any meaning in their ordering. This means that any software querying the DNS through their local resolver (so resolved) can pick any address at random.

He also described accurately that IPv6 link-local addresses cannot be correctly represented in the DNS, as they require the scope ID or interface to be usable. Therefore, returning link-local addresses to software querying their local resolver to resolve a name in the DNS is invalid and a bug in that regard.

> The env var _is_ documented, but we consider it a bit hackish and hence its in ENVIRONMENT.md and not on the main man page
>
> I am not seeing anything actionable here?

I see multiple possible actions (not exclusive):
1. Disable the automatic synthesis, by default;
2. Remove link-local addresses from the automatic synthesis, by default;
3. Make the synthesis configurable (without any hacks) and the configuration option clearly documented

**Comment by poettering** [comment]
if someone preps a patch that suppresses synthesis of responses with link-local addresses from the replies sent via the local dns stub listener (but keeps them for the dbus+varlink mechanism, where the ifindex can be propagated), then that should be something we could merge. but needs a patch.

(and of course, it's a bit of a mess that the issue of link-local addresses in DNS stub responses is conflated here with the issue whether we should synthesize or not)

**Comment by poettering** [comment]
> $ cat /etc/hostname
> maxchernoff.ca

So this is always going to be a bit messy, because the linux kernel isn't really set up for setting fqdns are kernel host names. I know people do that, but note that the kernel size limit for hostnames is 64 (i.e. as appropriate for a DNS label maximum of 63), not 255 (as would be appropriate for DNS domain name maxiums, i.e. fqdns). I'll prep a patch clarfiying that further in the documentation of hostname(5)

**Comment by pemensik** [comment]
> So this is always going to be a bit messy, because the linux kernel isn't really set up for setting fqdns are kernel host names. I know people do that, but note that the kernel size limit for hostnames is 64 (i.e. as appropriate for a DNS label maximum of 63), not 255 (as would be appropriate for DNS domain name maxiums, i.e. fqdns). I'll prep a patch clarfiying that further in the documentation of hostname(5)

It does not exactly help systemd prevents fetching FQDN from relative hostname configured and search domain(s), where different limit exists (bind-utils have fixed limit on number of search domains for example).

Removing only link-local addresses won't help in this matter. What would help instead is fetching real answer from configured servers first and caching it. Synthetize own response only if network did not deliver any or failed when trying to do that.

Similar to what default is in CentOS: myhostname is used only after dns plugin there and this problem is not present there.

**Comment by dawagner** [comment]
I second @gucci-on-fleek on this:

> Even if this is working as documented, I'd argue that it's both unexpected and undesirable for MX and TXT queries about the local system to fail.

What would be the downside of handling non-address RRs in the "regular" way?

I seem to have an extended version of the problem as laid out so far and `SYSTEMD_RESOLVED_SYNTHESIZE_HOSTNAME=0` doesn't fix it. I'm using systemd 257.13 on debian trixie (should I report to debian instead, given that, IIRC, you have a policy of only support the last 2 major releases ?)

- my hostname is foo
- my fqdn is foo.example.com or bar.example.com (issue reproduced with either)
- I either have example.com as search domain or not (issue reproduced with either)
- I have my fqdn (in addition to my hostname) in /etc/hosts, associated with my public IP (e.g. `1.2.3.4 bar.example.com foo`)

Under those conditions, `resolvectl query -t SSHFP $fqdn` fails.

**That seems to contradict the man page** that says:

> systemd-resolved synthesizes DNS resource records (RRs) for the following cases:
> 
> - The local, configured hostname is resolved to all locally configured IP addresses ordered by their scope, or — if none are configured — the IPv4 address 127.0.0.2 (which is on the local loopback interface) and the IPv6 address
>            ::1 (which is the local host).
> [stuff about localhost, _gateway, _outbound, etc]
> - The mappings defined in /etc/hosts are resolved to their configured addresses and back, **but they will not affect lookups for non-address types (like MX).** Support for /etc/hosts may be disabled with ReadEtcHosts=no, see
>            resolved.conf(5).

(emphasis mine)

Setting `ReadEtcHosts=no` works but that seems like a nuclear option to me. For now, I'll just remove the fqdn from /etc/hosts (it works around the issue) and see if it breaks anything.

**Comment by SaphireLattice** [comment]
Well that was a fun hour of trying to debug why SPF milter happily reports "None" despite the TXT record allowing only the MX. I thought it was tailscale doing it but upon further inspection it was the systemd-resolved synthetic records, as `dig`ing at tailscale happily reports correct information. And `resolvectl query -t TXT $FQDN` report that "$FQDN does not have any RR of the requested type". It seems that even the new `systemd.rr` won't help as those limit records types that they allows to set?

For the record I have the hostname set to FQDN (roughly `foo.example.com`), and DNS records set for that FQDN, with search domains including `example.com`.

I'm not sure how this kind of behavior is desirable? Unless this is a bug that's been fixed since version 259, and I'm commenting on the wrong issue.
