### ISSUE TITLE
networkd bridge is down after boot

### ISSUE THREAD

**Issue by zabbal** [systemd/systemd#425]
I've created bridge to use for inter-container communication - /etc/systemd/network/internalbridge1.netdev:
[NetDev]
Name=ibr1
Kind=bridge

The bridge appear in 'brctl show' properly, lxc containers with veth network type which uses this bridge (ip.network.link = ibr1) work fine BUT only after I manually set the bridge interface to UP state by issuing 'ip link set ibr1 up' command.

I went through systemd-networkd manual but could not find an option to get the netdev to be always up by default and whatever automatic detection is there to bring it up when necessary is obviously failing in this case.

Tested with 219-7ubuntu6 on ubuntu 15.04 x86_64. The systemd-networkd status is also highly confusing:
systemctl status systemd-networkd
● systemd-networkd.service - Network Service
   Loaded: loaded (/lib/systemd/system/systemd-networkd.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Tue 2015-06-30 15:29:31 CEST; 9min ago
     Docs: man:systemd-networkd.service(8)
  Process: 9908 ExecStart=/lib/systemd/systemd-networkd (code=exited, status=0/SUCCESS)
 Main PID: 9908 (code=exited, status=0/SUCCESS)
   Status: "Shutting down..."

Jun 30 15:28:46 xnode systemd[1]: Starting Network Service...
Jun 30 15:28:46 xnode systemd-networkd[9908]: ibr1            : netdev ready
Jun 30 15:28:46 xnode systemd-networkd[9908]: Enumeration completed
Jun 30 15:28:46 xnode systemd[1]: Started Network Service.
Jun 30 15:28:46 xnode systemd-networkd[9908]: ibr1            : lost carrier
Jun 30 15:28:46 xnode systemd-networkd[9908]: ibr1            : gained carrier
Jun 30 15:28:46 xnode systemd-networkd[9908]: ibr1            : netdev exists, using existing without changing its parameters

Btw, networkctl show those interfaces as 'degraded' which seems to be misleading - after manually bringing bridge interface up I can ping one container from the other just fine. Would be nice if there were a way to get some meaningful explanation from networkctl on why exactly it consider interfaces to be degraded - so we could judge if it's a bug inside networkctl or smth is indeed wrong with network stack.

**Comment by poettering** [comment]
@teg?

**Comment by joehillen** [comment]
I'm having this issue too with my previously working LXC network bridge on systemd 224 on Arch.

```
➤  sudo systemctl status systemd-networkd
● systemd-networkd.service - Network Service
   Loaded: loaded (/usr/lib/systemd/system/systemd-networkd.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2015-08-10 14:46:25 PDT; 6min ago
     Docs: man:systemd-networkd.service(8)
 Main PID: 17759 (systemd-network)
   Status: "Processing requests..."
   Memory: 356.0K
      CPU: 15ms
   CGroup: /system.slice/systemd-networkd.service
           └─17759 /usr/lib/systemd/systemd-networkd

Aug 10 14:46:50 shadow systemd-networkd[17759]: could not add new link: No such device
Aug 10 14:46:59 shadow systemd-networkd[17759]: vethL2A98C: Gained carrier
Aug 10 14:47:45 shadow systemd-networkd[17759]: vethL2A98C: Lost carrier
Aug 10 14:47:45 shadow systemd-networkd[17759]: vethL2A98C: Gained carrier
Aug 10 14:50:36 shadow systemd-networkd[17759]: vethL2A98C: Lost carrier
Aug 10 14:50:36 shadow systemd-networkd[17759]: vethL2A98C: Could not find udev device: No such device
Aug 10 14:50:36 shadow systemd-networkd[17759]: could not add new link: No such device
Aug 10 14:50:53 shadow systemd-networkd[17759]: vethC2YAU4: Gained carrier
Aug 10 14:51:39 shadow systemd-networkd[17759]: vethC2YAU4: Lost carrier
Aug 10 14:51:39 shadow systemd-networkd[17759]: vethC2YAU4: Gained carrier
```

**Comment by poettering** [comment]
Let me get this right: this is networkd running on the host, not in that LXC cotnainer?

**Comment by joehillen** [comment]
@poettering Yes, this is networkd on the host. systemd is _not_ running in the LXC container.

**Comment by zabbal** [comment]
I second that - my logs are from systemd-networkd of the host as well. One potential workaround would be to allow user to manually set bridge interface to be always up regardless of the other interface which are part of it.

**Comment by zabbal** [comment]
While this being investigated I've created following unit which works as a workaround for me:

[Unit]
Description=Fix dumb bug in systemd which prevents bridge interface from being up.
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/sbin/ip link set ibr1 up
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target

Running "systemctl enable fix-systemd-bug.service" allowed communication between containers but I'm still looking forward for the time when I'll be able to disable this unit and delete .service file.

**Comment by joehillen** [comment]
My LXC bridge networking issues were miraculously fixed as of v226, with no changes on my part, so this issue can be closed as far as I am concerned.

**Comment by zabbal** [comment]
good to know, will re-test once this version hits distributions

**Comment by mjevans** [comment]
I believe I've actually run across this while trying to setup a bridge to test on my own; it doesn't work.

My systemd version is 228 (part of an ArchLinux rolling release installation).

Here are approximations of my current configuration files.

/etc/systemd/network/brtest.netdev

```
[Match]
Host=vmhostname

[NetDev]
Description=Bridge for testing DHCP/DNS/etc
Name=brtest
Kind=bridge
MTUBytes=9000
MACAddress=dd:dd:dd:dd:dd:dd
```

/etc/systemd/network/brtest.network

```
[Match]
Name=brtest

[Link]
MACAddress=dd:dd:dd:dd:dd:dd
MTUBytes=9000

[Network]
DHCP=no
Address=10.0.0.1/8
```

The bridge is created, and has the correct mtu size, but does not come up.

I wanted to re-test this but am having a difficult time of finding documentation on how to bring down /just/ the brtest bridge instead of the whole system.

**Comment by mjevans** [comment]
I still need to troubleshoot why my network MTU isn't as I set, however SystemD 229 appears to bring the bridge up, with the segment down (due to no other ports) and then up once a client starts.

**Comment by reinderien** [comment]
I can still reproduce this on systemd 237, Ubuntu Server 18.04. After having restarted the service, my two NIC netdevs, two VLAN netdevs, and all networks are up, but the bridge netdev is down.
