### ISSUE TITLE
systemd-journal-remote ignores rotation rules

### ISSUE THREAD

**Issue by rkrzr** [systemd/systemd#5242]
### Submission type

  - [x] Bug report

### systemd version the issue has been seen with

v229

### Used distribution

Ubuntu 16.04

### In case of bug report: Expected behaviour you didn't see

Remote logs were not being rotated after 2GB

### In case of bug report: Unexpected behaviour you saw

Remote logs were already being rotated every 128MB.

The server was configured with `/etc/systemd/journald.conf` containing:

```
SystemMaxFileSize=2G
RuntimeMaxFileSize=2G
```

These settings were respected by the local `systemd-journald` process, but *not* by the `systemd-journal-remote` process.
Since `man systemd-journal-remote` states that "If necessary (journal files over size, or corrupted), journal files will be rotated following normal journald rules." I would assume that it should be possible to configure the size before rotation.

### In case of bug report: Steps to reproduce the problem

1. Run `systemd-journal-remote` on one machine
2. Upload logs with `systemd-journal-upload` from one or more other machines
3. Observe that the logs will get rotated after 128MB.

**Comment by andrew-david-smith** [comment]
Also having this problem, although have tested on Arch aswell as ubuntu 16.04.

As above `systemd-journald` rotates as expected but nothing seems to work for `systemd-journal-remote`.

Config is placed in `/etc/systemd/journald.conf` as above and contains minimal config like above.

**Comment by tominglis** [comment]
I am also affected by this issue on Ubuntu 16.04. It would be great to get a fix for it.

**Comment by arianvp** [comment]
I could have a stab at this issue with some pointers where to look.

**Comment by MartinVerges** [comment]
same problem here, please fix systemd-journal-remote

**Comment by tominglis** [comment]
@arianvp Thanks for offering to help with this - have you had a chance to look yet, and is there anything you need to know beyond what's in this issue?

**Comment by arianvp** [comment]
Haven't had the time to dig into the code yet. Gonna do that this weekend. I'm at all-systems-go.io this week. If anybody else is there as well perhaps we can hack on it together.

**Comment by arianvp** [comment]
I can't really find anything `journal-remote` specific that would cause this problem.

It basically opens a handle to the journal and writes to it...

So this seems to be an issue in journald itself I think?

**Comment by tominglis** [comment]
OK, how do we get this issue relabeled to journald?

I'm really keen to get to the bottom of this, but probably can't help much myself, other than testing any solution.

**Comment by tominglis** [comment]
@poettering Is this issue also fixed by:

https://github.com/systemd/systemd/pull/8222

**Comment by cflee** [comment]
systemd-journal-remote seems to not read journald.conf at all, only its own journal-remote.conf that doesn't have these rotation related config directives.

https://github.com/systemd/systemd/blob/1e5d2d656420d0e755dbcf72aeba3c3aba54e956/src/journal-remote/journal-remote-main.c#L753-L767

That might be because much of the rotation logic, especially the space calculation logic, only exists in various parts of journald and journalctl, though per #2376 journalctl doesn't quite work on remote dir too for other reasons.

When opening the journal files, the default 'metrics' and hence rotation configs are used, since the metrics are all set to -1:

https://github.com/systemd/systemd/blob/1e5d2d656420d0e755dbcf72aeba3c3aba54e956/src/journal-remote/journal-remote-write.c#L25

https://github.com/systemd/systemd/blob/1e5d2d656420d0e755dbcf72aeba3c3aba54e956/src/journal-remote/journal-remote.c#L66-L71

Therefore debug output shows: `Fixed min_use=1.0M max_use=4.0G max_size=128.0M min_size=512.0K keep_free=4.0G n_max_files=100`

On the actual journal writing code paths from journal-remote, it seems that only the default values for `SystemMaxFileSize`/`max_size` in `journal_file_allocate()` via `journal_file_append_entry()`, and perhaps `MaxFileSec`/`max_file_usec` in `journal_file_rotate_suggested()`, are used during the actual writes.

https://github.com/systemd/systemd/blob/1e5d2d656420d0e755dbcf72aeba3c3aba54e956/src/journal-remote/journal-remote-write.c#L71-L81

So I think the main issue is not in journald, but that journal-remote currently doesn't have any way to configure the MaxFileSize bit on the journal writer. The manpage is therefore technically correct in that the normal journald rules are followed, just without being able to configure the parameters for the rules...

**Comment by samuraiii** [comment]
Hello,
is there any chance on getting this fixed after 2 years after report?
S

**Comment by bjoe2k4** [comment]
Just ran into this issue, too. Very annoying.

**Comment by caruccio** [comment]
2020 and still not rotating. Would be nice to have this feature or any hack someone could come up with.

**Comment by topimiettinen** [comment]
Maybe systemd-tmpfiles could provide a generic method to rotate files, this could then be used in many other cases besides journald and in addition to logging, it could be used for backups (keep the old file instead of making a new zero size file). Finding the correct process so that it can be signaled to reopen the log etc. files could be a problem though.

**Comment by mdunnio** [comment]
I'm running into this problem as well. Is there anything we can do to help push this forward?

**Comment by jmontag43** [comment]
I'm also running into this issue.

**Comment by Insolita** [comment]
2021 and it is still open... :-(

**Comment by trogper** [comment]
Has anyone figured a workaround at least?

**Comment by MartinVerges** [comment]
Yes, not using it and choosing a better solution. Unfortunately it looks like no one cares about that.

**Comment by evdh-nl** [comment]
Might help someone; a workaround that currently works for me; nightly cronjob that vacuums the remote journal;

/usr/bin/journalctl --directory=/var/log/journal/remote --vacuum-size=10G
