### ISSUE TITLE
Add option to show job status with systemctl service control commands

### ISSUE THREAD

**Issue by mattatobin** [systemd/systemd#5717]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

>233

### Used distribution

> Fedora 26

### Description

When using `systemctl` to control services (that is, start/stop/restart/etc.), there is no output for indicating that the job requested has completed successfully. While it is the norm that programs do not print output by default on success, it is typical that there is some kind of option/flag to override this behavior (`--verbose` or whatnot). In this case, it would be desirable to have a way to print output similar to what systemd prints during the startup and shutdown processes when this flag is specified along with the appropriate systemctl subcommand.

As an example, with a hypothetical `--show-state-messages` option for systemctl, something like the following output is desired:

```
# Successful start of service
$ sudo systemctl --show-state-messages start foo

[  OK  ] Started Fooing the Bar

# Successful stop of service
$ sudo systemctl --show-state-messages stop foo

[  OK  ] Stopped Fooing the Bar

# Failed to start service
$ sudo systemctl --show-state-messages start baz

[FAILED] Failed to start Bazzing the Foo
         See 'systemctl status baz.service' for details.

```

In addition to having the option via the command line, it would be good if it were possible to configure this at runtime to be the default behavior or not, though it is not necessary.

**Comment by wolfbeast** [comment]
Especially when it comes to services, it is essential IMHO that immediate feedback is available to get confirmation that the action was performed, and if it was successful or not. State changes should always have feedback (as opposed to one-shot tools where no error = no output is fine).

**Comment by poettering** [comment]
When a service fails to start we do show a brief message about that and will return a non-zero exit code. Only on success we don't print a message and exit with a zero exit code.

Doing it that way is kinda the way UNIX usually does this stuff. We could certianly add an optional message in the success case too, but I wonder how useful it actually would be if it is not normally visible.

**Comment by Conan-Kudo** [comment]
@poettering As I see it, it's just about allowing the admin to make a choice locally to make systemctl verbose by default. However, that is an explicitly optional task, and it's perfectly fine to not offer that.

Also, can't you use the same code used for printing the state of services during boot for this? Wiring up `systemctl` to offer the alternative output that matches what systemd itself does during startup and shutdown seems like a useful option.

**Comment by okurz** [comment]
I am sometimes encountering the problem that the initial triggering of starting succeeds, so the `systemctl start <service>` succeeds but the service is either still in `starting` state IIRC or it failed. So the safe way for myself is to do something like `systemctl start <service> && while ! systemctl is-active <service> ; do sleep 0.1; done`

or more manually

```
systemctl start <service>
systemctl status <service>
```

So I guess this is something that could be improved by moving that into one command call with an option

**Comment by mattatobin** [comment]
What does this have to do with the issue of verbose feedback for commands?

**Comment by okurz** [comment]
IMHO it's serving the same use case: You want to know what's the state after you triggered a start, isn't it?

**Comment by 4wk-** [comment]
I would definitly appreciate a `--verbose` option for `systemctl` command. Then there's the perennial question of "is it hanging or is it just busy?" Even cp, mv, rm, and ln have a verbose option and you can't get much simpler than those ;)

**Comment by hjp** [comment]
I would also like a `--verbose` option (or maybe `--debug` or `--trace`), but I think it would be more useful if it didn't just report the final state but how it got there.

For example, I have a service called `apache2-multi@.service` for starting one of multiple apache instances. It includes the line:
`ConditionPathIsDirectory=/usr/local/www/%I/config/apache/`
When I mistype the name of the instance I want to start, `systemctl start` just returns with exit code 0 and no message. `systemctl status` shows the service as loaded and dead, and `journalctl` doesn't show anything about that service. So it's hard to see what's wrong.
If `systemctl --verbose start apache2-multi@doesnotexist.service` printed something like 
`ConditionPathIsDirectory=/usr/local/www/doesnotexist/config/apache/ failed - skipping`
that would make discovering that kind of error much easier.

**Comment by kot0dama** [comment]
I must say, I myself often issue a `systemctl status` after a `systemctl start/stop/restart` to check for status and last logs.
See also discussion on https://stackoverflow.com/questions/49396098/output-from-systemctl-start-restart-stop

I also think adding a `--verbose` option (or similar) that would display the journal of the unit while performing such operations would be useful to many. We might for example have resolved an issue with configuration and want to check what is happening live, or if other errors are occurring.

I know I can have a `journactl -f` running alongside the `systemctl start/stop/restart` command in another term, but I feel it's an unwanted hassle when we can expect the command we run to display useful feedback directly with a simple flag.

**Comment by teknoraver** [comment]
Hi @mattatobin

A simple message like "service XX is started" would be useless in most cases.
Imagine a daemon starting and failing just half a second later, after the success message.
If the unit file has no errors, the binary is present and all the conditions in the unit are satisfied, the message would almost always print a success message.

**Comment by Conan-Kudo** [comment]
> A simple message like "service XX is started" would be useless in most cases.
> Imagine a daemon starting and failing just half a second later, after the success message.

I think the idea here is that while it is starting, it shows the same starting output that shows up when system services are starting while booting.

This is difficult to represent in text like this, but basically it should present the same output that shows up at boot. `--show-status-messages` essentially tells systemctl to present it the same way systemd-init does.

> If the unit file has no errors, the binary is present and all the conditions in the unit are satisfied, the message would almost always print a success message.

That's the point, it should do just that.

**Comment by wolfbeast** [comment]
It's a pretty simple premise really:

- You issue a command
- You get some form of feedback from the system

It doesn't really matter if a service might or might not fail shortly after and stop. Getting immediate feedback that the command given was processed and passed execution checks successfully is what is expected and desired. Part of the whole "intuitive machine interface" thing.

**Comment by teknoraver** [comment]
Doesn't `--show-transaction` already do this?

```
# systemctl start --show-transaction apcupsd.service
Enqueued anchor job 52842 apcupsd.service/start.
# systemctl restart --show-transaction apcupsd.service
Enqueued anchor job 53333 apcupsd.service/restart.
# systemctl stop --show-transaction apcupsd.service
Enqueued anchor job 53996 apcupsd.service/stop.
```

**Comment by 4wk-** [comment]
@teknoraver AFAIK no, because "queuing the order" is not the response code of the action actually done.
In other terms, queuing a restart does not mean that the restart is actually done (and service up) for instance.

**Comment by DaanDeMeyer** [comment]
We will never be able to tell you whether the service is "up" since unless the service is type "notify" the service will always be considered "up" by systemd even if it fails right after we restart it. What we could do is log about job results as their results come in if `--show-transaction` is used. This still won't tell you if the service is actually running after `systemctl start` finishes, but it will tell you whether systemd's jobs succeeded.

**Comment by Conan-Kudo** [comment]
@yuwata @teknoraver I think this issue should be reopened. The actual request was for the status output used at startup and shutdown to be printed by systemctl.

If I understand the code right, that means the logic from `job_emit_done_message()` in `src/core/job.c` for printing output should be exposed and used by `systemctl(1)`.

**Comment by YHNdnzj** [comment]
I tend to disagree: https://github.com/systemd/systemd/pull/30493#issuecomment-1865374006

> But that logic is all contained in one file, couldn't it be pulled out into shared logic so that it can be accessed from either systemctl(1) or pid1?

The code in `core/` is about all jobs and is bound to `manager` object. It is too much extra effort to extract that and probably expose needed information through a new dbus method.

Please provide more justifications for the proposed change. Otherwise, I don't think such refactoring is valuable.

**Comment by Conan-Kudo** [comment]
The justification is that this is literally what the OP is asking for. They wanted that output style to be accessible from `systemctl(1)`. They gave it as the _example_. 

The code for it is not in an ideal setup right now in `core/`, so it needs to be refactored so it can be accessed from `shared/` in both `core/` and `systemctl`.

**Comment by mattatobin** [comment]
> [...] what I originally asked for. Which is upstart-like responses to issuing common commands to systemctl as an optional setting likely based on an env var for those who would like to know the result of the command they issued.

**Comment by mattatobin** [comment]
If you wish an simulation of the expected output (ignoring script syntax and purpose) you can run https://dpaste.org/Pjt49 on an el8 instance.

I have had this since I posted my initial request for enhancement as a temporary stopgap but did not explicitly share it because I figured it would lower the motivation for completing this issue. Guess that is no longer a concern this many years later.

**Comment by mattatobin** [comment]
![image](https://github.com/systemd/systemd/assets/3889475/d1de9654-62ad-4880-a301-033eafd21618)

Is the type of output I would like when issuing systemctl commands. I hope this removes any and all confusion and ambiguity from the request I made in 2017 for enhancement.

**Comment by mattatobin** [comment]
At this point, I can't see any point to pursuing this for another seven years so I formally withdraw my request for enhancement which was not in any way satisfied by the designated fix attached to this issue.

This experience has soured me to systemd so much that I feel as a user of my system and your software that I just have no agency or choice or control in or over anything. To that end, I have decided to pursue non-systemd linux from scratch as well as other non-systemd complete distros and otherwise using my modified `service` script on my el-servers.

Thank you for your time and consideration.

**Comment by wolfbeast** [comment]
Please reopen. Just because the OP has gotten tired of this doesn't mean others are not feeling similarly to this feature request in systemd

**Comment by mlachal** [comment]
> Please reopen. Just because the OP has gotten tired of this doesn't mean others are not feeling similarly to this feature request in systemd

Will you become our new spokesperson?

**Comment by wolfbeast** [comment]
> Will you become our new spokesperson?

I can, if you want. This does impact me for my server administration although I do not really use Linux as my daily driver otherwise. If someone else is more exposed day-by-day and wanting to be torch bearer for this steps up, then I'll yield to them.

**Comment by DaanDeMeyer** [comment]
Note that a fix was merged https://github.com/systemd/systemd/pull/30493, it just doesn't happen to use the same output format as what you see on boot. Everyone reading this that still cares, upvote if you're OK with what we merged in https://github.com/systemd/systemd/pull/30493, downvote if that doesn't satisfy you and you want the exact same output as is shown when a system is booted.

**Comment by YHNdnzj** [comment]
As mentioned, the functionality IS implemented. What's left is pure cosmetic stuff but actually hard to implement _exactly_ without large refactoring. This needs more justification, and I don't see people working on this just to make things a little prettier.

**Comment by YHNdnzj** [comment]
> This does impact me for my server administration although I do not really use Linux as my daily driver otherwise. 

So when doing administration do you really need this cosmetic stuff? I agree with @teknoraver that a single-line output reporting job result is enough.

**Comment by mlachal** [comment]
> Note that a fix was merged #30493, it just doesn't happen to use the same output format as what you see on boot. Everyone reading this that still cares, upvote if you're OK with what we merged in #30493, downvote if that doesn't satisfy you and you want the exact same output as is shown when a system is booted.

Hi, maybe I missed something but I feel similar to https://github.com/systemd/systemd/pull/30493#issuecomment-1865322941 and am not able to read the code thus I cannot vote.

**Comment by wolfbeast** [comment]
> As mentioned, the functionality IS implemented. What's left is pure cosmetic stuff, which is however hard to implement _exactly as requested_ without large refactoring. This needs more justification, and I don't see people working on this just to make things a little prettier.

My main concern really isn't that it's pretty colours or formatted in a specific way or what not, but that the command gives suitable and meaningful feedback about the task. So just stating that "it was queued" is pointless.
If it doesn't provide meaning success/fail output (the [OK] or [FAILED] during startup, equivalent) then the issue really wasn't solved. I repeat: Getting immediate feedback that the command given was processed and passed execution checks successfully is what is expected and desired. It doesn't matter if a service stops shortly after for other reasons.
If that's not the output the PR generates, then it wasn't solved...

**Comment by YHNdnzj** [comment]
> Getting immediate feedback that the command given was processed and passed execution checks successfully is what is expected and desired.

And I've said, multiple times, that it is implemented. Just check the linked PR yourself...

**Comment by wolfbeast** [comment]
You seem to be under the impression that I can read that PR's code and know what it's doing. I don't.

but if that's what's implemented then it gets a thumbs up from me, and it should be done.

**Comment by DaanDeMeyer** [comment]
Example output:

```
➜  systemd git:(main) sudo build/systemctl --show-transaction start systemd-networkd
Enqueued anchor job 537238 systemd-networkd.service/start.
Job for systemd-networkd.service finished.
```

This shows you that systemd considers systemd-networkd started.

**Comment by wolfbeast** [comment]
> This shows you that systemd considers systemd-networkd started.

"it considers it started" is a bit vague. Has it actually been started, or is systemd just telling the user that the command was successfully queued? If it's the latter then that **isn't** useful (like I said before). it should provide feedback that the service was, in fact, started. That is what I meant with "execution checks". i.e. if it's asynchronous it should do a callback to let the user know the service startup was completed.

**Comment by wolfbeast** [comment]
Thanks for clarifying!
