### ISSUE TITLE
systemd timers do not reset after a time/date change

### ISSUE THREAD

**Issue by zealws** [systemd/systemd#6036]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemd 233

### Used distribution

> CentOS 7, Arch Linux

### In case of bug report: Expected behaviour you didn't see

> after a date change, `systemctl list-timers` should show times that are in the near future, regardless of the date before the change.

### In case of bug report: Unexpected behaviour you saw

> after a date change from 2020 to now, `systemctl list-timers` had times that were in 2020, and indicated the timers had `3 years left`

### In case of bug report: Steps to reproduce the problem

> create a timer that triggers periodically (e.g. `daily`)
> make sure the timer is started and shows up correctly in `systemctl list-timers`
> set the date into the past by 2 years
> `systemctl list-timers` will show a `NEXT` time that's 2 years in the future and `LEFT` will show `2 years left`

**Comment by poettering** [comment]
what's the precise timer unit file you used?

**Comment by ghost** [comment]
Same problem here - new motherboards clock defaulted to 2045-07-15.

    $ systemctl list-timers --no-pager                                                                                                                                       
    NEXT                         LEFT                    LAST                         PASSED                  UNIT                         ACTIVATES
    Sat 2017-07-29 18:55:49 PDT  20h left                Fri 2017-07-28 18:55:49 PDT  3h 15min ago            systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
    Sun 2045-07-16 00:00:00 PDT  27 years 11 months left Sat 2045-07-15 13:18:15 PDT  27 years 11 months left logrotate.timer              logrotate.service
    Sun 2045-07-16 00:00:00 PDT  27 years 11 months left Sat 2045-07-15 13:18:15 PDT  27 years 11 months left man-db.timer                 man-db.service
    Sun 2045-07-16 00:00:00 PDT  27 years 11 months left Sat 2045-07-15 13:18:15 PDT  27 years 11 months left shadow.timer                 shadow.service
    Mon 2045-07-17 00:00:00 PDT  27 years 11 months left Sat 2045-07-15 13:18:15 PDT  27 years 11 months left fstrim.timer                 fstrim.service

systemd 234.11 on Arch Linux

**Comment by smldis** [comment]
@poettering This is a serious bug since it is difficult to notice that your timers are not running until the user runs `systemctl list-timers` and look at the results driven by curiosity or by debugging an already happened issue.

Does someone have a workaround?

An example timer file is the following (a file of this pkg https://www.archlinux.org/packages/core/x86_64/shadow):
```
[Unit]
Description=Daily verification of password and group files

[Timer]
OnCalendar=daily
AccuracySec=12h
Persistent=true
```

**Comment by philipp-classen** [comment]
I documented my workaround here: https://unix.stackexchange.com/a/387516/29509

The timestamps are stored in `/var/lib/systemd/timers`. After manually fixing the broken timestamps (via `touch`) followed by a reboot, systemd should be in sync again.

**Comment by xoduddk123** [comment]
Restart the corresponding timer to initialize the timer trigger.(systemctl command)

	root@test:~# date 070707072000
	Fri Jul  7 07:07:00 UTC 2000
	root@test:~#
	root@test:~# systemctl status logrotate.timer
	● logrotate.timer - Daily rotation of log files
	   Loaded: loaded (/lib/systemd/system/logrotate.timer; enabled; vendor preset:
	enabled)
	   Active: active (waiting) since Thu 2018-01-25 13:58:26 UTC; 17 yea
	rs 6 months left
	  Trigger: Fri 2018-01-26 00:00:00 UTC; 17 years 6 months left
	     Docs: man:logrotate(8)
	           man:logrotate.conf(5)
	
	Jan 25 13:58:26 test systemd[1]: Stopping Daily rotation of log files.
	Jan 25 13:58:26 test systemd[1]: Started Daily rotation of log files.
	root@test:~#
	root@test:~# touch /var/lib/systemd/timers/stamp-logrotate.timer
	root@test:~#
	root@test:~# systemctl restart logrotate.timer
	root@test:~#
	root@test:~# systemctl status logrotate.timer
	● logrotate.timer - Daily rotation of log files
	   Loaded: loaded (/lib/systemd/system/logrotate.timer; enabled; vendor preset:
	enabled)
	   Active: active (waiting) since Fri 2000-07-07 07:07:57 UTC; 4s ago
	  Trigger: Sat 2000-07-08 00:00:00 UTC; 16h left
	     Docs: man:logrotate(8)
	           man:logrotate.conf(5)
	
	Jul 07 07:07:57 test systemd[1]: Stopping Daily rotation of log files.
	Jul 07 07:07:57 test systemd[1]: Started Daily rotation of log files.
	root@test:~#

**Comment by zfjagann** [comment]
This is still in `needs-reporter-feedback` but I think there's plenty of info here to repro the bug. Is anything else needed, @poettering?

**Comment by poettering** [comment]
@zfjagann so this is about persistent timers? can you provide your timer unit please, as requested?

If this is about persistent timers, i am not sure what we can do... I mean, how are we supposed to know that the time used on a previous boot as bogus?

**Comment by poettering** [comment]
If this is about persistent timers that once ran in the "future", then this is a duplicate of #6821, no? @zfjagann does your version of systemd that shows this behaviour already include the fix for that, i.e. #6823?

**Comment by okdana** [comment]
I'm not sure about persistent timers, but i know this does affect non-persistent `OnCalendar=` ones. Specifically, the previously computed time of the next firing is maintained when the clock changes. That means that:

* If the clock jumps *forwards*, any timers with a next-firing time between the old clock time and the new one are fired immediately. e.g., if the clock time was 00:00, and the timer was set to fire next at 01:00, and the clock jumps ahead to 02:00, systemd will detect that the time has passed and fire the timer.

* If the clock jumps *backwards*, systemd waits for the previously scheduled firing time. e.g., if the clock time was 01:00, and the timer was set to fire next at 02:00, and the clock jumps back to 00:00, systemd will wait an extra hour before firing the timer again. (This is the bigger problem, IMO, especially for timers with short intervals.)

In either case, things carry on more or less as normal once the timer is fired.

**Comment by klausenbusk** [comment]
Is there anyway to reset the trigger time without rebooting the system?

My server was booted with a incorrect clock (2098-01-01) and after correct the clock, I can't get my user service to trigger in a foreseeable future.

```
$ systemctl --user cat borg.service
[Unit]
Description=BorgBackup

[Service]
ExecStart=/home/backup/borg/backup.sh

[Install]
WantedBy=multi-user.target
$ systemctl --user status borg.timer
● borg.timer - Run borg.service every two hours
   Loaded: loaded (/home/backup/.config/systemd/user/borg.timer; enabled; vendor preset: enabled)
   Active: active (waiting) since Mon 2019-09-02 11:33:42 CEST; 1h 22min ago
  Trigger: Thu 2098-01-02 01:18:59 CET; 78 years 4 months left

sep 02 11:33:42 arch systemd[334]: Started Run borg.service every two hours.
$ systemctl --user stop borg.timer
$ systemctl --user daemon-reexec
$ systemctl --user daemon-reload
$ systemctl --user start borg.timer
$ systemctl --user status borg.timer
● borg.timer - Run borg.service every two hours
   Loaded: loaded (/home/backup/.config/systemd/user/borg.timer; enabled; vendor preset: enabled)
   Active: active (waiting) since Mon 2019-09-02 12:56:39 CEST; 3s ago
  Trigger: Thu 2098-01-02 01:18:59 CET; 78 years 4 months left

sep 02 12:56:39 arch systemd[334]: Started Run borg.service every two hours.
```

**Comment by AfroThundr3007730** [comment]
@klausenbusk Systemd timers store a timestamp file to record the last time the timer was triggered. For system level timers, they're stored in `/var/lib/systemd/timers/stamp-*` and for user timers they're in `~/.local/share/systemd/timers/stamp-*`.

Simply `touch`ing the errant file will reset the timer trigger date, then another `systemctl --user daemon-reload` should do the trick. Found this info on the [ArchWiki](https://wiki.archlinux.org/index.php/Systemd/Timers#Management).

**Comment by klausenbusk** [comment]
> @klausenbusk Systemd timers store a timestamp file to record the last time the timer was triggered. For system level timers, they're stored in `/var/lib/systemd/timers/stamp-*` and for user timers they're in `~/.local/share/systemd/timers/stamp-*`.
> 
> Simply `touch`ing the errant file will reset the timer trigger date, then another `systemctl --user daemon-reload` should do the trick. Found this info on the [ArchWiki](https://wiki.archlinux.org/index.php/Systemd/Timers#Management).

 `~/.local/share/systemd/timers` does not exist, which makes sense as the stamp files is only created if `Persistent=true` (I think?), which isn't the case for me. Anyways thanks for the hint! I assume the "state" is currently stored in memory.

**Comment by R-VdP** [comment]
@poettering has this ever been solved?

I am running into this issues with NixOS machines (using systemd v243) running on VirtualBox. VirtualBox has a weird issue where the time starts off several months in the future before being corrected by the guest utils service, but all of my systemd timers (non-persistent ones, using onCalendar), maintain the old timestamp and will not fire for the next several months.

**Comment by dmigowski** [comment]
The fix for systemd would be easy! If the last-run-timestamp is in the future consider it being bogus and ignore it. Maybe add a minute here to be able to work with small time jumps introduced from NTP hickups, but everything after that should just be ignored.

**Comment by R-VdP** [comment]
I cannot believe that this bug is seriously still present 3 years down the road. And there is not even a workaround for non-persistent timers.

I have about 20 servers affected by this issue.

**Comment by ibalintha** [comment]
> 

Any update? It's clear and very easy to reproduce the issue below.
Hope it can be changed

- If the clock jumps backwards, systemd waits for the previously scheduled firing time. e.g., if the clock time was 01:00, and the timer was set to fire next at 02:00, and the clock jumps back to 00:00, systemd will wait an extra hour before firing the timer again. (This is the bigger problem, IMO, especially for timers with short intervals.)

**Comment by joaofl** [comment]
This issue still exists in `systemd 244`. The next trigger for a daily timer is a fex weeks from now:
```
root@machine:~# systemctl list-timers --all
NEXT                         LEFT                LAST                         PASSED     UNIT                         ACTIVATES
Sat 2022-06-04 22:07:58 UTC  21h left            Sun 2022-05-29 23:59:20 UTC  5 days ago systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
Wed 2022-06-29 11:05:55 UTC  3 weeks 4 days left n/a                          n/a        logrotate.timer              logrotate.service
```

And the worst of it is, I cannot get this fixed without restarting the machine. I tried all the below commands, and none of them did the job of reestablishing the trigger to the right time:

```
systemctl stop logrotate.timer
systemctl disable logrotate.timer
touch /var/lib/systemd/timers/stamp-logrotate.timer
systemctl clean --what=state logrotate.timer
systemctl enable logrotate.timer
systemctl daemon-reload
systemctl reload-or-restart logrotate.timer
```
And still in the end I get the same `NEXT Wed 2022-06-29 11:05:55 UTC  3 weeks 4 days left`.

Anybody have any idea on how to restart this timer without a reboot?

**Comment by markstos** [comment]
@joaofl Can you share your time file contents so we can confirm it's the same issue as others and not a different variation?

**Comment by markstos** [comment]
The change makes sense to me. There's a small typo in the comment: `s/withe/with/`

**Comment by yuwata** [comment]
@joaofl The relevant part was modified 26698337f3842842af51cd007485f1dcd7c43cf2 and 58afc4f8e41176c890b171f422b988fd83887605. If these do not fix the issue, please submit as a PR.

**Comment by joaofl** [comment]
@yuwata 
Indeed, commit https://github.com/systemd/systemd/commit/26698337f3842842af51cd007485f1dcd7c43cf2 seems to solve the problem. The following solution on commit https://github.com/systemd/systemd/commit/58afc4f8e41176c890b171f422b988fd83887605 seems to improve the implementation, but does not compile on v244 out of the box, so I tested the first one.

What I found out is that both my patch and commit https://github.com/systemd/systemd/commit/26698337f3842842af51cd007485f1dcd7c43cf2 only fix the problem if the unit.timer file have the both configs set to true:
```
OnClockChange=true
OnTimezoneChange=true
```
Otherwise, we see in the logs:
```
Oct 02 00:04:27 L98 systemd[1]: logrotate.timer: Timezone change, recalculating next elapse.
Oct 02 00:04:27 L98 systemd[1]: logrotate.timer: Realtime timer elapses at Thu 2024-10-03 00:00:00 CEST.
Jul 10 23:59:48 L98 systemd[1]: logrotate.timer: Time change, recalculating next elapse.
Jul 10 23:59:48 L98 systemd[1]: logrotate.timer: Realtime timer elapses at Thu 2024-10-03 00:00:00 CEST.
```
A `systemctl restart logrotate.timer`  does fix the problem, an get the far-future trigger set backwards.

For me that does seem to be the expected behavior, right?

If so, I believe some more investigation is requred here.

**Comment by joaofl** [comment]
I confimed that the PR https://github.com/systemd/systemd/commit/26698337f3842842af51cd007485f1dcd7c43cf2 only fixes the problem for when `OnClockChange=true` and `OnTimezoneChange=true`. Otherwise `next_elapse` would still be stuck with the future date.

To fix the issue I added the following check on top of the changes done in https://github.com/systemd/systemd/commit/26698337f3842842af51cd007485f1dcd7c43cf2. I believe this has to be tested with the latest versions of systemd to see if this problem persists there, and it this check makes sense for upstream:

```patch
diff --git a/src/core/timer.c b/src/core/timer.c
index 051ca76..f3fb1b9 100644
--- a/src/core/timer.c
+++ b/src/core/timer.c
@@ -374,6 +374,11 @@ static void timer_enter_waiting(Timer *t, bool time_change) {
                          * to that. If we don't, just start from
                          * the activation time. */
 
+                        if (time_change){
+                                t->last_trigger.realtime = ts.realtime;
+                                log_unit_debug(UNIT(t), "Last trigger updated on time change.");
+                        }
+
                         if (t->last_trigger.realtime > 0)
                                 b = t->last_trigger.realtime;
                         else {
@@ -391,8 +396,11 @@ static void timer_enter_waiting(Timer *t, bool time_change) {
                          * if the scheduled time has already passed, set the time when systemd
                          * first started as the scheduled time.
                          * Also, we don't have to check t->persistent since the logic implicitly express true. */
-                        if (v->next_elapse < UNIT(t)->manager->timestamps[MANAGER_TIMESTAMP_USERSPACE].realtime)
-                                v->next_elapse = UNIT(t)->manager->timestamps[MANAGER_TIMESTAMP_USERSPACE].realtime;
+                        dual_timestamp dts;
+                        dual_timestamp_from_monotonic(&dts, UNIT(t)->manager->timestamps[MANAGER_TIMESTAMP_USERSPACE].monotonic);
+
+                        if (v->next_elapse < dts.realtime)
+                                v->next_elapse = dts.realtime;
 
                         if (!found_realtime)
                                 t->next_elapse_realtime = v->next_elapse;

```

**Comment by joaofl** [comment]
I've confirmed that this issue still exists in the main branch, and made a PR with the test-case in which it fails and a potential fix for the problem. Please check it here: https://github.com/systemd/systemd/pull/24131

**Comment by keszybz** [comment]
It's too late in the release cycle to change things in this area. Let's try to do better for v257.

**Comment by drawks** [comment]
> opened [on May 25, 2017](https://github.com/systemd/systemd/issues/6036#issue-231493484)

🧐
