### ISSUE TITLE
MSI-PR200: screen flickering issue:  60-keyboard.hwdb extend RFE

### ISSUE THREAD

**Issue by djfd** [systemd/systemd#6972]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 234

### Used distribution

> ArchLinux

*Issue*: backlight is flickering when trying to change screen brighthess by any of means: keyboard Fn+ keys, gnome shell applet slider, direct write to /sys/class/backlight/acpi_video0/brightness

Also mentioned [here](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/756509) and [there](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/178860) even if ancient enough

As per [60-keyboard.hwdb](https://github.com/systemd/systemd/blob/master/hwdb/60-keyboard.hwdb#L921)
```
# some MSI models generate ACPI/input events on the LNXVIDEO input devices,
# plus some extra synthesized ones on atkbd as an echo of actually changing the
# brightness; so ignore those atkbd ones, to avoid loops
```
Adding this description string below to the mentioned file resolves the issue
```
evdev:atkbd:dmi:bvn*:bvr*:bd*:svnMicro-Star*:pn*PR200*:pvr*
```
```
#udevadm info /dev/input/event0
> P: /devices/platform/i8042/serio0/input/input0/event0
> N: input/event0
> E: DEVNAME=/dev/input/event0
> E: DEVPATH=/devices/platform/i8042/serio0/input/input0/event0
> E: ID_BUS=i8042
> E: ID_INPUT=1
> E: ID_INPUT_KEY=1
> E: ID_INPUT_KEYBOARD=1
> E: KEYBOARD_KEY_a0=mute
> E: KEYBOARD_KEY_ae=volumedown
> E: KEYBOARD_KEY_b0=volumeup
> E: KEYBOARD_KEY_b2=www
> E: KEYBOARD_KEY_c2=ejectcd
> E: KEYBOARD_KEY_df=sleep
> E: KEYBOARD_KEY_e2=bluetooth
> E: KEYBOARD_KEY_e4=f21
> E: KEYBOARD_KEY_ec=email
> E: KEYBOARD_KEY_ee=camera
> E: KEYBOARD_KEY_f6=wlan
> E: KEYBOARD_KEY_f7=reserved
> E: KEYBOARD_KEY_f8=reserved
> E: KEYBOARD_KEY_f9=search
> E: LIBINPUT_ATTR_KEYBOARD_INTEGRATION=internal
> E: LIBINPUT_DEVICE_GROUP=11/1/1/ab41:isa0060/serio0
> E: MAJOR=13
> E: MINOR=64
> E: SUBSYSTEM=input
> E: TAGS=:power-switch:
> E: USEC_INITIALIZED=10636105
```
```
$ cat /sys/class/dmi/id/modalias
dmi:bvnAmericanMegatrendsInc.:bvrA1221IMSV1.51:bd01/19/2010:svnMicro-StarInternational:pnMSINotebookPR200:pvrVer1.000:rvnMSI:rnMS-1221:rvrVer1.000:cvnToBeFilledByO.E.M.:ct10:cvrToBeFilledByO.E.M.:
```

**Comment by poettering** [comment]
Not sure I follow. @martinpitt something for you?

**Comment by poettering** [comment]
btw, if you have a specific change in mind, make sure to file a PR with it, otherwise it's unlikely to happen, as none of us has your specific piece of hw...

**Comment by djfd** [comment]
```diff
diff -aur before/systemd/hwdb/60-keyboard.hwdb after/systemd/hwdb/60-keyboard.hwdb
--- before/systemd/hwdb/60-keyboard.hwdb        2017-09-12 06:07:43.000000000 +1000
+++ after/systemd/hwdb/60-keyboard.hwdb 2017-10-03 16:59:31.948867300 +1000
@@ -923,6 +923,7 @@
 evdev:atkbd:dmi:bvn*:bvr*:bd*:svnMICRO-STAR*:pn*U100*:pvr*
 evdev:atkbd:dmi:bvn*:bvr*:bd*:svnMICRO-STAR*:pn*N033:*
 evdev:atkbd:dmi:bvn*:bvr*:bd*:svnMicro-Star*:pn*VR420*:pvr*
+evdev:atkbd:dmi:bvn*:bvr*:bd*:svnMicro-Star*:pn*PR200*:pvr*
  KEYBOARD_KEY_f7=reserved
  KEYBOARD_KEY_f8=reserved
 
```
pls, don't ask me for a PR, I simply do not know how to do that, sorry

given the patch above could you please make a PR?

**Comment by djfd** [comment]
**UPD2** Sorry, this does not work on vanilla DSDT of the laptop

small update
Even better patch, allowing to suppress a logs pollution with a lot of messages like these:
```
atkbd serio0: Unknown key pressed (translated set 2, code 0xf8 on isa0060/serio0).
atkbd serio0: Use 'setkeycodes e078 <keycode>' to make it known.
atkbd serio0: Unknown key released (translated set 2, code 0xf8 on isa0060/serio0).
atkbd serio0: Use 'setkeycodes e078 <keycode>' to make it known.
```
```diff
diff -aur a/systemd/hwdb.d/60-keyboard.hwdb b/systemd/hwdb.d/60-keyboard.hwdb
--- a/systemd/hwdb.d/60-keyboard.hwdb   2017-09-12 06:07:43.000000000 +1000
+++ b/systemd/hwdb.d/60-keyboard.hwdb   2017-10-07 05:33:59.814652696 +1000
@@ -923,8 +923,9 @@
 evdev:atkbd:dmi:bvn*:bvr*:bd*:svnMICRO-STAR*:pn*U100*:pvr*
 evdev:atkbd:dmi:bvn*:bvr*:bd*:svnMICRO-STAR*:pn*N033:*
 evdev:atkbd:dmi:bvn*:bvr*:bd*:svnMicro-Star*:pn*VR420*:pvr*
- KEYBOARD_KEY_f7=reserved
- KEYBOARD_KEY_f8=reserved
+evdev:atkbd:dmi:bvn*:bvr*:bd*:svnMicro-Star*:pn*PR200*:pvr*
+ KEYBOARD_KEY_f7=unknown
+ KEYBOARD_KEY_f8=unknown
 
 # MSI Wind U90/U100 generates separate touchpad on/off keycodes so ignore touchpad toggle keycode
 evdev:atkbd:dmi:bvn*:bvr*:bd*:svnMICRO-STAR*:pnU90/U100:*
```

**Comment by martinpitt** [comment]
@djfd : Fixed in PR #8018. Sorry for the long delay, and thanks for the fix!

**Comment by djfd** [comment]
@martinpitt Hello, Martin!

It is okay, no problem. However may I ask you do not apply this patch right now? Just have reread the thread, and I cannot remember for sure what patch version I am using, and no way to check it right now... Please let me 1 day to verify how did I actually solved it for myself...

Thanks

**Comment by martinpitt** [comment]
@djfd: Sure!

**Comment by djfd** [comment]
@poettering @martinpitt 

this version of a patch is currently installed (and works just fine) on the target:
```diff
diff -aur a/60-keyboard.hwdb b/60-keyboard.hwdb
--- a/60-keyboard.hwdb  2018-01-15 23:02:36.000000000 +1000
+++ b/60-keyboard.hwdb  2018-01-27 21:51:39.571634476 +1000
@@ -925,6 +925,7 @@
 evdev:atkbd:dmi:bvn*:bvr*:bd*:svnMICRO-STAR*:pn*U100*:pvr*
 evdev:atkbd:dmi:bvn*:bvr*:bd*:svnMICRO-STAR*:pn*N033:*
 evdev:atkbd:dmi:bvn*:bvr*:bd*:svnMicro-Star*:pn*VR420*:pvr*
+evdev:atkbd:dmi:bvn*:bvr*:bd*:svnMicro-Star*:pn*PR200*:pvr*
  KEYBOARD_KEY_f7=reserved
  KEYBOARD_KEY_f8=reserved
 
```

A variant with ```KEYBOARD_KEY_XX=unknown``` only stops logs pollution, main issue is still here, brightness down/up keys generate duplicate events. With all up to date software I cannot see flickering now, but adjustment range is 4 levels, instead of 9 expected bright levels.

Sorry for the delay, computer was in disassembled state, for some parts replacement...

**Comment by martinpitt** [comment]
@djfd : OK, that was what I was afraid of. I changed the PR to this simpler version, we can change it again later on to fix the noise (in case we find a solution).

**Comment by djfd** [comment]
@martinpitt Thank you!

At that time I tracked this [mis]behaviour down to its source, and If I can remember right, it was in the keyboard driver. I mean keys flags (reserved, undefined) interpretation. just FYI.
