### ISSUE TITLE
btrfs root: frequent races when mounting subvolumes 

### ISSUE THREAD

**Issue by lisaev** [systemd/systemd#927]
System: Arch Linux x86_64
.             systemd 224
.             kernel 4.1.4

Setup: The entire ssd is a btrfs block dev (no partitions). Instead, I use subvolumes _root for /, _var for /var and _home for /home. The fstab is correct and the system boots fine in about 70% of the time. However, in 30% it fails to boot with systemD saying that either /var or /home is failed to mount, and I am dropped into an emergency shell.

The mount command quits with errno 32 : /dev/sda already mounted. Which is... True.

This happens on real hw and in all VMs I used btrfs on. Of course, manually mounting all subvolumes works fine.

Thanks,
Leonid.

PS: On a side note, not everyone runs journald, so it might be useful to print an error message to console so that people don't hack their systems to get an exit code, instead of saying "run journalctl -xyz".

**Comment by arvidjaar** [comment]
> The mount command quits with errno 32 : /dev/sda already mounted. Which is... True.

is _Which is... True_ part of message? Please show **exact** message you get.

> not everyone runs journald

systemd without journald is likely not supported at all.

**Comment by heftig** [comment]
Also, please post your `/etc/fstab`.

**Comment by richardmaw-codethink** [comment]
@lisaev  I've seen this happen before from bugs in btrfs, I have my doubts that this is a bug in systemd since I have been running a system with the same sort of layout using systemd as the init for a couple of years.
I've seen this issue a couple of times before and every time it has been a bug in btrfs, rather than systemd.

**Comment by lisaev** [comment]
This is from my VM just now:

```
# systemctl status home.mount -l
● home.mount - /home
   Loaded: loaded (/etc/fstab)
   Active: failed (Result: exit-code) since Tue 2015-08-11 15:17:37 UTC; 1min 31s ago
    Where: /home
     What: /dev/disk/by-uuid/4e197a82-c0fd-4f99-bd69-2bd773ed4aa4
     Docs: man:fstab(5)
           man:systemd-fstab-generator(8)
  Process: 183 ExecMount=/usr/bin/mount /dev/disk/by-uuid/4e197a82-c0fd-4f99-bd69-2bd773ed4aa4 /home -n -t btrfs -o rw,nosuid,nodev,noexec,relatime,space_cache,subvol=homevol,autodefrag (code=exited, status=32)

Aug 11 15:17:37 archvm-brtfs systemd[1]: Mounting /home...
Aug 11 15:17:37 archvm-brtfs mount[183]: mount: /dev/vdb is already mounted or /home busy
Aug 11 15:17:37 archvm-brtfs mount[183]: /dev/vdb is already mounted on /
Aug 11 15:17:37 archvm-brtfs systemd[1]: home.mount: Mount process exited, code=exited status=32
Aug 11 15:17:37 archvm-brtfs systemd[1]: Failed to mount /home.
Aug 11 15:17:37 archvm-brtfs systemd[1]: home.mount: Unit entered failed state.

# cat /etc/fstab 
UUID=4e197a82-c0fd-4f99-bd69-2bd773ed4aa4 /     btrfs ro,nodev,relatime,space_cache,subvol=rootvol,autodefrag 0 0
UUID=4e197a82-c0fd-4f99-bd69-2bd773ed4aa4 /home btrfs rw,nosuid,nodev,noexec,relatime,space_cache,subvol=homevol,autodefrag 0 0
UUID=4e197a82-c0fd-4f99-bd69-2bd773ed4aa4 /var  btrfs rw,nosuid,nodev,noexec,relatime,space_cache,subvol=varvol,autodefrag 0 0
UUID=93434e94-e325-4c36-921f-71cee26c51b1 /boot ext4  ro,nosuid,nodev,noexec,relatime,data=ordered 0 2

tmpfs /dev/shm tmpfs noexec,nosuid,nodev 0 0
tmpfs /tmp     tmpfs noexec,nosuid,nodev 0 0

# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
fd0      2:0    1    4K  0 disk 
sr0     11:0    1 1024M  0 rom  
vda    254:0    0  200M  0 disk 
└─vda1 254:1    0  199M  0 part /boot
vdb    254:16   0    5G  0 disk /var

# systemd-detect-virt 
kvm
```

To answer specific questions:

@richardmaw-codethink: FYI mount /p1 /m1 && sleep 1 && mount /p2 /m2 && ... && mount /pN /mN works fine. All I _really_ want to know is how to serialize systemd mount units in the above fashion. I already do so with many services...

@arvidjaar: Yes this is exactly what the message said :) On top of that, systemd explained to me what actually happened using a pleasant female voice and then submitted the original bugreport... right before it brewed my coffee. Well, not really. I actually had to wrap /bin/mount in a shell script and capture the output of the failed command.

**Comment by richardmaw-codethink** [comment]
@lisaev That's odd, btrfs shouldn't be giving you EBUSY.
I still think it's a bug in btrfs, but you could try http://www.freedesktop.org/software/systemd/man/systemd.mount.html#x-systemd.requires= to serialize them.

**Comment by lisaev** [comment]
@richardmaw-codethink: Thanks a lot! I didn't know about that mount option.

So, I appended the mount entries for /var and /home in fstab with

```
# cat /etc/fstab
...
... /var... x-systemd.requires=sleep-root.service
... /home... x-systemd.requires=sleep-var.service
...
```

and added two simple services:

```
# cat /etc/systemd/system/sleep-root.service
[Unit]
Description=A delay after mounting /
DefaultDependencies=no
After=-.mount

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/sleep 4

# cat /etc/systemd/system/sleep-var.service 
[Unit]
Description=A delay after mounting /var
DefaultDependencies=no
After=var.mount

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/sleep 4
```

(4s delay because systemd starts spewing "the job is running..." notifications at 5s). Now, I can have a non-interacting reproducible boot like in the pre-systemd times (only a bit slower):

```
# systemd-analyze 
Startup finished in 32.525s (kernel) + 11.497s (userspace) = 44.023s

# systemd-analyze blame | grep sleep-
          4.044s sleep-root.service
          4.012s sleep-var.service
```

Regarding the kernel btrfs-related bug, I don't know. Nothing besides systemd seems to be able to trigger it. And I see no kernel-level error messages.

But anyway, for me this issue is resolved :) Thanks again.

**Comment by arvidjaar** [comment]
> Nothing besides systemd seems to be able to trigger it.

systemd starts mounts concurrently as long as they are not nested so it stresses btrfs more than others. You really should contact btrfs list, as such errors are hard to reproduce and having system that can reliably trigger them is of great help to debugging.

> for me this issue is resolved

Good. Now help to actually fix it for others.

**Comment by poettering** [comment]
My educated guess here is that you are using different mount options for the root partition and your subvolumes. And the kernel probably just refused mounting the subvols with different options because it wants them to be the same for all mount options.

Specifically, if you drop "autodefrag" and "space_cache" from your fstab options, does it make this work reliably?

Or conversely, if you add "autodefrag" and "space_cache" to the "rootflags=" kernel cmdline option, does it fix the issue for you? (presuming you do not have them there yet).

The race you are encountering is probably between "systemd-remount-fs.service" fixing up the root mount options before we mount the first subvol. if we fix up the root mount point options before mounting the first subvol everything is fine, if it happens in the opposite order you see what you see.

Not sure what we could do about this from the systemd side. I'd probably consider this a kernel problem (it should not fail mounts with EBUSY when the options don't match, but at best warn about it), or a local setup problem (since /etc/fstab was changed, but rootflags= wasn't).

Anyway, would be good if you could check what I suggest above, so that no "sleep 4" or any hacks like that are necessary.

**Comment by lisaev** [comment]
@poettering: I am confused by your post. So, let me answer the questions as I understood them.

(1) Your guess is right, as the fstab above shows. Specifically, / is (re)mounted ro,nodev, while other FS are - rw,noexec,nosuid,nodev. Autodefrag is irrelevant, since I had boot failures also on machines w/o this option. So the answer to your 1st quastion is no.

(2) I don't understand the problem with different mountoptions. What's the practical point of using subvols (and btrfs as opposed to lvm) if I can't mount different subvolumes with different options? Here is my /proc/cmdline (I only know of rootfalgs in connection to it):

```
# cat /proc/cmdline 
BOOT_IMAGE=../vmlinuz-linux root=/dev/disk/by-uuid/4e197a82-c0fd-4f99-bd69-2bd773ed4aa4 ro ipv6.disable=1 security=yama init=/usr/lib/systemd/systemd rootflags=subvol=rootvol console=ttyS0 nomodeset initrd=../initramfs-linux.img
```

(3) I don't understand the issues with remounting / and mounting other subvols. From my experience, these operations (when performed manually at least) completely commute. I remount / at any time w/o issues. I also tried breaking boot at the initramfs when only / is mounted with default options. Then manually mounting the fstab (or with mount -a) and then remounting /, or vice-versa. Everything worked.

Perhaps my layout is not clear:

```
# btrfs subvolume list /mnt
ID 257 gen 6917 top level 5 path rootvol
ID 258 gen 6923 top level 5 path homevol
ID 259 gen 6929 top level 5 path varvol
# ls /mnt
homevol/  rootvol/  varvol/
```

(4) Finally, I don't see why the 4s delay that I used is a hack, especially it makes my headless machine boot reliably.

**Comment by arvidjaar** [comment]
> Specifically, / is (re)mounted ro,nodev, while other FS are - rw,noexec,nosuid,nodev. 

@lisaev Yes, that's the problem

```
bor@bor-Latitude-E5450:~/src/linux$ sudo mount -o ro /dev/loop0 /tmp/btrfs
bor@bor-Latitude-E5450:~/src/linux$ sudo mount -o subvol=subvol /dev/loop0 /tmp/btrfs/submnt
mount: /dev/loop0 уже примонтирован или /tmp/btrfs/submnt занят
mount: согласно mtab, /dev/loop0 примонтирован на /tmp/btrfs
```

> What's the practical point of using subvols (and btrfs as opposed to lvm) if I can't mount different subvolumes with different options?

You better ask this question on btrfs list. But I'm not sure what exact semantic it should have. You still have the single file system and every write operation affects the whole file system including parts that are allegedly read-only.

@poettering 

> The race you are encountering is probably between "systemd-remount-fs.service" fixing up the root mount options before we mount the first subvol. ... Not sure what we could do about this from the systemd side. 

This (race) should not happen upstream as remount-fs runs before any local filesystem. But then it means it will consisntently fail to mount those subvolumes marked "rw" ... this really should be addressed on kernel side.

**Comment by lisaev** [comment]
@arvidjaar: ???

No, it's not. The following is done from  Arch 03/2015 livecd:

```
# uname -a
Linux archiso 3.18.6-1-ARCH #1 SMP PREEMPT Sat Feb 7 08:44:05 CET 2015 x86_64 GNU/Linux
# mount -v -o ro,noexec /dev/vdb /mnt
mount: /dev/vdb mounted on /mnt
# mount -v -o subvol=rootvol /dev/vdb /mnt/t
mount: /dev/vdb mounted on /mnt/t
# findmnt -l | grep /mnt
/mnt /dev/vdb btrfs ro,noexec,relatime,space_cache
/mnt/t /dev/vdb[/rootvol] btrfs rw,relatime,space_cache
```

Your box is broken somehow but you can verify that I'm right using any Archlinux livecd. Otherwise, please tell me how I did this:

```
$ findmnt -l | grep vdb
/                          /dev/vdb[/rootvol] btrfs      ro,nodev,relatime,space_cache,autodefrag
/var                       /dev/vdb[/varvol]  btrfs      rw,nosuid,nodev,noexec,relatime,space_cache,autodefrag
/home                      /dev/vdb[/homevol] btrfs      rw,nosuid,nodev,noexec,relatime,space_cache,autodefrag
$ uname -a
Linux archvm-brtfs 4.1.5-1-ARCH #1 SMP PREEMPT Tue Aug 11 15:41:14 CEST 2015 x86_64 GNU/Linux
```

Notice, your error message is completely clear & race free. Hence, there is nothing to address on the kernel side except an _academic_ problem of split-microsecond mounts of embedded filesystems which is unlikely to be fixed in the near future because /me, personally, have more important things to do than restarting the VM all day long.

In practice, it is systemd who fails to boot a machine, either because of internal error, or by triggering the above academic issue, in which case it is _systemd_ robustness problem as the above exercise with delays shows (thanks again, @richardmaw-codethink, btw). I don't really care what this is -- I have my fix.

**Comment by lisaev** [comment]
Same with Linux 4.1.6.

**Comment by poettering** [comment]
@lisaev if @arvidjaar is right, it's really purely about the "ro" flag. With the fstab options you use, you basically configure the "ro" flag for the whole btrfs fs in a conflicting way. To set only the ro mount option for one specific subvol consider using "btrfs property set" with the "ro" property. This allows you to set a per subvol ro flag without involving fstab at all. Alternatively you can set the ro propery of the ("bind") mount point rather than the whole file system. Specifically, use "mount ... -o ro,bind,remount" to set it.

This confusion stems from the fact I guess that there are three read-only flags maintained by the kernel: one for the whole btrfs file system, one for each mount point of it, and then one for each btrfs subvol. You chose to configure the first one, but you cannot really do that for each subvol, because it is global. If you instead configure one of the latter two you should be on the safe side however.

**Comment by poettering** [comment]
Anyway, this is a kernel problem, closing hence.

**Comment by lisaev** [comment]
@poettering, really? As I already said, @arvidjaar is wrong.

Just for the sake of completeness, see this commit https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/btrfs/super.c?id=773cd04ec1911abb33cf9538b65f55b76cad5d92 (it also links to a commit by Harald Hoyer that implemented exactly what you said).

**Comment by arvidjaar** [comment]
@lisaev I see. Thank you for the pointer! Yes, my kernel is too old for this. Sorry for the noise.

**Comment by dwm** [comment]
For anyone running into this issue today, it's been acknowledged as a deficiency in btrfs; see:

https://patchwork.kernel.org/patch/8958861/

At time of writing, a fix doesn't appear to have been applied to the kernel.  However, sleeping for multiple seconds doesn't appear to be necessary; at least in my initial experiments, you can efficiently serialise mounts as @richardmaw-codethink suggested by having each one depend explicitly on the previous, e.g:

```
UUID=[…] /              btrfs   compress,subvol=@,ro                                    0       0
UUID=[…] /var           btrfs   compress,subvol=@var,x-systemd.requires=-.mount         0       0
UUID=[…] /var/tmp       btrfs   compress,subvol=@var@tmp,x-systemd.requires=var.mount   0       0
UUID=[…] /root          btrfs   compress,subvol=@root,x-systemd.requires=var-tmp.mount  0       0
UUID=[…] /mnt/btrfs     btrfs   compress,subvol=/,x-systemd.requires=root.mount         0       1
```

**Comment by arvidjaar** [comment]
@dwm 

> At time of writing, a fix doesn't appear to have been applied to the kernel.

If you scroll patchwork link to the bottom

> And this is a wrong fix. It will break the existing semantics of mixed ro/rw mounts.
